### ISSUE TITLE
url_for method in blueprint

### ISSUE THREAD

**Issue by gsemet** [huge-success/sanic#1029]
Hello
I split my apis in several blueprint files and so do not have direct access to the global "app" object to call `url_for` from the blueprint files. Is it possible to add a url_for method in the blueprint so this would be possible to do:
```
bp = Blueprint('bp1', url_prefix="/api/v1")

@bp.route('/foo')
async def foo():
    ...
    bp.url_for("path.to.the.view")
```

**Comment by Garito** [comment]
You have it @ request.app.url_for

But! I have something similar (blueprints besides the app file where I define "root" paths) and I can't access the routes outside the blueprints

Is this expected? How can I?

Thanks!
