### ISSUE TITLE
Websockets lifecycle hooks and response groups, synchronous beahviour

### ISSUE THREAD

**Issue by dszmaj** [huge-success/sanic#1044]
Hey,
unfortunately I couldn't find anything that point me at right direction about this.

How to handle on_connection, on_message, on_close websocket events? I'm looking for a way to write this similar to django channels where consumers have methods for this so I can for ex authorize websocket connection. For now I see that this main handler gets already opened connection.

Is there a way to create response groups with specific id's? Or any implementation that can sanely queue the messages (with redis for ex)?

Thank you for any time and effort to try answering those questions.

Best regards,
Dominik

PS. Really great work with this framework, reasonably easy to work with and very little overhead over logic code.

**Comment by dszmaj** [comment]
Also I discovered that for websockets it don't behave asynchronous.

Let's assume that I have a query running 5s. I make 10 fast frames in js loop in the browser. Last response is after 50s and should be like 10 - 15s or so.

Is it possible that for a websocket connection messages are consumed synchronously (but without blocking, tested) one after another? From async system I would assume that queries will hit db in first second nearly all at once.

**Comment by ahopkins** [comment]
@dszmaj This question is quite old at this point, so I am not sure if it is relevant or not any more. I am closing it for now. As you probably already know by now, Sanic uses the [websockets](https://websockets.readthedocs.io/en/stable/intro.html) package. It is not event based in that you do not create callbacks for specific events (like you would in JS, for example, with a websocket client).

Instead, you create [handlers that are loops](https://websockets.readthedocs.io/en/stable/intro.html#common-patterns) whose job it is to consume or produce messages.
