### ISSUE TITLE
Sanic.run argument log_config is invalid

### ISSUE THREAD

**Issue by jmurrayufo** [huge-success/sanic#1051]
Following the documentation, and attempting to turn off logging, by setting the `log_config` argument to `None`. 

Test app is as follows: 
```python
#!/usr/bin/env python3
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run( log_config = None )
```

Running test app results in the following.
```
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    app.run( log_config = None )
TypeError: run() got an unexpected keyword argument 'log_config'
```

**Comment by jmurrayufo** [comment]
Seems that the github docs are more up to date, and the Read The Docs copy is out of date?

**Comment by r0fls** [comment]
Ya the docs are supposed to build/publish themselves but they seem to fail a lot.

**Comment by sjsadowski** [comment]
I think we've fixed the documentation issue with RTD, so we should be ok now.
