### ISSUE TITLE
httptools is now safe for header field fragmentation

### ISSUE THREAD

**Issue by youknowone** [huge-success/sanic#1057]
Related old fix: #756
New httptools release: 0.0.10

We can bump httptools up to recent release and drop #756

**Comment by sjsadowski** [comment]
Since httptools is not pinned (currently) it should pick up the current version on install.

**Comment by youknowone** [comment]
Did you remove the fragment and pinned httptools? That's what you should do.

**Comment by youknowone** [comment]
Why I still see the workaround code on master branch? https://github.com/huge-success/sanic/blob/master/sanic/server.py#L234

**Comment by youknowone** [comment]
The fragment workaround is not a essential part of sanic if you use recent version of httptools. It means it is a pure useless overhead of sanic.
When you don't close the issue, I *or someone* will find the issue and remove the code one day. Now, the issue is hidden and it will not be found again without additional investigation cost.

Your decision is weird. If I will submit a PR right now, why should I reopen the issue? People who know an issue don't need any opened issue to write and submit a PR. The issues exist for project, not for me.

@channelcat @seemethere @r0fls do you maintainers have any ideas?

**Comment by vltr** [comment]
@youknowone are you refering as workaround how the whole `on_header` method deals with the values received from `httptools` or only the check on the line you highlighted that checks the payload size described in the headers?

**Comment by youknowone** [comment]
@vltr I am referring #756 which added workaround to handle header fragment. I am sorry if the new link to specific line confused you.

**Comment by vltr** [comment]
@youknowone no need to worry about that! :wink: I'm just trying to understand the specifics in here so a proper solution can be provided. I'm all in to understand the real problem, if you still have the patience to provide the overall problem some thoughts or context (I hope I'm not asking for too much in here).

**Comment by youknowone** [comment]
#756 added a workaroud to fix httptools bug in 0.0.9. It is fixed in 0.0.10. So we can pin the httptools version `>=0.0.10` and remove the workaround for the bug.

To fix the issue:
- sanic shouldn't allow httptools < 0.0.10
- remove fragmanted header workaround which is added in #756 - because it is duplicated code and responsibility.

**Comment by ashleysommer** [comment]
@youknowone I see you've made this commit to your own fork: https://github.com/youknowone/sanic/commit/98a6933ce623f04a744a4635a079d1cca6a6ea17
If we pin httptools to >= 0.0.10 then can be just use that same commit patch?

**Comment by vltr** [comment]
@ashleysommer his fork is just a "reversion" of PR #756, which I think it's quite doable in Sanic if we just pin `httptools` :wink:

**Comment by youknowone** [comment]
@ashleysommer I doubt it. I used that fix to test whether I fixed httptools correctly or not. I think more change is possible than that one.
