### ISSUE TITLE
Handling redployments

### ISSUE THREAD

**Issue by tomchristie** [huge-success/sanic#107]
Hiya,

One thing that's not clear to me from the documentation is how users should be expected to handle app redeployments (without dropping existing connections). Presumably you'd need to bring up the new servers on a different port, switch the load balancer, and then (gracefully) stop the existing server.
- Does sanic handle graceful redeployment without dropping connections?
- Have I misunderstood how app redeployment should be handled with sanic?
- Would this be worth documenting in the deployment section.

(Also related to https://github.com/channelcat/sanic/issues/61 since graceful reloads are one of the benefits of running an application framework underneath a server such as gunicorn.)

**Comment by channelcat** [comment]
Hmm, Sanic is set up to properly drain connections on close, but does not support reloading, so you would have to do what you outlined.  Looking at Gunicorn, it looks like it creates an arbiter before loading any application code.  To create workers, the arbiter forks the process first, then initializes the workers to allow graceful reloading.  Pretty neat.

We should be able to support that paradigm by shifting to running apps with `python -m sanic file.app` (currently supported) when using multiple workers.  I think I'd like to add this, but I'm not sure when I will be able to get to it, so I'm tagging in case someone else wants to pick it up first.
