### ISSUE TITLE
how to enforce TLSv1.2

### ISSUE THREAD

**Issue by choobinejad** [huge-success/sanic#1070]
When starting a Sanic server with SSL, is there a way to enforce a specific version? Specifically, TLS v1.2?

**Comment by r0fls** [comment]
You should be able to force TLS v1.2 with the standard sanic SSL configuration from [here](http://sanic.readthedocs.io/en/latest/sanic/ssl.html?highlight=ssl), plus the `set_ciphers` [method](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_ciphers).

For example:

```python
import ssl
context = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH)
context.set_ciphers('TLSv1.2')
context.load_cert_chain("/path/to/cert", keyfile="/path/to/keyfile")

app.run(host="0.0.0.0", port=8443, ssl=context)
```

**Comment by choobinejad** [comment]
Good to go! Thanks @r0fls. Agree that `context.set_cipher()` might be a useful add to the docs.
