### ISSUE TITLE
request.uri_template returns None

### ISSUE THREAD

**Issue by poerwiyanto** [huge-success/sanic#1115]
Hi,

I am trying to get request.uri_template from request middleware, but I always get None. How can I get request.uri_template from request middleware? Thanks.

**Comment by arnulfojr** [comment]
Hmmm.. well as far as I'm concerned the request middleware(s) are executed before the app fetches the request route from the Router and therefore setting the `uri_template` in the request object only after the request middleware is executed. This of course will have the request's uri_template as None during the request middleware.
Which makes sense as the request middleware is only concerned about the request, but if I may ask what's your use case?
