### ISSUE TITLE
Wildcard route support

### ISSUE THREAD

**Issue by chauffer** [huge-success/sanic#1126]
I couldn't find anything regarding wildcard route support (e.g.: https://github.com/bottlepy/bottle/issues/178) - Is this supported/planned?

**Comment by ashleysommer** [comment]
No it is not supported, and not planned. The sanic router is designed to operate a fast as possible. Adding wildcard support is one of those features that sounds cool to have, but would likely significantly impact the performance of the router.

If you (or someone else) could come up with a reference wildcards matching implementation that does not slow down the performance of the Sanic router for common use-cases, then it will certainly be considered for inclusion.

**Comment by episodeyang** [comment]
Then, is there a catch-all route?

**Comment by episodeyang** [comment]
Here it is!! #1223 

@app.route('/<path:path>')

**Comment by episodeyang** [comment]
I'm running into this problem: when I do `GET localhost:3002/profiles`, I thought the async handler is supposed to catch this via the `/<path:path>` route, with `path="profiles"`. However the server errors out with "file not found", apparently from the static handler.

```python
import os
from sanic import Sanic
from sanic.response import file

# gets current directory
BASE = os.path.realpath(__file__)
print(BASE)
print(os.path.dirname(BASE))

build_path = os.path.join(os.path.dirname(BASE), "../app-build")
print(build_path)

app = Sanic()
# serve js file for webpack
app.static('/', build_path)


# app.static('/main.js', './app-build/main.js', name='main.js')

@app.route('/')
@app.route('/<path:path>')
async def index(request, path=""):
    print('hey ====', [path])
    return await file(build_path + '/index.html')


if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=int(os.environ.get('PORT', 3002)),
        workers=int(os.environ.get('WEB_CONCURRENCY', 1)),
        debug=bool(os.environ.get('DEBUG', '')))
```
