### ISSUE TITLE
Catch SIGTERM at the route level

### ISSUE THREAD

**Issue by youcandanch** [huge-success/sanic#1128]
So, this may be purely a documentation issue, but I'm struggling to do this and figured I'd reach out.

I have an endpoint like this:

```python
@app.websocket('/reading-session')
async def websocket_handler(request, ws):
    received_messages = []
    try:
        while True:
            message = await ws.recv()
            parsed_message = verify_and_parse_payload_data_or_None(message)
            if parsed_message:
                received_messages.append(parsed_message)
    except websockets.exceptions.ConnectionClosed:
        await persist_messages_to_db(received_messages)
```

Roughly what I'm trying to accomplish is capturing a user event stream for the duration of their connection, and then once the connection closes, we persist that information to a data store. This works reasonably well, unless the Sanic service receives a term or kill signal; when that happens, we don't receive a ConnectionClosed exception, and therefore the data that's stored in memory is lost. 

With that in mind, is there a way to catch these termination signals at the route level? Is there a better pattern I should be following? Thanks in advance.

**Comment by ashleysommer** [comment]
This is a great question.
At the moment I believe there is no way to do what you are describing.
You can register an "on_before_close" listener, in which you set up a handler to close any currently open websockets, but I don't know if its possible to access and close the websockets from the handler.

Looking at the internal server signal handling code, it _might_ be possible to add it the functionality, I will play around with the code later tonight.

Just FYI, it is _not_ at all possible to catch a SIGKILL. The SIGKILL is a kernel signal, it is not sent to a process, but rather it is an instruction sent to the kernel to forcefully end a process. There is no way for a process to listen for and/or intercept a SIGKILL signal.

**Comment by antinescience** [comment]
Makes sense. Thanks @ashleysommer!

**Comment by seemethere** [comment]
Thanks @ashleysommer!

**Comment by antinescience** [comment]
(for what it's worth I can do _something_ resembling this by also catching `CancelledError` but boy oh boy does that also catch a whole lot of other garbage, haha)

**Comment by antinescience** [comment]
Wait, @seemethere, why the close? Seems like there's research possible here that could bring this to a PR?

**Comment by seemethere** [comment]
Oh I thought your question had been answered. I'll reopen.

**Comment by antinescience** [comment]
Thanks! If it turns out there's no way to do it, that's fine, but if there's some direction I can be pointed in I'd be happy to try to take a stab at it. I just don't know the internals well enough at this point to do it on my own yet 😬

**Comment by sjsadowski** [comment]
This issue seems to have stagnated. Closing.
