### ISSUE TITLE
Route reverse lookup

### ISSUE THREAD

**Issue by ahopkins** [huge-success/sanic#1132]
Is there some way already in Sanic to do a reverse lookup on a `Route` object? Inside of a [decorator](http://sanic.readthedocs.io/en/latest/sanic/decorators.html#handler-decorators), I am trying to get access to either the `Route` or (even better) the `Blueprint`.

I know that on the `request` object I can get to the `Router` and `routes_all`. But what would be the best way to determine the route and/or blueprint instance using the `request` object?

Assuming there is not currently one, what about extending the `request` object, and the `route`?

```python
request.route
>>> Route(
    handler=<function hello_world at ...>,
    methods=frozenset({'GET'}),
    pattern=re.compile('^/test/$'),
    parameters=[],
    name='Test.hello_world',
    uri='/test/',
    blueprint=<sanic.blueprints.Blueprint object at ...>
)
```

See `request.route` and `Route.blueprint`

**Comment by ahopkins** [comment]
@ashleysommer Thanks. I was thinking I might need to go that route, but was not sure.

I would be happy to work on something if it sounds like it might be a helpful feature for anyone else.

**Comment by sjsadowski** [comment]
@ahopkins do you want to leave this open?

**Comment by ahopkins** [comment]
@sjsadowski There's no need for further discussion here on this....

But, I do think this is a reference that we should have when we get to redoing the router. I am fine with closing it, but I think if we are keeping a list of items that need to be addressed on the new router, this should be one.
