### ISSUE TITLE
ImportWarning & DeprecationWarning using builtin aiohttp client for tests

### ISSUE THREAD

**Issue by Julien00859** [huge-success/sanic#1133]
I have both `ImportWarning` and `DeprecationWarning` when I use the built in aiohttp test client with unittest.

Code:
```python
import unittest
import sanic
app = sanic.Sanic()
class Test(unittest.TestCase):
    def test(self):
        _, res = app.test_client.get("/")
        self.assertEqual(res.status, 404)
unittest.main()
```

Warnings:

	venv/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
	  return f(*args, **kwds)
	venv/lib/python3.6/site-packages/sanic/testing.py:24: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
	  conn = aiohttp.TCPConnector(verify_ssl=False)

**Comment by yunstanford** [comment]
i guess you are using newer version of aiohttp, as `verify_ssl` is deprecated after `v2.3`. However, it supposed to use a very old version of aiohttp https://github.com/channelcat/sanic/blob/master/tox.ini#L16. I can take a look this later when i get some time.

**Comment by madisvain** [comment]
verify_ssl is deprecated after 2.3 as @yunstanford already said. I'm proposing the following patch - if everybody agrees on this I can make a pull request so this warning wold go away.
```python
if aiohttp.__version__.startswith("2."):
    conn = aiohttp.TCPConnector(verify_ssl=False)
else:
    conn = aiohttp.TCPConnector(ssl=False)
```

Maybe there is a better way of checking versions without importing distutils and using version parsing from there.

The other option would be to increase the aiohttp required version to minimum 3 and then we don't have to build this version checking at all.

**Comment by whyboris** [comment]
I can confirm the warning I see when running _pytest_ in my project goes away when `verify_ssl=False` is changed to `ssl=False` (changing this line: https://github.com/huge-success/sanic/blob/9092ee9f0e65d38a65ac1d506af65d06e5f86652/sanic/testing.py#L26 on my machine.)

**Comment by ahopkins** [comment]
There is PR #1155. This seems like such a small little change that we ought to make.

The bigger question, however, is about testing in general and whether the testing client itself should be moved to its own repo to be able to trim down the requirements.

**Comment by ralston3** [comment]
> There is PR #1155. This seems like such a small little change that we ought to make.
> 
> The bigger question, however, is about testing in general and whether the testing client itself should be moved to its own repo to be able to trim down the requirements.

Came here as I was similarly getting this error with latest sanic/aiohttp. I'm not a contributor, but I'd agree with the idea of keeping the repo lean (a lot of folks actually build their own testing for http apis anyway), so it would be a nice way to say "Well if you need it, go add this testing requirement package"

**Comment by ahopkins** [comment]
@ralston3 we'd welcome your contributions, and if not, we welcome your opinions!
