### ISSUE TITLE
Static files handling makes a mistake when deal with "Range: bytes=0-" headers.

### ISSUE THREAD

**Issue by ryanrain2016** [huge-success/sanic#1139]
I use the code below to deal with static files with  request with "Range: 0-" headers.
```python
@app.route("/media/<filename>")
async def static(request, filename):
    filename = os.path.join('media',  filename)
    stats = await stat(filename)
    _range = None
    try:
        _range = ContentRangeHandler(request, stats)
    except HeaderNotFound:
        pass
    else:
        # _range.end -= 1
    resp = await sanic.response.file_stream(filename, _range=_range)
    # if _range: resp.status=206
    return resp
```
But unfortunately, it doesn't work as expected.
Assume the file size is 1024 bytes.  
Firstly, the `_range`  returned by `ContentRangeHandler` in the code produces a header 'Range: bytes 0-1024/1024', which exactly should be 'Range: bytes 0-1023/1024'. I should add `_range.end -= 1` to fix it.When dealing with video files, this mistake will make video on browsers un-seekable.
Secondly, If `_range`  is not None, the `file_stream` returns a `StreamingHTTPResponse` with a status 200. I should change is to 206 by myself , which is annoying.

**Comment by sjsadowski** [comment]
@ryanrain2016 would you be willing to submit a PR to fix this?

**Comment by ryanrain2016** [comment]
@sjsadowski  
It's my pleasure.

**Comment by ryanrain2016** [comment]
@sjsadowski 
I try to fix it. But it doesn't pass the test.
The test case assert response.status equals to 206, no matter whether range is None.
The test case `test_static_content_range_correct`  in test_url_for_static.py and test_static.py assert 
'Range': 'bytes=12-19'   should not contains the end `content[19]`, which is not correct.
Can I modify the test case?

**Comment by sjsadowski** [comment]
Yes, if the test is incorrect, please correct it. When you submit your PR, someone will review and make sure it's a valid change.

**Comment by sjsadowski** [comment]
Close per #1402
