### ISSUE TITLE
How do I add a custom log instead of syslog and track all the access log and error logs in 2 separate files without explicitly using try catch

### ISSUE THREAD

**Issue by jibinmathew69** [huge-success/sanic#1161]
How do I add a custom log instead of syslog and track all the access log and error logs in 2 separate files without explicitly using try catch, essentially logging the console output of sanic in 2 separate files.

**Comment by jibinmathew691993** [comment]
I found out the solution
https://stackoverflow.com/questions/49270646/how-to-change-the-default-sanic-log-directory-to-a-custom-directory
