### ISSUE TITLE
`url_for` filename can not be ignored.

### ISSUE THREAD

**Issue by LynnShaw** [huge-success/sanic#1171]
[build-url-for-static-files](http://sanic.readthedocs.io/en/latest/sanic/routing.html#build-url-for-static-files) says `filename` can be ignored, however, it can't works with error `AttributeError: 'NoneType' object has no attribute 'startswith'`

![q](https://user-images.githubusercontent.com/11351097/37816722-120f27ae-2eaf-11e8-8104-0052092451f9.png)

**Comment by r0fls** [comment]
Can you please show a minimal example to reproduce this?

**Comment by LynnShaw** [comment]
@r0fls I have added a picture to show the example

**Comment by gabrii** [comment]
+1
