### ISSUE TITLE
Running with gunicorn, not able to get the instrumentation metrics

### ISSUE THREAD

**Issue by darxtrix** [huge-success/sanic#1178]
Hi,

I wanted to run our first sanic powered application in production, but am not able to get the gunicorn metrics out to statsd.

```shell
# with old worker
$ gunicorn --name <name> app:app  --bind 0.0.0.0:1337 --worker-class  sanic_gunicorn.Worker  -w 2  --statsd-host=localhost:8125 

# with new worker
$ gunicorn --name <name>  app:app --bind 0.0.0.0:1337 --worker-class sanic.worker.GunicornWorker -w 2  --statsd-host=localhost:8125 
```

I have tested with the basic hello world gunicorn and i am getting all the instrumentation parameters of gunicorn over the UDP port. Is there a work around for this ?

Is it because of the async behavior of sanic, what other approaches we can take to performance metrics of sanic ?

**Comment by pyk** [comment]
>  what other approaches we can take to performance metrics of sanic ?

Here is an example to track the request rate on Sanic-based apps using [Promtheus](http://prometheus.io) as the metrics data storage and [Grafana](https://grafana.com) as the dashboard.

```python
#app.py
from sanic import Sanic
from sanic import response
import prometheus_client as prometheus
from prometheus_client import exposition

app = Sanic()

# pylint: disable=E1120
srt = prometheus.Counter("sanic_requests_total",
                         "Track the total number of requests",
                         ["method", "endpoint"])


@app.get("/")
async def index(request):
    # pylint: disable=E1101
    srt.labels(method=request.method, endpoint=request.path).inc()
    return response.json("hello")

@app.get("/metrics")
async def metrics(request):
    output = exposition.generate_latest().decode("utf-8")
    return response.text(body=output,
                         content_type=exposition.CONTENT_TYPE_LATEST)

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080)

```

Add the following config to the prometheus yaml file:

```
- job_name: sampleapp
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:8080
```

And use the following query for the grafana dashboard.

```
rate(sanic_requests_total{job="sampleapp"}[5m])
```

Example result for the grafana dashboard using dummy requests and endpoints:

<img width="1375" alt="screen shot 2018-04-01 at 21 51 21" src="https://user-images.githubusercontent.com/2213646/38174412-ed3c9764-35f6-11e8-8744-04457b19b2fb.png">
