### ISSUE TITLE
python Kafka producer does not work with multi worker python framework like sanic and japronto

### ISSUE THREAD

**Issue by souravroy0708** [huge-success/sanic#1185]
I am implementing python sanic web framework to produce message in kafka topic.So when I am using worker more than one in my application then kafka produce not able to produce message but when i am using worker as 1 then kafka client able to produce the message.

So is there any way to work kafka producer with python multiprocessing.After running python app.py I am able to that it is running in multiple processes.

501 14712 14709 0 7:56AM ttys002 0:00.03 python app.py
501 14713 14709 0 7:56AM ttys002 0:00.03 python app.py

Sanic reference - http://sanic.readthedocs.io/en/latest/sanic/deploying.html#workers

**Comment by r0fls** [comment]
Hi, can you show a more complete example of how you’re using the Kafka client, to reproduce this? Is it logging any errors anywhere?

**Comment by sjsadowski** [comment]
Does this work with a single worker?

**Comment by sjsadowski** [comment]
Closing - requester did not respond.

**Comment by souravroy0708** [comment]
> Does this work with a single worker?

Yes

**Comment by souravroy0708** [comment]
> Closing - requester did not respond.
