### ISSUE TITLE
How to set the exception handler for app.websocket

### ISSUE THREAD

**Issue by zzeric** [huge-success/sanic#1191]
ErrorHandler can not handle the websocket exceptions

**Comment by sjsadowski** [comment]
Sorry for the 9 month delay: ErrorHandler is used for http requests not ws requests; you'll need to manage the exceptions for websockets yourself. The list of exceptions provided by websockets is available here https://websockets.readthedocs.io/en/stable/api.html (need to scroll down to Exceptions section)
