### ISSUE TITLE
Ability to send Content-Length header when streaming large files

### ISSUE THREAD

**Issue by simonw** [huge-success/sanic#1194]
I'm using the `response.file_stream(...)` function to serve a large (often 100MB-ish) file for download, and I noticed that I'm not getting a `Content-Length` header even if I manually include one in the call to that function.

Without a Content-Length header, tools like `wget` and `curl` or browser download interfaces are unable to show my user's a progress bar indicating how long the file will take to download.

My code looks like this:

        return await response.file_stream(
            location=filepath,
            headers={
                'Content-Length': os.path.getsize(filepath),
            },
            filename=os.path.basename(filepath),
            mime_type='application/octet-stream''
        )

It looks like the `Content-Length` header I calculated is being removed here:

https://github.com/channelcat/sanic/blob/8b920d9d5683467b89fda2bd463656b1846a9059/sanic/response.py#L148-L157

I'd like to be able to include this header when I serve large files.

**Comment by yunstanford** [comment]
It should not include both `chunked` and `Content-Length`
