### ISSUE TITLE
Egg Info Failed when installing Sanic on Windows

### ISSUE THREAD

**Issue by ryankempster** [huge-success/sanic#1198]
Trying to install Sanic on Windows through a requirements.txt file and getting the following error

Python version 3.6
Pip version 9.0.1
Sanic version 0.7.0
setuptools version 39.0.1

Collecting sanic==0.7.0
  Downloading https://files.pythonhosted.org/packages/9c/9a/76fa35936aa51d27f293fc724af62dc7ce84280a6940b50dcb63ba5a7c06/sanic-0.7.0-py3-none-any.whl (48kB)
Collecting aiofiles>=0.3.0 (from sanic==0.7.0)
  Downloading https://files.pythonhosted.org/packages/0b/39/bb20653b60bab6ba036f13f7eae91a232b63394d4a04ae08efd45f434222/aiofiles-0.3.2-py3-none-any.whl
Collecting uvloop>=0.5.3 (from sanic==0.7.0)
  Downloading https://files.pythonhosted.org/packages/f3/e0/05c5c2a879b3ee8427a43ca2abd34cffc172e2cb5c45217d67e06b36a48e/uvloop-0.9.1.tar.gz (1.8MB)
    Complete output from command python setup.py egg_info:
 
Command "python setup.py egg_info" failed with error code 1

**Comment by ryankempster** [comment]
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pycharm-packaging\httptools\

However that pycharm-packaging folder does not exist.

**Comment by nhydock** [comment]
it's mentioned in the readme for Sanic that uvloop has no wheels for windows.  If you want to run it on windows 10, try using python in a linux subsystem instead

**Comment by Atagait** [comment]
Failing using the linux subsystem, You can also download the repository and manually edit `setup.y` so that it installs without uvloop and ujson

**Comment by sjsadowski** [comment]
This should be fixed in 0.8.x with the removal of non-windows compatible dependencies on windows.
