### ISSUE TITLE
How to run a task in a multiple worker.

### ISSUE THREAD

**Issue by Mdslino** [huge-success/sanic#1201]
I'm facing a problem. I have a task set that make a call to a mainframe, but my sanic server is running multiple workers and the task starts its run in every worker at the same time. How can i prevent that? Is there a way to make a task run in a sigle worker even if sanic is running in a multiple worker scenario?

**Comment by scottwernervt** [comment]
Another option is https://arq-docs.helpmanual.io/ which I found very easy to get started with vs celery.

**Comment by Mdslino** [comment]
@SirEdvin @scottwernervt what i trying to accomplish is use the sanic add_task feature. When i do that and set multiple worker in app.run(workers=4) the task runs simultaneous in every task. Its two features that can't work together. I cant let the same database transaction run N times at the same time or a calculation, whats the point in having a built-in task function (whats is awesome by the way) and don't work well with multiple workers? The alternatives I already know I'm here to discuss the solution with pure Sanic.

**Comment by skytoup** [comment]
If gunicorn is used to replace sanic's multi-worker, can it work normally?

**Comment by SirEdvin** [comment]
@skytoup You should sync task and provide distributed locks in both cases.
