### ISSUE TITLE
Sentry support built into Raven

### ISSUE THREAD

**Issue by madisvain** [huge-success/sanic#1212]
Raven the client for Sentry has added support for Sanic:
https://github.com/getsentry/raven-python/blob/master/raven/contrib/sanic.py

The documentation is not present but the code is and works as intended. Sanic documentation should be updated to direct people to the correct implementation.

I will try to help myself with this also.

**Comment by sjsadowski** [comment]
I closed this because I don't believe that it's sanic that should update their docs to point at the external projects, it should be the other way around.
