### ISSUE TITLE
Exception: "data received after completed connection: close message"

### ISSUE THREAD

**Issue by pyk** [huge-success/sanic#1215]
Hey guys, we use Sanic and we got the following exception in our error reporting:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 220, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserError: data received after completed connection: close message
```

I cannot reproduce the error because the HTTP Request is empty:
<img width="798" alt="screen shot 2018-05-08 at 07 36 45" src="https://user-images.githubusercontent.com/2213646/39731596-aa943e04-5292-11e8-83c0-88eb8a2df6f1.png">

it seems that the exception is raised before `response` middleware (where our custom access log exists to record HTTP request such as latency etc)  is executed.

Do you have any idea why this is happen and how to reproduce this exception? 

thanks guys

**Comment by sjsadowski** [comment]
@pyk can you provide us a stripped down example of the code where your issue occurs?

**Comment by sjsadowski** [comment]
Closing - requester did not respond.
