### ISSUE TITLE
Sanic getting hanged when im running with worker >1

### ISSUE THREAD

**Issue by spawn08** [huge-success/sanic#1216]
Hey guys I have three end points `"/"`, `"/train"`, and `"/classify"`.  When I specify the worker > 1, in my case it is 4 (`app.run(host...,port...,worker=4`)). My `"/"` route is working fine but as soon as I go to route `"/train"` and `"/classify"`, sanic is getting blocked. There is no response.

```
@app.route('/api/train')
async def train(request):
    train_network_sanic.train()
    return response.text("training successfull")


@app.route('/api/classify')
async def classify(request):
    sentence = request.args.get('query')
    return_list = train_network_sanic.classify(sentence)
    return response.text(str(return_list))
```

This is what my code looks like for route `"/train"` and `"/classify"`. can anybody help?

**Comment by bunyk** [comment]
I would say that it blocks in ` train_network_sanic` methods. Could you remove them and try again?

**Comment by yunstanford** [comment]
closing this since no more feedbacks. feel free to reopen if needed.
