### ISSUE TITLE
How to use concurrent.futures.ProcessPoolExecutor from within a Sanic webapp

### ISSUE THREAD

**Issue by soumyadipdm** [huge-success/sanic#1224]
I am doing something like this:
```python
import sanic
import asyncio
import concurrent.futures

app = sanic.Sanic()

def compute_heavy_sync_function(multiplier):
    result = 0
    for i in range(multiplier):
        result += 2 ** i
    return {"result": result}

@app.route("/some/route/<arg>")
async def handle_route(request, arg):
    payload = request.json
    loop = asyncio.get_event_loop()
    with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
       data = await loop.run_in_executor(executor, compute_heavy_sync_function, payload["data"])

    return sanic.response.json(data)

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8090, workers=12)
```

When I run this, I get an exception in Sanic worker

```
May 18 07:12:02 xyz server[26009]: data = await loop.run_in_executor(executor, compute_heavy_sync_function, payload["data"])
May 18 07:12:02 xyz server[26009]: File "uvloop/loop.pyx", line 2318, in uvloop.loop.Loop.run_in_executor
May 18 07:12:02 xyz server[26009]: File "/venvs/python/3.6/lib/python3.6/concurrent/futures/process.py", line 454, in submit
May 18 07:12:02 xyz server[26009]: self._start_queue_management_thread()
May 18 07:12:02 xyz server[26009]: File "/venvs/python/3.6/lib/python3.6/concurrent/futures/process.py", line 415, in _start_queue_management_thread
May 18 07:12:02 xyz server[26009]: self._adjust_process_count()
May 18 07:12:02 xyz server[26009]: File "/venvs/python/3.6/lib/python3.6/concurrent/futures/process.py", line 434, in _adjust_process_count
May 18 07:12:02 xyz server[26009]: p.start()
May 18 07:12:02 xyz server[26009]: File "/venvs/python/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
May 18 07:12:02 xyz server[26009]: 'daemonic processes are not allowed to have children'
May 18 07:12:02 xyz server[26009]: AssertionError: daemonic processes are not allowed to have children
```
I see [process.daemon = True](https://github.com/channelcat/sanic/blob/202a4c6525cc47fb55a35be136a9b928011b78cc/sanic/server.py#L715) is set while spinning up the workers.

So what's the right way to run a ProcessPoolExecutor inside a Sanic app?

I would love if there was a way to use custom `serve_multiple` function for the workers.

**Comment by yunstanford** [comment]
Did you try gunicorn ? or try `ThreadPoolExecutor` ?

**Comment by soumyadipdm** [comment]
I am using NGINX to proxy the app (among other things like terminate SSL and header injection). I don't see myself using `gunicorn`. Tried `ThreadPoolExecutor` but since the function (function in the example is a mock one, the original one revolves around calculating and comparing hash digests) is CPU heavy, so it was of not much helpful.

So other than running 12 Sanic servers (as opposed running 1 Sanic server with 12 workers), there's no way to use `ProcessPoolExecutor`?

**Comment by yunstanford** [comment]
https://github.com/channelcat/sanic/blob/master/sanic/server.py#L715 multiworker mode sets the process to daemon.

You can still ngnix with gunicorn.

**Comment by soumyadipdm** [comment]
But NGINX Unit does not support SSL, isn't it? So I have to bring in NGINX in front of Unit for SSL termination. Gunicorn or NGINX Unit + NGINX seems to be the way forward to solve it.

I think if this can be documented somewhere pointing out that `ProcessPoolExecutor` from within Sanic workers as workers are forked using `multiprocessing.Process` with `daemon = True` to make the workers well behaved. And in order to use `ProcessPoolExecutor`, we have to use a set up similar to the one mentioned above.

Happy to open a PR if someone points me to the right doc where it can be mentioned.
