### ISSUE TITLE
Does the sanic have the maximum number of connections

### ISSUE THREAD

**Issue by Gitforxuyang** [huge-success/sanic#1226]
Hello, I found that when the connection number reached 1000, I couldn't connect to it. Is there a maximum number of connections for sanic? If so, where is the maximum connection limit set?

**Comment by Gitforxuyang** [comment]
Can anyone answer this question

**Comment by yunstanford** [comment]
`gunicorn` limits max_clients to 1000 by default, not sure if you're using gunicorn. http://docs.gunicorn.org/en/stable/settings.html#worker-connections

**Comment by yunstanford** [comment]
how do you start your service ? did you set backlog ?

**Comment by Gitforxuyang** [comment]
@yunstanford   Hello, this is my configuration

app.run(host=HOST, port=PORT, access_log=False)

**Comment by Gitforxuyang** [comment]
@yunstanford  Are you still there?

**Comment by Gitforxuyang** [comment]
@yunstanford 
I tried to input 10000, but I did not see any change through the test. Do you know what backlog is set up for?

**Comment by yunstanford** [comment]
https://docs.python.org/3/library/asyncio-eventloop.html#creating-listening-connections

curious how do you test it ?

**Comment by Gitforxuyang** [comment]
@yunstanford 
After I set up backlog to 10000。
I use node's connection pool to create 1200 socket connections, and when I create 1000 or so, the subsequent connection will be closed by the server.

**Comment by Gitforxuyang** [comment]
@yunstanford 

Hello, I seem to have found a problem. We use sanic to default only to receive 1000 requests, today we switch to `Gunicorn` to start the program, and set the `worker_connections` to 2048, and the acceptable number of connections is raised to 2000.

I have a question. Does sanic have the default maximum 1000 connection settings? And does not allow developers to modify it? It's not reasonable to think about it.

**Comment by yunstanford** [comment]
If I understand your question correctly, 

no, it doesn't, you can configure maximum queued connections by setting backlog. 

Also the worker_connection setting only affects the Eventlet and Gevent worker types if I recall correctly.

**Comment by Gitforxuyang** [comment]
@yunstanford 
All right, that's really confusing. Because I had a backlog of 10000/1000 yesterday, I could only accept as many as 1000+ socket connections. I took packet analysis from wireshark and found that when the number of connections reaches more than 1000, when a new socket is established, the server will send a fin signal to the client to close the socket.
Is this a bug?

**Comment by yunstanford** [comment]
Backlog is for queueing unaccepted connections

**Comment by Gitforxuyang** [comment]
@yunstanford 
Well, I'm working on it for the time being. Follow up with time

Thank you for answering me
