### ISSUE TITLE
How to custom websocket event in view function ?

### ISSUE THREAD

**Issue by cundi** [huge-success/sanic#1227]
I don't find any answers in the official docs, so how can I do about this scenario

**Comment by sjsadowski** [comment]
Can you describe what you're trying to accomplish with some pseudocode?

**Comment by cundi** [comment]
> Can you describe what you're trying to accomplish with some pseudocode?

the event which I want to custom just like tornado websocket events , let's say `on_message` , `on_close`, etc.

**Comment by sjsadowski** [comment]
I'm doing some clean-up and just came back to this - I think what you really need is info on the underlying information about how websockets is handled within sanic, and we use the websockets package to do the lifting there: https://websockets.readthedocs.io/en/stable/intro.html

**Comment by hyansuper** [comment]
I think this is what you want https://python-socketio.readthedocs.io/en/latest/server.html#sanic
I don't know how to do the `on_event` handling with sanic's default websocket module, websockets seems to be unable to do that?
