### ISSUE TITLE
Would Sanic borrow code from other projects like Japronto?

### ISSUE THREAD

**Issue by btegs** [huge-success/sanic#1228]
Sanic is fast and I love it. People also seem to be curious about [Japronto](https://github.com/squeaky-pl/japronto), which people are claiming to be the fastest Python web framework in existence.

Unfortunately, development on Japronto has pretty much stopped. Would Sanic in the future consider merging in or at least reference code in Japronto to improve speeds of Sanic? It would be a shame to see Japronto get eventually abandoned with all that optimized code.

**Comment by meckin** [comment]
Generally, I'm unclear how they would "merge". Is there something in Japronto that would be useful?

**Comment by xen** [comment]
Japronto looks good on tests but in reality, doesn't have performance advantages over aiohttp.web and Sanic. It postpones headers parsing to be great on pictures. But when you add things like database queries, sessions stored in redis, etc you will get the same performance. In the end, you will get the same Python performance. Sorry to say, but there is no magic Santa Claus with gifts under the tree.

**Comment by GMLudo** [comment]
Maybe something to take from this project: https://github.com/vibora-io/vibora ?

**Comment by sjsadowski** [comment]
I think the answer is "yes" if it meets a need. I think for now, it would need to come in the form of a pull request in response to an issue.
