### ISSUE TITLE
Websocket 5.0 incompatible change, removes after_handshake=True from close_connection

### ISSUE THREAD

**Issue by garyo** [huge-success/sanic#1237]
In websockets 5.0, apparently the socket.close_connection() method no longer accepts `after_handshake=True` as a keyword arg. If that code gets run, it gives an unexpected keyword error. I actually noticed this bug in pytest-sanic, see https://github.com/yunstanford/pytest-sanic/issues/17, but sanic has the same code in https://github.com/channelcat/sanic/blob/202a4c6525cc47fb55a35be136a9b928011b78cc/sanic/server.py#L668 and https://github.com/channelcat/sanic/blob/202a4c6525cc47fb55a35be136a9b928011b78cc/sanic/worker.py#L119
IMHO, the fix is just to remove those args, or if you want more compatibility, try with the arg first, and catch the TypeError and try without it.
Sorry, I don't have a test case to repro this within Sanic at the moment.

**Comment by nhydock** [comment]
If anything, Sanic should have fixed versions set on its requirements.txt to avoid breaking due to API changes in dependencies

**Comment by sjsadowski** [comment]
Closing b/c #1239
