### ISSUE TITLE
Add github & slack integration to channelcat/sanic repo

### ISSUE THREAD

**Issue by smagafurov** [huge-success/sanic#1240]
Hello!

Is it possible to add "github & slack integration"(https://github.com/integrations/slack) app to channelcat/sanic repo?

Link to setup https://github.com/apps/slack/installations/new

**Comment by r0fls** [comment]
This would be more suitable for an extension, we wouldn't want to add that it to sanic core. What do you have in mind for an integration exactly?

**Comment by smagafurov** [comment]
No need to change sanic code at all.
This app adds ability to subscribe on changes in your repository.
https://slack.github.com/

**Comment by meckin** [comment]
>This app adds the ability to subscribe on changes in your repository.

I'm unsure on why this is something Sanic needs to provide to you. Seems like you could handle this in more than one way without this repo's having to add something to your use case.

**Comment by seemethere** [comment]
Neither me nor @r0fls have the ability to enable this. It'd require action from @channelcat

**Comment by meckin** [comment]
I'm unsure of the level of access one has to give away to make this functional, as it has to have some level of permission via his account level. Again, I have yet to look that up..

However, https://zapier.com/apps/github/integrations seems the ability without outside requirements. I believe you can make a trigger a repo you're watching.

**Comment by sjsadowski** [comment]
Since we don't run slack (we use gitter) and the slack integration itself doesn't appear to require access from us to notify on repo changes, the slack admin for whomever wanted to watch it would have to set it up.

I don't think this is really an issue for us.
