### ISSUE TITLE
New release on Pypi ?

### ISSUE THREAD

**Issue by ncrocfer** [huge-success/sanic#1245]
Hello,

I was looking for a tool to autoreload my code when I develop and I found this commit : https://github.com/channelcat/sanic/commit/52c2a8484e6aa5fa13aaade49e1f2597dd006e15

So it seems Sanic already integrates it since December 07, 2017. But the the latest version on Pypi dates from the day before (https://github.com/channelcat/sanic/commit/1ea3ab7fe8ab03a6ddf4d75a3de8cb719f4c584c) : https://pypi.org/project/Sanic/#history

Is-it possible to release a new version on Pypi please ? Other features (like the UUID support in routes) are also interesting :)

Thanks in advance !

**Comment by c-goosen** [comment]
pip install https://github.com/user/repo.git@branch

**Comment by ncrocfer** [comment]
@c-goosen Yes it's what we are doing now, but I still think `pip install sanic` is more convenient than `pip install https://github.com/channelcat/sanic.git@master` :pensive:

Six months without a new release on Pypi for an awesome project like **Sanic**... People who read blog posts on this framework will just try `pip install sanic`, not the full path including the branch.

**Comment by ashleysommer** [comment]
There is already another thread about requesting a new Sanic release, here:
https://github.com/channelcat/sanic/issues/1170

**Comment by c-goosen** [comment]
Well we should discuss integrating with circle CI or other tools with a scheduled release cycle.

**Comment by ashleysommer** [comment]
@c-goosen 
What is your reasoning behind that? How would a scheduled release cycle benefit the Sanic project?

**Comment by vlad1777d** [comment]
I think, it would be just enough to make new release )

**Comment by sjsadowski** [comment]
Guess I'll go ahead and +1 this, if only for the ipv6 support.

**Comment by sjsadowski** [comment]
@seemethere seems to be the one to tag and release, not sure if that also carries the responsibility to push to pypi.

**Comment by GoodiesHQ** [comment]
Personally, I don't like having to specially get the Sanic repo for support for something like nested Blueprints which has been a feature for a while now.
https://github.com/channelcat/sanic/commit/a10d7469cdeeaa4bdd94d508520e84255bdddb0b

**Comment by ajutras** [comment]
I'm having issues pushing for adoption of Sanic over Flask in my organisation at the moment mostly because of the lack of releases. The lack of a release cycle undermine the confidence in the product. 

I've read the few different issues opened about the lack of releases and I still cannot find a good reasoning as to why Sanic stopped doing releases. So what's up?

**Comment by sjsadowski** [comment]
@channelcat @seemethere Any ideas here?

**Comment by leotada** [comment]
@r0fls is one of the more active in 2018. Can you make a new release? If no one can make this, maybe we have to migrate for an organization in other repo. @yunstanford @seemethere

**Comment by r0fls** [comment]
I tried and I get this message 😢 :

```
HTTPError: 403 Client Error: The user 'r0fls' isn't allowed to upload to project 'Sanic'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

Seems pypi is hoping to fix this eventually: https://github.com/pypa/warehouse/issues/1506

In the meantime, only @seemethere can do a release. @seemethere any chance you want to change your pypi to a password that you can share with me so that I can do a release and calm the masses?

**Comment by ashleysommer** [comment]
@r0fls 
This small PR https://github.com/channelcat/sanic/issues/1285 will need to be merged before a release, because auto_reload is currently broken for all users except those on Mac OS.

**Comment by henry0312** [comment]
@r0fls you don't need to get the password. @seemethere will just add you to collaborators on PyPI :)

Example:
![image](https://user-images.githubusercontent.com/433434/44248166-f0a99200-a223-11e8-94df-12858b52e06d.png)

**Comment by ashleysommer** [comment]
Also would be good to get https://github.com/channelcat/sanic/pull/1179 and https://github.com/channelcat/sanic/pull/1278 merged before a release, but I don't want to set a precedent of everyone pleading to get their PRs merged before the release.

**Comment by yunstanford** [comment]
It'd be great if we have a team/official process for operating release.

I'd also like to see this https://github.com/channelcat/sanic/pull/1179 merged in so we could get feedbacks.

**Comment by ahopkins** [comment]
I'll be quite honest..... I've heavily adopted sanic in production, but did so in a way I could easily switchboard I need to. The lack of release schedule has me and my team worried and I've considered the effort to remove it. I already [took it out of my gateway service](
https://github.com/channelcat/sanic/issues/1264#issuecomment-413227303). 

Seeing this move to an organization would give the project a lot. Sanic's biggest weakness (in my opinion) right now is the lack of project direction. This could give some great momentum to an otherwise great framework.

**Comment by yunstanford** [comment]
@ahopkins agree, moving to an organization helps a lot.

**Comment by vltr** [comment]
I would be glad to help as well.

**Comment by sjsadowski** [comment]
I would also be willing to assist, if needed.

**Comment by seemethere** [comment]
Cutting a release today (@r0fls will handle the release notes), will contact @channelcat to see if we can move this to an organization so we can get more people who can help out with the project.

**Comment by seemethere** [comment]
Apparently @channelcat hasn't verified his email address on PyPI so I'm uploading to PyPI is currently broken, trying to see if there's a workaround.

**Comment by TheGrandmother** [comment]
I totally agree with @ahopkins. I really like Sanic but it seems like @channelcat haven't been that active in the project for a while (at least from what I can tell) and that kinda scares me.

**Comment by sjsadowski** [comment]
Has anyone tried to contact @channelcat directly via email to try and get these changes made? 

I hate to ask this but is it time for those of us who have availability and desire to do a community fork of this in order to make it sustainable and build some redundant leadership? I've been using sanic for some time now and I think a number of us on this thread want to be able to keep the project going and give back.

**Comment by TheGrandmother** [comment]
@sjsadowski I think forking should be a last alternative.

**Comment by vltr** [comment]
@sjsadowski I had this idea a million times and discussed with @ahopkins a million times as well, but we also agree with @TheGrandmother's opinion that forking should be the last alternative here. We all have the feeling that @channelcat looks abandoned, but yet this might not be true, so we have to wait a little bit more and see (and yes, this is rather frustrating, I can't deny that).

**Comment by ahopkins** [comment]
I agree that maybe now is not the time to fork. Sounds like @r0fls may be making some progress (hopefully). Hopefully we can get this loved to an organization. If not..... might I suggest pip install tailz 😂

**Comment by sjsadowski** [comment]
I don't disagree with @TheGrandmother, @vltr, or @ahopkins - but there is clearly a lot of concern about release cadence and PR management. The fact that this issue has been open for 2 months with @channelcat referenced multiple times and zero response. 

I'd rather keep pushing this project forward, personally, with increased community involvement to alleviate the pressures that come from the situation we're in now.

**Comment by seemethere** [comment]
We're looking into moving the project into an organization with a larger team of maintainers so changes are incoming but the current team has been extremely busy with other things. 

Sorry for the wait guys, this has been frustrating at both ends.

**Comment by c-goosen** [comment]
Need volunteers and maintainers to help? Think we can gain more from helping than criticising.

**Comment by c-goosen** [comment]
Also can we move some of the sanic-jwt/sanic-openapi etc under the same organization?

**Comment by ahopkins** [comment]
@c-goosen I can only speak for `sanic-jwt`. if there is enough interest from the community, I am not opposed to it. However, I currently intend to continue maintaining it as a third party package. I use it myself everyday at least you can feel comfortable that it is and will continue to be active so long as the `sanic` project is active. There are a decent group of contributors to the package, and you are welcome to join.

I am sure many of you would agree with me, one of the greatest strengths of `sanic` is the barebones nature of it, and that the framework does not force you to develop in one particular way. I strongly believe that options and flexibility in a framework are good. Therefore, my biggest hesitation in moving the project would be minimizing this.

**Comment by ahopkins** [comment]
Not saying it would change the nature of sanic per se.... Just that I know (for example) I am generally more inclined to use something from the same organization than not. I'm not so sure that sanic-jwt is or should be the "sanctioned" way of doing authentication. On the other hand.... I am happy to share the code, adopt new users, and if there is sufficient time interest, move it to an organization.

**Comment by yunstanford** [comment]
Any update or any plan ?

**Comment by ahopkins** [comment]
What about moving some of this discussion about the planning of *how* and *when* over to the [Gitter channel](https://gitter.im/sanic-python/Lobby). I mean ... its not like much else is going on over there.

**Comment by yunstanford** [comment]
i feel like issue pages have better visibility. Thoughts ?

**Comment by TheGrandmother** [comment]
Since the Gitter channel seems fairly stale, continuing the discussion on github might be prudent.

**Comment by TheGrandmother** [comment]
@ahopkins It's okay. The council of the elders of the internet forgives you ^-^

**Comment by dmitry-sobolev** [comment]
Any updates on this issue? Version 0.8.0 still not in PyPI :(

**Comment by ahopkins** [comment]
Hey everyone ... I started a mailing list to bring together a "task force" of like minded developers wanting to push this into a community backed organization. I urge everyone that has any inclination to help push Sanic forward into the future to join the conversation:

https://groups.google.com/forum/#!forum/sanic-dev

The goal is to continue this discussion with a set of specifics on how we can achieve this for the betterment of the Sanic community.

**Comment by abuckenheimer** [comment]
8,1 now available on pypi :fireworks:
