### ISSUE TITLE
serve on named pipe?

### ISSUE THREAD

**Issue by alexhsamuel** [huge-success/sanic#1251]
Has anyone gotten Sanic running on a POSIX named pipe instead of TCP socket?  I'm interested in running a service for private local use only, and a named pipe provides nice access control.

**Comment by sjsadowski** [comment]
This isn't currently supported, but it is useful.

**Comment by vltr** [comment]
@sjsadowski yeap. I don't believe it should be too difficult to implement, but it might change how the startup process (at least some extra params on `run`, in a vague thought here).

**Comment by alexhsamuel** [comment]
Hi!

For what it's worth, I no longer need this, so please don't implement it on my account.  But thanks for checking.

In any case, I've figured out since then (for other reasons) how to pass in the socket to `Sanic.run()`.  This might just work with an AF_UNIX socket?

**Comment by vltr** [comment]
@alexhsamuel would you mind sharing any piece of code regarding this case, for, at least, documenting reasons? Thanks a lot!

**Comment by alexhsamuel** [comment]
Sure.  [Here you go.](https://github.com/alexhsamuel/apsis/blob/e3052bfcf3fff6e9e30be5645eba021be9bd5413/python/apsis/agent/main.py#L187-L214)  My motivation here is that I need to choose a sever port  dynamically (as any given port might already be in use) and report it to the caller, before daemonizing and starting the Sanic app.

**Comment by vltr** [comment]
Great, thanks a lot @alexhsamuel !

**Comment by sjsadowski** [comment]
FWIW I've added a PR for documentation around using non-IPv4 sockets here: https://github.com/huge-success/sanic/pull/1375
