### ISSUE TITLE
request.form() lost many bytes of binary data

### ISSUE THREAD

**Issue by veelion** [huge-success/sanic#1253]
Hello,
I found a bug of request.form(), it call parse_qs() with default encoding="utf8", when there are binary data (such as image data) in request.body, it would lost some bytes, because some binary data sequence is not in UTF-8 order.

------------------ Reproducing the bug: ------------------------------
1. server code:
#!/usr/bin/env python3
from sanic import Sanic
from sanic import response

app = Sanic(__name__)
 
@app.route('/', methods=['POST'])
async def api_img(request):
    img_data = request.form.get('img_data', '') 
    print('img_data:', len(img_data))                                                                                                                                                                       
    img_data_binary = img_data.encode('utf8')
    print('get img_data : {}, img_data_binary: {}'.format(len(img_data), len(img_data_binary)))
 
    result = { 
        'img_data': len(img_data),
        'img_data_binary': len(img_data_binary),
    }   
    return response.json(result)
 
if __name__ == '__main__':
    app.run(host='127.0.0.1', port=7000)

2. Client code:
#!/usr/bin/env python

import requests
img_data = open('dog.jpg', 'rb').read()
post_data = {
    'img_data': img_data,
    'img_type': 'jpg',
}
url = 'http://127.0.0.1:7000/'
r = requests.post(url, data=post_data)
print('client send img_data:', len(img_data))
print('server got: ', r.text)

3. run server code and client code, client code will print the msg:
('client send img_data:', 150156)
('server got: ', u'{"img_data":142079,"img_data_binary":269713}')
that means, client sent a image of 150156 bytes, but server request.form() only got 142079 bytes, something lost!

--------------- How to fix it? ------------------
Just in function request.form() call parse_qs() with encoding="latin1"
change file sanic/request.py, line 130. change to:
`parse_qs(self.body.decode('utf-8'),` encoding='latin1'))

**Comment by sjsadowski** [comment]
Looks like @ashleysommer provided a reasonable solution in commentary to the PR.
