### ISSUE TITLE
[Feature Request] Support bool in route request parameter

### ISSUE THREAD

**Issue by csis0247** [huge-success/sanic#1282]
[Route request parameters](http://sanic.readthedocs.io/en/latest/sanic/routing.html#request-parameters) `<param:int>` and `<param:number>` work but `<param:bool>` doesn't ([Stackoverflow question](https://stackoverflow.com/a/51791291/2473022)) ([Sanic source code](https://github.com/channelcat/sanic/blob/212da1029e9a0ed786b5a1bfaf10183bfef9a790/sanic/router.py#L16)). Please add support to `bool` type.

Error message:
`Error: Requested URL /api/True not found`

Code:
`app.add_route(APIController().entry, '/api/<param:bool>)`

Version of Sanic is 0.7.0 with Python 3.6.5 in virtualenv.

**Comment by abuckenheimer** [comment]
whats your usecase here? I've never seen a url pattern like that and it seems like it be trivial to do this with the truthy-ness of an int instead

**Comment by abuckenheimer** [comment]
seems like #1013 has you covered anyway

**Comment by csis0247** [comment]
My use case is to include a flag to switch some API options on and off. I know I can parse a string or use an int, or even bitshift multiple flags inside an int, but that is beyond the point. A `bool` is a primitive type in many languages and should thus be supported by default.

**Comment by abuckenheimer** [comment]
My instinct is that there isn't enough best practice for encoding a bool into a url to really make a ruling on what that would look like from the sanic side of things. You mention `/api/True` but capital T true is just what python calls it where as I think most people are probably used to seeing something like `/api?url_kwarg=true` which then makes one ask what strings should signify a boolean True in sanic? The obvious answer is probably defer to json serialization but my gut is that should be handled on a case by case basis so I'm not sure if the framework should make a ruling. I don't have a particularly strong conviction either way though.

**Comment by abuckenheimer** [comment]
Also it sounds like your trying to use http GET requests to specific urls to set state which may explain some of your friction here. By using a POST method you could include True/False in the body instead of having to parse it in the url.

**Comment by ahopkins** [comment]
@vltrs is [creating a plugin called `sanic-boom`](https://github.com/vltr/sanic-boom) that I believe will support this:

https://github.com/vltr/sanic-boom/blob/master/tests/test_utils.py#L29

**Comment by vltr** [comment]
Thanks, @ahopkins !
@csis0247 yes, sometimes you do want a `yes` or `true` as a parameter and that's why I'm working in a plugin that would inject components and allow function parameter annotations as a "guide" to parse the captured value. It is very similar as parsing an `int`, `float`, `uuid`, you name it. I hope to have a working version soon :wink:

**Comment by vltr** [comment]
@csis0247 [continuing] unfortunatelly Sanic doesn't provide support for the `bool` type out of the box. You might take an example from the code and extend `REGEX_TYPES` to your taste:

```python
from sanic import Sanic
from sanic.response import text
from sanic.router import REGEX_TYPES


"""
# to generate the trie regex, uncomment the code bellow and install
# the triegex lib using pip

import triegex
t = triegex.Triegex(
    "yes",
    "Yes",
    "YES",
    "no",
    "No",
    "NO",
    "true",
    "True",
    "TRUE",
    "false",
    "False",
    "FALSE",
    "ok",
    "Ok",
    "OK",
    "accept",
    "Accept",
    "ACCEPT",
    "decline",
    "Decline",
    "DECLINE",
)
print(t.to_regex())
"""


def parse_bool(value):
    value = value.lower()
    return value in ("yes", "true", "ok", "accept")


bool_regexp = r"(A(?:CCEPT\b|ccept\b)|D(?:ECLINE\b|ecline\b)|F(?:ALSE\b|alse\b)|N(?:O\b|o\b)|O(?:K\b|k\b)|T(?:RUE\b|rue\b)|Y(?:ES\b|es\b)|accept\b|decline\b|false\b|no\b|ok\b|true\b|yes\b)"

REGEX_TYPES['bool'] = (parse_bool, bool_regexp)

app = Sanic(__name__)


@app.get("/license/<accept:bool>")
async def license(request, accept):
    assert type(accept) is bool
    if accept:
        return text("congratulations!")
    return text("well, we are sorry to hear that")


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

The result:

```
$ curl http://127.0.0.1:8000/license/True
congratulations!

$ curl http://127.0.0.1:8000/license/ok
congratulations!

$ curl http://127.0.0.1:8000/license/accept
congratulations!

$ curl http://127.0.0.1:8000/license/yes
congratulations!

$ curl http://127.0.0.1:8000/license/no
well, we are sorry to hear that

$ curl http://127.0.0.1:8000/license/false
well, we are sorry to hear that

$ curl http://127.0.0.1:8000/license/notarealanswer
Error: Requested URL /license/notarealanswer not found
```

I hope this helps :smiley:

**Comment by sjsadowski** [comment]
I think @vltr responded to this well and gives a solution without needing additional changes.
