### ISSUE TITLE
What to return for websocket requests?

### ISSUE THREAD

**Issue by garyo** [huge-success/sanic#1287]
Normal requests return a response object e.g. `response.text("hi there")`. What should a long-running websocket request return? The Sanic websocket samples return nothing, which might be OK except in the case of response_middleware that expects a response object from all requests (e.g. sanic-session). Is it OK to return a response object from a websocket request even though it will probably be thrown away (in `websocket.py:write_response`)?

**Comment by garyo** [comment]
Actually I think it doesn't matter what the app's websocket handler returns because that return value is ignored. Websocket handlers never return anything because app.py `websocket_handler` doesn't return anything: https://github.com/channelcat/sanic/blob/6abdf9f9c162140a4981c21361d334323ed47d65/sanic/app.py#L287
So this presumably means response middlewares should expect that response is None sometimes -- is that all correct?

**Comment by sjsadowski** [comment]
This might help; it really depends on what response you're expecting - but knowing what the possible responses are for a ws upgrade request could help you handle that better on the requesting side: https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism

**Comment by ahopkins** [comment]
Right, there is no need to return anything from that route. The websocket route needs to remain open as long as you want that connection to exist. From there, you interact with the interface via: `await ws.send(data)`.

Have you seen the documentation for `websockets` (the package that `sanic` uses under the hood: https://websockets.readthedocs.io/en/stable/intro.html

It is helpful to look through there for ideas and more complete examples.

**Comment by garyo** [comment]
OK to leave this closed, but I will point out the example response middleware in the doc doesn't protect against getting response=None. That's what led me here in the first place; my middleware was crashing when the websocket exited.

**Comment by sjsadowski** [comment]
@garyo I think that issue may be closer to an actual bug than your initial question. Would you like to open a new issue 'middleware crashes on websocket close' or something similar and provide what detail you can?
