### ISSUE TITLE
Can't Running via command in sanic version>0.7.0

### ISSUE THREAD

**Issue by RainJayTsai** [huge-success/sanic#1307]
when i used sanic==0.7.0 run sanic app via command it work fine
"$ python -m sanic app.app -host=0.0.0.0 --port=1337 --workers=4"

but when i update sanic to 0.8.0 or 0.8.1 and run app via command  it not working
raise a ImportError when call import_module method and show 

No module named blueprints found.
  Example File: project/sanic_server.py -> app
  Example Module: project.sanic_server.app

**Comment by sjsadowski** [comment]
I don't think this is a problem with blueprints, but you'd have to post more of your project for anyone to know.

**Comment by ahopkins** [comment]
I am going to close this issue for now. @RainJayTsai if you are still experiencing problems, you can repoen for more discussion. Include some information about what kind of environment you are running (docker, bare metal, virtualenv, etc).
