### ISSUE TITLE
Request type is used instead of file type on file.type

### ISSUE THREAD

**Issue by aveao** [huge-success/sanic#1311]
Heya!

I've noticed that `file.type` over [here](https://sanic.readthedocs.io/en/latest/sanic/request_data.html#request-data) (see `files`) is not a mimetype for the file but for the request, grabbed from [`cgi.parse_header`](https://docs.python.org/3.5/library/cgi.html#cgi.parse_header).

This feels like an incorrect behavior as we (@elixire) previously assumed that this was for file mimetype, and it caused a bug that affecting many users.

I propose doing one (or more) of these:
- Updating documentation to state that it's not file type but request type
- Swapping it out for file's mimetype
- Removing `.type`
- Adding a `.mime` field to file with mimetype

We can get the proper file mimetype from either the file's magic header with [`python-magic`](https://github.com/ahupp/python-magic) or with the name through [mimetypes](https://docs.python.org/3.5/library/mimetypes.html) library. While `python-magic` would give more accurate results, it requires installing libmagic through distro's package manager which might not be favorable for some.

I'd just send a PR but wasn't sure which approach was the most favorable, so I'll send one once a decision is made regarding which approach will be taken.

**Comment by sjsadowski** [comment]
I disagree with this; the mimetype isn't necessarily passed. We're getting the appropriate information from the headers, as per https://tools.ietf.org/html/rfc6266#section-4. If you want to do magic interpolation around the file itself, I don't think that should be included in sanic core.

**Comment by aveao** [comment]
@sjsadowski while I agree that magic interpolation is overkill, passing request headers as file type is simply unreasonable.

Passing mimetype would make much more sense in this case.

**Comment by sjsadowski** [comment]
I think expanding the dependency tree by adding mimetypes seems like overkill. I'd say we'd be better off to remove .type to prevent confusion

**Comment by aveao** [comment]
Mimetypes is a standard lib and is used elsewhere in code (response.py iirc), so I don't think that it'd expand the dep tree.

On September 13, 2018 11:58:09 PM GMT+03:00, Stephen Sadowski <notifications@github.com> wrote:
>I think expanding the dependency tree by adding mimetypes seems like
>overkill. I'd say we'd be better off to remove .type to prevent
>confusion
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/huge-success/sanic/issues/1311#issuecomment-421150669

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjsadowski** [comment]
I'd actually forgotten about that. If you push it through mimetypes.guess_type() the filetype would be the mime encoding or None if it couldn't guess. That's not horrible I suppose.

**Comment by sjsadowski** [comment]
@aveao there's a single outstanding request for your PR. Could you take a look at that?

**Comment by aveao** [comment]
I'll take a look tomorrow.

**Comment by sjsadowski** [comment]
Looks like interest in this was dropped. We can open a new issue to address going forward if necessary.
