### ISSUE TITLE
docker deployment:  alpin, slim not supported

### ISSUE THREAD

**Issue by liulwx** [huge-success/sanic#1320]
sanic cannot be installed when using python-alpine or python-slim
3.6.6-slim-stretch, 3.6-slim-stretch, 3.6.6-slim

I can install sanic using python:3.6.6

**Comment by ahopkins** [comment]
I have it running on `python:3.6.4-alpine`

Can you explain why you are unable to deploy it on docker? What are you experiencing?

**Comment by c-goosen** [comment]
You might need gcc to get libuv to compile.

FROM python:3.6-alpine
COPY ./ctrl_api /ctrl_api

WORKDIR /ctrl_api/
RUN ls
RUN apk add --update --no-cache build-base python3-dev libffi-dev openssl-dev
RUN pip install virtualenv
RUN virtualenv -p python3.6 venv
RUN source venv/bin/activate
RUN pip install -r dev_requirements.txt

**Comment by liulwx** [comment]
> I have it running on `python:3.6.4-alpine`
> 
> ```
> FROM python:3.6.4-alpine
> 
> RUN apk update \
>     && apk add build-base
> ```
> Can you explain why you are unable to deploy it on docker? What are you experiencing?

I want this to be executed successfully
```
FROM python:3.6.6-slim-stretch

ADD . /app

WORKDIR /app

RUN pip install sanic

EXPOSE 7000

CMD ["python", "src/app.py"]
```
The error is 
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I./python -I./lib -I/usr/local/include/python3.6m -c ./python/ujson.c -o build/temp.linux-x86_64-3.6/./python/ujson.o -D_GNU_SOURCE
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1

**Comment by c-goosen** [comment]
@liulwx Alpine linux is not based on gcc but musl. 

You need to install gcc first.

Hence `RUN apk add --update --no-cache build-base`

**Comment by c-goosen** [comment]
@liulwx I am not familiar with slim-stretch. If its ubuntu based you need to install gcc first.

apt-get install build-essential gcc

**Comment by liulwx** [comment]
> @liulwx Alpine linux is not based on gcc but musl.
> 
> You need to install gcc first.
> 
> Hence `RUN apk add --update --no-cache build-base`

Thank you for you solving my problem.
Can you provide a basic docker image in docker hub. Then we can deploy sanic in docker-alpine like flask. When using flask, I have no need to manually install gcc in alpine or slim

**Comment by ahopkins** [comment]
I've actually been working on this... Later this week I plan on uploading both a sanic alpine base image and one with sanic-jwt.

I'm closing this for now. Feel free to continue discussing if need be.

**Comment by amireldor** [comment]
Hello. Is it nice to have  `RUN apk del build-base` after the installation of sanic to reduce the docker image size?
