### ISSUE TITLE
How you unregister a static file?

### ISSUE THREAD

**Issue by corsariovasco** [huge-success/sanic#1324]
With app.static(..) you register a file static but I would like to know like I might unregister or in default know all registered static files.

Kind regard,

**Comment by sjsadowski** [comment]
Currently this is not possible.

Can you provide a use case where you would want to unregister a static file?

**Comment by corsariovasco** [comment]
Thanks for your reply.

I will try to set an example.
We create a special document in python and expose by means of a service based on sanic. 
Well, this document is created for each user and it is stored in your folder according to the session. We need to incorporate it into app.static, in this way the user might download it. 
If the user requests a new document with the same name. As we have not way the check the app.static files and we will get an error on the register.
Besides, we can not expose all folders o parent folder because another user could see them.
I do not know if I explain to you correctly. You understand me?.

**Comment by ahopkins** [comment]
@corsariovasco Since you are creating the document in python, have you thought about potentially sending the content as a stream? https://sanic.readthedocs.io/en/latest/sanic/streaming.html

**Comment by vltr** [comment]
@corsariovasco I think a stream might be the best way to accomplish this, as @ahopkins mentioned. Trying to add new - and even remove - routes, using `app.static`, may be error prone if you're dealing with more than one worker or service at the same time (or if you're planning to in the future).

**Comment by sjsadowski** [comment]
I think I'm going to +1 for streams. I also have a use case for dynamic file delivery and already use streams for that. Based on 3 of us pointing that direction, I'm going to close this.

**Comment by corsariovasco** [comment]
Thanks everybody for your replies.

Kind regards,
