### ISSUE TITLE
Rename modules to not conflict with the standard library

### ISSUE THREAD

**Issue by ahopkins** [huge-success/sanic#1326]
As discovered by Issues #1323, there are modules that are named as the same as [standard library modules](https://docs.python.org/3/library/index.html).

In particular, [`http.py`](https://github.com/huge-success/sanic/blob/master/sanic/http.py) conflicts with [`http`](https://docs.python.org/3/library/http.html).

We should rename `http.py` to `helpers.py` or something that will not conflict.

**Comment by hramezani** [comment]
If it is just a rename and change the files that import `http.py`, I can do it.

**Comment by vltr** [comment]
Thanks, @hramezani ! This was already handled on #1327 :wink:
