### ISSUE TITLE
Sharing Values in A Dict Among Workers 

### ISSUE THREAD

**Issue by meckin** [huge-success/sanic#1328]
Greetings, 

Thanks for any suggestions in advance.  I'm looking to create a python dict that will house a list of things. This list of things, will have a "status" that informs workers of their state. Either working, skip, or broken each worker will go over the list in a round robin fashion at different points in the list. 

Each worker needs to understand the status of each "thing", but I'm unsure how to share this among workers. 

My idea is to initialize the class and then pass the class into each async worker, but I'm unsure if this is how Sanic handles this kind of thing. 

The dict will be shared among workers, and will have to stay up-to-date and append the list.

Does anyone have any suggestions? 

Thanks again in advance

**Comment by m-equinox** [comment]
Hi,
Look, maybe this is what you want: #1270

**Comment by ahopkins** [comment]
@meckin I think it really depends on the ultimate deployment strategy. By "worker" do you mean multiple instances of sanic? In a single docker container? Asked another way, how do you plan to run sanic?

Honestly, in situations like this I much prefer to break each "worker" into a separate instance of sanic running in an isolated container and communicate through a message broker, pubsub, etc. I have also used [`mmap`](https://docs.python.org/3/library/mmap.html) in a situation like this in the past.

**Comment by yunstanford** [comment]
Honestly, the suggestion here https://github.com/huge-success/sanic/issues/1270 is error-prone in a lot cases, like process recycling, worker failover, and your system will be not resilient.

**Comment by meckin** [comment]
@yunstanford I completely agree, it's too complex to be a solution for such a small data point. Do you have any suggestions? 

Thanks,
M

**Comment by ahopkins** [comment]
For more discussion, please reopen in https://community.sanicframework.org/
