### ISSUE TITLE
Pin versions for LTS release

### ISSUE THREAD

**Issue by sjsadowski** [huge-success/sanic#1331]
I think that versions of (some) should be allowed to float but when we are ready for an LTS release, the versions should be pinned at that time.

@r0fls @ahopkins @seemethere @ashleysommer @yunstanford @ahopkins

**Comment by vltr** [comment]
@sjsadowski if we pin `httptools` to be `>=0.0.10`, then we can tackle #1057 (I don't know if we re-open it or create another related issue) :wink:

**Comment by sjsadowski** [comment]
@vltr I'm going to branch today for the LTS release, we can set pins there. I'm actually okay (if we can get enough interest) with pinning a minimum version of httptools in master as well.

**Comment by vltr** [comment]
@sjsadowski oh yes, pinning `httptools` would make a lot of developers happy around here ...

**Comment by sjsadowski** [comment]
@vltr let's do it. I have not seen anything that suggest that should not be done. Can you get a PR in and we'll merge it after someone upchecks it. I'm hoping to get the other current PRs in this week after review and then merge them up to the 18.12 LTS branch.

**Comment by vltr** [comment]
@sjsadowski sure thing! Let me see if this will not conflict with #1310 (dumb one here forgot to create a branch for it ... :grimacing:)
