### ISSUE TITLE
Don't use `logger.error(format_exc())`

### ISSUE THREAD

**Issue by untitaker** [huge-success/sanic#1332]
Whenever an error happens, sanic stringifies the exception and logs it. This interacts really poorly with [Sentry.io](http://sentry.io/) (disclaimer: I am affiliated) and probably every similar tool out there because an error log of the stringified exception will be seen as a distinct error from the error already caught via errorhandlers.

There are a few possible fixes that we can make in our sanic integration without having to touch sanic:

1. Ignore the `"root"` logger. Sanic [logs to a logger just called root](https://github.com/huge-success/sanic/blob/076cf51fb295e7624968db766fd613aa3948289d/sanic/handlers.py#L86). This is undesirable because that logger might actually contain useful errors as well.
2. Error deduplication based on comparing stringified tracebacks. Let's just not go there.

But rather I'd like to change how Sanic logs those errors. Instead of `error(format_exc())`, what about this?

`error("Failed to run handler", exc_info=sys.exc_info())`

Or this?

`logger.exception("Failed to run handler")`

**Comment by untitaker** [comment]
@sjsadowski what does this label mean? Would you accept a PR changing how this is logged?

**Comment by sjsadowski** [comment]
Logging has been a [long-term problem](https://github.com/huge-success/sanic/issues?utf8=%E2%9C%93&q=is%3Aissue+logging) for this project and I will happily suggest a PR be submitted, but it will need to get reviewed. I do not know if doing this has larger implications at the moment, thus it needs to be investigated.

**Comment by untitaker** [comment]
That depends entirely on what you consider part of your API, so I'm not sure what investigation means in this context.

**Comment by sjsadowski** [comment]
Just some outstanding questions are on the PR. Otherwise I'm fine with merging #1336 and closing this.

**Comment by untitaker** [comment]
BTW, since progress on #1336 isn't that quick the Sanic integration just ignores the `root` logger at the moment.
