### ISSUE TITLE
ModuleNotFoundError: No module named 'http.cookies'; 'http' is not a package

### ISSUE THREAD

**Issue by bunyk** [huge-success/sanic#1339]
I'm getting following error, but not sure from where in my code it originates, because all files of the trace are in sanic package:

```
web    | Traceback (most recent call last):
web    |   File "/usr/local/lib/python3.7/site-packages/sanic/__main__.py", line 4, in <module>
web    |     from sanic.log import logger
web    |   File "/usr/local/lib/python3.7/site-packages/sanic/__init__.py", line 1, in <module>
web    |     from sanic.app import Sanic
web    |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 21, in <module>
web    |     from sanic.server import serve, serve_multiple, HttpProtocol, Signal
web    |   File "/usr/local/lib/python3.7/site-packages/sanic/server.py", line 31, in <module>
web    |     from sanic.request import Request
web    |   File "/usr/local/lib/python3.7/site-packages/sanic/request.py", line 6, in <module>
web    |     from http.cookies import SimpleCookie
web    | ModuleNotFoundError: No module named 'http.cookies'; 'http' is not a package
```

To reproduce: clone https://github.com/bunyk/sanic-tdidf and run `docker-compose up`.  (I'm trying to create more minimal example, but not figured exact place where this happens yet). Anyway, my project is almost of hello-world complexity.

I'm using sanic==0.8.3

**Comment by bunyk** [comment]
Weird thing is that inside container, this gives error:

```
>>> from http.cookies import SimpleCookie
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'http.cookies'; 'http' is not a package
```

But outside - not.  But in both cases I'm running python 3.7.0. Probably error is with some dependencies...

**Comment by vltr** [comment]
@bunyk , please see PR #1327 :wink:

**Comment by sjsadowski** [comment]
Duplicate - see @vltr 's comment

**Comment by vltr** [comment]
@bunyk yeee ... I don't know. `pip install` from `hatarist:fix-1323` would be a solution for that but I really don't like to do this kind of installations **unless** extremely necessary ... If you can run your app by calling `$ python server.py` to avoid this, well, until this fix comes out ... I don't know, this is really up to you I guess :confused:

**Comment by bunyk** [comment]
Oh, yes, I reread what hatarist wrote, and running server not with `python -m sanic` , but with 
```
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=app.config.PORT)
```
inside my code works. Thanks.

**Comment by vltr** [comment]
@bunyk no problem, I hope this solves your problem (for now) :wink:
