### ISSUE TITLE
[Un]necessary code?

### ISSUE THREAD

**Issue by vltr** [huge-success/sanic#1340]
This:

https://github.com/huge-success/sanic/blob/fafe23d7c273a8329006a986dc9c73643b92e091/sanic/server.py#L153-L156

Couldn't be translated into this?

```python
exception = RequestTimeout("Request Timeout")
self.write_error(exception)
```

Another one here:

https://github.com/huge-success/sanic/blob/fafe23d7c273a8329006a986dc9c73643b92e091/sanic/server.py#L173-L176

Because there is a lot of these code patterns already in `server.py`:

https://github.com/huge-success/sanic/blob/fafe23d7c273a8329006a986dc9c73643b92e091/sanic/server.py#L202-L203

I can submit the PR, just for uniformity.

**Comment by sjsadowski** [comment]
Stuff like this makes me wonder if I'm bad at python (high probability) or crazy (also high probability). 

Is there a reason you would try: raise and then catch the exception you raised in the try, when the raise is the only statement in the try block? I could see if we were wrapping things around the if blocks... but I'm all for leaning out the code if we can and there's no specific reason.

**Comment by vltr** [comment]
> Stuff like this makes me wonder if I'm bad at python (high probability) or crazy (also high probability).

That made me laugh. Welcome to the club :beers:

> Is there a reason you would try: raise and then catch the exception you raised in the try, when the raise is the only statement in the try block?

Well, no. Perhaps there might be a reason on the git history, idk. But, I'll send a PR tomorrow either way :wink:

**Comment by ashleysommer** [comment]
I've seen these same patterns in server.py, and I too have (internally) questioned their purpose.
I have always assumed there is some nuanced low-level reason they are done that way.

I now have a different theory. I haven't looked back through the git history, but I think maybe the error handling section of the `server.py` file has been rewritten at some point, maybe each section was able to raise an exception, and the `write_error` was handled elsewhere, then at some point in time it was decided (for performance reasons?) to write out the error as soon as the exception is thrown, so it just ended up that way.
I can try translating those parts, if all of the tests still pass then I don't see anything wrong with removing those sections in favour of the translations.

**Comment by vltr** [comment]
Thanks, @ashleysommer ! I think I understood the general idea, but I don't know how I'd implement it. Anyway, if you need some help, please let me know :+1:

**Comment by abuckenheimer** [comment]
I think the point is that by raising you attach a traceback

```
import traceback

def with_raise():
    try:
        raise RuntimeError('failing')
    except RuntimeError as e:
        return e

e1 = with_raise()
print('with raise')
print('\n'.join(traceback.format_exception(type(e1), e1, e1.__traceback__)))


def without_raise():
    return RuntimeError('failing')

e2 = without_raise()
print('without raise')
print('\n'.join(traceback.format_exception(type(e2), e2, e2.__traceback__)))

## -- End pasted text --
with raise
Traceback (most recent call last):

  File "<ipython-input-4-9db7dae0feba>", line 5, in with_raise
    raise RuntimeError('failing')

RuntimeError: failing

without raise
RuntimeError: failing
```

**Comment by ashleysommer** [comment]
@abuckenheimer Yes I agree, and that fact that removing these try/catch sections also removes the tracebacks _did_ cross my mind.

However! I think removing them in this case is the best option, because we _dont need_ tracebacks at those points in the code. Each of these exception objects are passed straight into `write_error()` for the purposes of generating a HTTP Error Response, and doesn't even use the traceback.

**Comment by ashleysommer** [comment]
Ah yes. You're right. I wonder what happens if it tries to get the traceback info from an exception object that doesn't have traceback info attached. It should fail gracefully and not print anything.

The other thing to consider is that adding a traceback in these specific cases doesn't add any useful new information to the exception. Knowing where the exception originated doesn't help because we created and raised them deliberately at those locations.

Also, the default exception handler only renders the traceback if `debug` is true. Would it make sense to have the try/catch method with tracebacks attached if running in debug mode, and an alternate path with the cleaner method if debug is off?

**Comment by ashleysommer** [comment]
I just noticed this:
https://github.com/huge-success/sanic/blob/master/sanic/handlers.py#L109.L115
Basically if the exception is a subclass of `SanicException`, it renders the response as text, _without_ including a traceback.
So in this case `ResponseTimeout`, `RequestTimeout`, `PayloadTooLarge` etc are all `SanicException`s thus are not expected to have a traceback attached.

**Comment by abuckenheimer** [comment]
True but I think `self.log(format_exc())` on line 108 would only format with a traceback if we raise.

As an aside I think your right that we may not specifically need the traceback but unless we could show a reasonable performance gain I don't think we should strip anything that may be useful in debugging.

**Comment by ahopkins** [comment]
I agree with @abuckenheimer. If we were building this now, the traceback gain is so minimal in this instance that the pattern does not make sense.

However (and this is something I think should be a guiding principle) we should not change the functionality unless we have a sufficient reason (adding a new feature or gaining performance).

So I think we need to first get a good reliable benchmark, adopt that as our standard, and rest changes like this against it. 

In the meantime, we can "clean up" these parts of the code by adding some good comment blocks that explain what and why.
