### ISSUE TITLE
Problem with redirect

### ISSUE THREAD

**Issue by Zolegz** [huge-success/sanic#1344]
I want POST request to be redirected from one application to another (I am also using ssl). Here is similar to my code:
````
from sanic import Sanic
from sanic import response

app = Sanic(__name__)

    
@app.route('/', methods=['POST'])
def handle_request(request):
    print('trying to redirect')
    return response.redirect('/redirect')


@app.route('/redirect', methods=['POST'])
async def test(request):
    print('redirected')
    return response.json({"Redirected": True})

ssl = {'cert' : my_cert, 'key' : my_key}

if __name__ == '__main__':
    app.run(port=8000, ssl=ssl, debug=True)
````

Sanic doesn't write any errors in console, i get this 'trying to redirect' printed, but nothing else after request. I also tried:

```
url = app.url_for('/redirect')
return response.redirect(url)
```
But that is also a mistake "Endpoint with name `/redirect` was not found" in function url_for

**Comment by sjsadowski** [comment]
These methods are both POST only; redirect will redirect to a GET. 
```curl -X POST https://[server]/redirect``` would work and return your json, 
but if you were to do ```curl -X POST -L https://[server]/``` (-L is necessary to follow the redirect) you would still get an endpoint not found error.
