### ISSUE TITLE
Python (and documentation) code rules

### ISSUE THREAD

**Issue by vltr** [huge-success/sanic#1355]
Hello everyone!

I think it is time for us to think about coding rules and standards. We should be able to work on the Sanic codebase seamlessly regarding the developer, editor, OS and etc.

Some tools / configs I can think of to accomplish this:

- [black](https://black.readthedocs.io/en/stable/)
- [flake8](http://flake8.pycqa.org/en/latest/)
- [isort](https://isort.readthedocs.io/en/latest/)
- [editorconfig](https://editorconfig.org/)
- [check-manifest](https://pypi.org/project/check-manifest/)
- [docutils](http://docutils.sourceforge.net/) - check #1354 as well

And, of course, which rules would we set for the tools we choose. I really find problematic to work on the Sanic codebase as is, without these set of rules to effectively work on.

Also, regarding the docs: isn't better to work with reStructuredText instead of Markdown? It has a lot of useful extra features in conjunction with Sphinx.

Let me know your thoughts, @huge-success/sanic-core-devs

**Comment by ahopkins** [comment]
This seems like a conversation ripe for the forums. It would be nice to keep GitHub issues related to features and bugs with the forum for help/support/development discussion (including tooling), etc.

**Comment by vltr** [comment]
Thanks, @ahopkins !

Discussion [moved to the forums](https://community.sanicframework.org/t/python-and-documentation-code-rules/38).

**Comment by sjsadowski** [comment]
Closing - discussion moved to forums.
