### ISSUE TITLE
Multiple identical route variables

### ISSUE THREAD

**Issue by ahopkins** [huge-success/sanic#1359]
### Problem

Currently, the router allows you to define the same variable multiple times in a route. What happens if you do? It simply grabs the last one.

Let me show you what I mean:

```from sanic import Blueprint, Sanic
from sanic.response import text

app = Sanic(__name__)


@app.get("/<test>/<test>")
async def multiple_identical_variables(request, test):
   return text(test)


if __name__ == '__main__':
   app.run(host="0.0.0.0", port=1234)
```

Then query it:

```
$ curl localhost:1234/foo/bar
bar
```

### Expected outcome

I think that the server should (at a minimum) throw me a warning that there is a route that potentially will dome something unintended on it. Taking that one step further, I sort of feel like it should raise an exception.

I am thinking more in terms of nested blueprints with conflicting `url_prefix`. Without a notice of some sort, I think this has the potential to be a difficult bug for someone to identify.

**Comment by yunstanford** [comment]
Yeah, we can probably just raise exception explicitly.

**Comment by vltr** [comment]
@yunstanford you mean raise an exception when? A check before the server start, on every new route or if a request hits an endpoint with two identical variables?

**Comment by ahopkins** [comment]
For any newcomers to the conversation, exception on startup.
