### ISSUE TITLE
Components instead of globals

### ISSUE THREAD

**Issue by sirex** [huge-success/sanic#1362]
I like how apistar and vibora implemented components and I would like to see something similar in Sanic, in stead of using globals.

More information: https://docs.vibora.io/initial

There is no need to reinvent whole dependency injection thing and components can be injected using https://github.com/ivankorobkov/python-inject for example.

Components also could be used for things like authentication.

**Comment by ahopkins** [comment]
This is likely not something that is on the near term development list (while I do agree that component injection is awesome). On the other hand @vltr is working on something just like this as a plugin. I'll let him explain further. 

+1  for the idea though!

**Comment by yunstanford** [comment]
I don't see anything needs to be global if `request` has attached `app`.

**Comment by yunstanford** [comment]
Thanks! Gonna close this issue.
