### ISSUE TITLE
Do I need separate WSGI servers sanic?

### ISSUE THREAD

**Issue by bubnenkoff** [huge-success/sanic#1369]
Do I need separate WSGI servers for sanic?

And do I need nginx for static?

**Comment by ahopkins** [comment]
You certainly do not **need** to run a wsgi process (like gunicorn), or another web server (like nginx). But, of course you can.

Have you seen the [documentation on deployment?](https://sanic.readthedocs.io/en/latest/sanic/deploying.html) Also, checkout #1274 about some deployment ideas.

Personally, I would put sanic into a container and run the container and put a load balancer (like nginx) in front of that. Also, while you can [serve static files](https://sanic.readthedocs.io/en/latest/sanic/static_files.html), I generally prefer to do that from nginx anyway and not inside python. No need for it in my personal opinion. But the option is of course yours.

Feel free to bring the discussion to [the community forums](https://community.sanicframework.org/) if you would like to discuss this more.

**Comment by bubnenkoff** [comment]
@ahopkins so I can use sanic in *prod* without wsgi/nginx? Cool!
Django afaik cant work without them in prod.

**Comment by ahopkins** [comment]
https://community.sanicframework.org/t/gunicorn-uwsgi-vs-build-in-http-server/47/2?u=ahopkins
