### ISSUE TITLE
readthedocs - tag not available

### ISSUE THREAD

**Issue by sjsadowski** [huge-success/sanic#1374]
**Describe the bug**
When using the tag to view specific version documentation, the docs are unavailable.

**Code snippet**
Visit https://sanic.readthedocs.io/en/latest and select the tag for '0.8.3' or visit https://sanic.readthedocs.io/en/0.8.3/ directly

**Expected behavior**
Documentation is available

This is more irksome than a real problem at the moment, however when we release 18.12 and for further versions we should be making sure that 'latest' and 'stable' are appropriately linked to the version they represent, as well as having documentation for the release version (especially for LTS) directly available.

**Comment by yunstanford** [comment]
And the readthedoc build is failing for long time.

**Comment by yunstanford** [comment]
Actually there is another error that we need figure out, you can take a look at above link

**Comment by yunstanford** [comment]
The link in that PR

**Comment by ahopkins** [comment]
I just looked at the comment about the build failing....

Looks to me like an rst issue. Take a look at that message. There is a location that needs and extra line break after the code block definition. I'm on my phone so I cannot make the change right now. Can e should reopen the PR, fix that and then run sphinx to make sure it is solved.

**Comment by sjsadowski** [comment]
@huge-success/sanic-core-devs someone double-check me but it looks like it's failing because of a gunicorn dependency not being met?

http://readthedocs.org/projects/sanic/builds/7989537/

**Comment by ahopkins** [comment]
@sjsadowski This is what I was referring to. It looks like a rst compile error in that there is a missing li e break after the code block line. I meant to check when I was in the office earlier and forgot.

**Comment by sjsadowski** [comment]
Ah, I see now. Thanks for the clarification @ahopkins

**Comment by ahopkins** [comment]
See PR #1383, there were 5 files that were causing an issue.
