### ISSUE TITLE
Auto reload causes debuggers not to attach properly

### ISSUE THREAD

**Issue by mackeyja92** [huge-success/sanic#1381]
**Describe the bug**
When in debug mode, the auto reload functionality seems to break debuggers such as PyCharm.

**Expected behavior**
Auto reload and debugger support.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: 0.8.3

**Comment by vltr** [comment]
@mackeyja92 thanks for your report!

There's an ongoing discussion related to the `auto_reload` feature in the [community forums](https://community.sanicframework.org/t/following-auto-reload-support-for-windows/35?u=vltr). You should definitely check it out - although it started as a Windows support for this feature, it aims to contemplate all OSes :wink:

**Comment by mackeyja92** [comment]
https://github.com/watchexec/watchexec May be a good candidate to support all OSes.

**Comment by ahopkins** [comment]
Closing in favor of #1346 and the community discussion linked above.

**Comment by marijngiesen** [comment]
Why is this closed? This is a bug for all I know.

Setting debug=True or auto_reload=True breaks PyCharm debugging. I like to have debug logging and use PyCharm to debug my code, but that's not possible right now because setting debug=True will also enable the auto_reload stuff.

Please fix this
