### ISSUE TITLE
Need better documentation on unittesting

### ISSUE THREAD

**Issue by bunyk** [huge-success/sanic#1384]
Let me, for example, have application from [getting started](https://sanic.readthedocs.io/en/latest/sanic/getting_started.html) that returns `{"hello": "world"}` when getting '/'. 

So, I write following unittest:
```python
import unittest

from main import app # main.py created in getting started

class TestHello(unittest.TestCase):
    def test_hello(self):
        _, response = app.test_client.get('/')
        self.assertEqual(response.status, 200)

```

It works, when I change status code - fails, and passes when code is 200. But then I want to test actual content of response, and I wander how? 

I guess response is instance of [aiohttp.ClientResponse](https://aiohttp.readthedocs.io/en/stable/client_reference.html#response-object), but there json is method (and async, I guess), and in response in test - it is already parsed response. 

So, maybe it would be helpful to add to examples in test also asserts about content, like:

```python
        _, response = app.test_client.get('/')
        self.assertEqual(response.status, 200)
        self.assertEqual(response.json, {"hello": "world"})
```

And info about what else could be checked on response for testing. Headers, raw payload...

**Comment by sjsadowski** [comment]
@bunyk We always welcome contributions. If you'd like to help create some additional documentation around this and submit a pull request, that would be really helpful!

**Comment by bunyk** [comment]
I would love to, but I not yet figured out what is response and why do we need request.

Maybe I will, after I'll come back to adding unittests, because currently other tasks are due.

**Comment by ahopkins** [comment]
@bunyk `app.test_client.get()` (and the other methods for that matter), take an argument: `gather_request`.

When `gather_request == True`, it returns a tuple of the `request` and `response` object.

This is [already in the docs](https://sanic.readthedocs.io/en/latest/sanic/testing.html#testing)

> gather_request (default True) A boolean which determines whether the original request will be returned by the function. If set to True, the return value is a tuple of (request, response), if False only the response is returned.

**Comment by sjsadowski** [comment]
I missed that @ahopkins. Closing.
