### ISSUE TITLE
Can't working with Image

### ISSUE THREAD

**Issue by StVl** [huge-success/sanic#1389]
**Describe the bug**
Trying to send in response the image from the PIL
the error is "TypeError: expected str, bytes or os.PathLike object, not a Image"

**Code snippet**
```
byte_io = BytesIO()
final_img.save(byte_io, media_type.upper(), quality=quality) #media_type=jpeg
byte_io.seek(0)
mime_type = 'image/' + media_type
return await response.stream(final_img, mime_type)

```
Maybe you know, how i can fix it
thanks!
(telegram: @stvlpotapov )

**Comment by sjsadowski** [comment]
it appears that final_img is an object, not a string, bytes, or os.Path - which is generally indicated that you're calling a method (final_img.save()).

Perhaps you need to find the method that returns the raw bytes for final_img? Either way, this isn't exactly a sanic bug or issue.

**Comment by ahopkins** [comment]
@StVl Bring this to the [community forums](https://community.sanicframework.org/) if you need some more help 😄
