### ISSUE TITLE
app.stop() does not stop the server

### ISSUE THREAD

**Issue by d-Rickyy-b** [huge-success/sanic#1394]
**Describe the bug**
I am trying to stop the server with `app.stop()` but it seems that it does not work. The server still continues running. I am running the server in a seperate thread and calling `app.stop()` from the main thread.

**Code snippet**
```
from threading import Thread
from sanic import Sanic

app = Sanic()
thread = Thread(target=app.run, name="sanicAPI", kwargs=dict(host="0.0.0.0", port=8080, debug=True))
thread.start()

app.stop()
thread.join()
```

**Expected behavior**
The server should shut down and the thread should join back into the main thread.

**Environment:**
 - OS: Windows 10 (1803), build 17134.345
 - Sanic Version: 0.8.3

**Additional context**
I am starting the server in another thread because I have an application where I additionally need a very small API server to handle tiny amounts of requests to control the application or receive data from it.

Am I doing something wrong? Any kind of help is appreciated. Thanks for the great project.

**Comment by d-Rickyy-b** [comment]
@harshanarayana Thank you very much. I actually did not find it yet. It looks promising.

I will try to implement that tonight and will report back if that solves my issue :).

Maybe that can be referenced in the documentation? (If it already is, I must be blind, sorry)

**Comment by ahopkins** [comment]
@d-Rickyy-b I thought it had been in the docs, because that is basically the setup that I am using. But, now I am looking back and forth thru them and cannot find it. I must have used it from the examples. I'll tag this as something worth documenting.

**Comment by yunstanford** [comment]
`app.stop()` just stops the running event_loop. and each thread has its own event loop. Also you probably won't need multiple threads for async application.

**Comment by d-Rickyy-b** [comment]
@yunstanford I just wanted the API to run in another than the main thread so that it's not blocking the main thread. The posted example helped a lot. I am not finished yet but I guess I can solve the initial issue I got with it.

**Comment by vltr** [comment]
@d-Rickyy-b take a look at [this](https://docs.python.org/3/library/asyncio-subprocess.html#subprocess-and-threads). `threading` and `asyncio` have some requirements to run properly.
