### ISSUE TITLE
Logger not work.

### ISSUE THREAD

**Issue by chenjr0719** [huge-success/sanic#1395]
**Describe the bug**
Logger did not work at current master commit (https://github.com/huge-success/sanic/commit/7d79a86d4dc48de11cd34e8ba12e41f3a9f9ff18).

**Code snippet**
```python
from sanic import Sanic
from sanic.log import logger
from sanic.response import text


app = Sanic()

@app.listener('before_server_start')
async def setup(app, loop):
    logger.info('INFO')


@app.get('/')
async def test(request):
    return text('hello world')


if __name__ == '__main__':
    app.run()
```
There is no any log/output now.

**Expected behavior**
At `0.8.3` release, it will logging/output some messages like:
```
[2018-11-05 17:34:47 +0800] [12112] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-11-05 17:34:47 +0800] [12112] [INFO] INFO
[2018-11-05 17:34:47 +0800] [12112] [INFO] Starting worker [12112]
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: https://github.com/huge-success/sanic/commit/7d79a86d4dc48de11cd34e8ba12e41f3a9f9ff18

**Additional context**
It seems that `getLogger()` does not get the correct logger at [line 56](https://github.com/huge-success/sanic/blob/master/sanic/log.py#L56) in `log.py`. The logger is trying to get a logger named `sanic.root`, but it does not exist. Rename the logger `root` at [line 9](https://github.com/huge-success/sanic/blob/master/sanic/log.py#L9) should fix this bug.

**Comment by ahopkins** [comment]
@chenjr0719 Can you submit a PR?

**Comment by KeepitReal555** [comment]
I'd like to submit a PR for this, can I?

**Comment by chenjr0719** [comment]
@KeepitReal555 Sure, be my guest.
@ahopkins I found something weird. There are 5 test cases in `test_logging.py` and they can all pass even this bug still not fixed. Are all tests will be run when the PR has been merged? If so, I will try to fix those tests to ensure the same bug will not happen again.

**Comment by harshanarayana** [comment]
@KeepitReal555 @chenjr0719 @ahopkins 
Test cases are passing beause we are not asserting to validate the default log levels in the unit tests. 
`assert logging.getLogger('sanic.root').getEffectiveLevel() == logging.INFO` need to be added into `test_logging_defaults` method under `test_logging.py`

**Comment by KeepitReal555** [comment]
@harshanarayana thanks, I didn't think enough, I will modify it right now.

**Comment by harshanarayana** [comment]
@KeepitReal555 Thanks for the consideration.

**Comment by ahopkins** [comment]
awesome work everyone! Closing this now since there is a PR to discuss further if needed. See #1397
