### ISSUE TITLE
asyncio Lock does not work in appropriate way

### ISSUE THREAD

**Issue by stopfaner** [huge-success/sanic#1396]
I was developing Connection Pool for my own purposes via asyncpg driver. In my case I needed custom in-memory Connection Pool. To achieve thread safeness I wrapped my code into asyncio.Lock(). But while I try simultaneously access to that method and lock is not released, I get an error: 

> RuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /Users/user1/.virtualenvs/wsgi_test/lib/python3.6/site-packages/sanic/app.py:603>> got Future <Future pending> attached to a different loop

While it should wait until lock released and continue execution, it throws error above.
Sample of code you can find here (I deal with it like with context manager, but in fact it does not matter):

```
class LockTest:
    LOCK = asyncio.Lock()

    async def test(self):
        async with LockTest.LOCK:
            await asyncio.sleep(10)
            return "Test"

    async def __aenter__(self):
        return await self.test()

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        pass
```

Did anyone faced the similar issue? (This happens only with sanic request execution)

**Comment by ahopkins** [comment]
How are you running Sanic? Take a look at #1388. It sounds like it is the issue you are running into.

**Comment by ahopkins** [comment]
I am going to close the issue. If this is not the problem, feel free to reopen.
