### ISSUE TITLE
Error: Range Header Not Found

### ISSUE THREAD

**Issue by Vitalio44** [huge-success/sanic#1417]
## Error: Range Header Not Found
I try get range from request, but take error.
```
from aiofiles.os import stat
from sanic.handlers import ContentRangeHandler


@app.get('/ax-media/<asset_id>/media/<file_name>')
async def video_get(request, asset_id, file_name):
    path = 'ax/assets/' + asset_id + '/media/' + file_name
    stats = await stat(path)
    _range = ContentRangeHandler(request, stats)  # problem is here 
    headers = {'Content-Type': 'video/mp4', 'Accept-Ranges': 'Accept-Ranges: bytes'}
    ...
```
Idea is to response a video file with a status of 206

**Comment by harshanarayana** [comment]
@Vitalio44 

```python
 _range = request.headers.get("Range")
if _range is None:
    raise HeaderNotFound("Range Header Not Found")
```
This is the section that causes the error you are referring to. Looks like your incoming request is missing the Http header `Range`.
eg: `Range: bytes=12-19`

Also, your snipped has another small issue that I noticed. `Accept-Ranges` header is wrong. 
It currently says `'Accept-Ranges': 'Accept-Ranges: bytes'` however, it should be `'Accept-Ranges': ' bytes'`

**Comment by Vitalio44** [comment]
> Hi @Vitalio44
> 
> ```python
>  _range = request.headers.get("Range")
> if _range is None:
>     raise HeaderNotFound("Range Header Not Found")
> ```
> 
> This is the section that causes the error you are referring to. Looks like your incoming request is missing the Http header `Range`.
> eg: `Range: bytes=12-19`
> 
> This missing header causes the `_range = ContentRangeHandler(request, stats)` line to throw an exception as per the above snippet.
> 
> Also, your snipped has another small issue that I noticed. `Accept-Ranges` header is wrong.
> It currently says `'Accept-Ranges': 'Accept-Ranges: bytes'` however, it should be `'Accept-Ranges': ' bytes'`

### another way
```
@app.route('/ax-media/<asset_id>/media/<file_name>')
async def handle_request(request, asset_id, file_name):
    print(asset_id, file_name)
    print(request.headers)
    print(request.headers.get("range"))
    path = 'ax/assets/' + asset_id + '/media/' + file_name
    return await response.file(path)
```
First time 'range': 'bytes=0-' then None. and then MemoryError

**Comment by harshanarayana** [comment]
@Vitalio44 Below code is taken from the example file `try_everything.py`

```python
@app.route("/file_stream")
async def test_file_stream(request):
    return await response.file_stream(os.path.abspath("setup.py"),
                                      chunk_size=1024)
```
