### ISSUE TITLE
Disabling the LOGO

### ISSUE THREAD

**Issue by rbw** [huge-success/sanic#1432]
**Describe the bug**
```
[D 2018-12-20 02:20:18.032 8537] False
[I 2018-12-20 02:20:18.032 8537] Goin' Fast @ http://0.0.0.0:8080 
```

Kept getting this in my Sanic log.

Started debugging and realized setting LOGO to a false value other than None is treated as a logo.

**Code snippet**
`app.config.LOGO=False`

**Expected behavior**
No logging of course.

**Additional context**
Let's get real - no one in their right mind would set LOGO to False, empty string, 0 or such and expect Sanic to treat it as an actual logo.

I think it's safe to assume that changing this:
https://github.com/huge-success/sanic/blob/e3a27c2cc485d57aa1ff87d9f69098e4ab12727e/sanic/app.py#L1107

to:
`not self.config.LOGO`

...wouldn't cause any breakage or upset anyone

**Comment by rbw** [comment]
Oh, yeah- and thank you for a great piece of software. Love it :+1:

**Comment by abuckenheimer** [comment]
Fine by me if you want to put in a PR for this

**Comment by ahopkins** [comment]
Agreed. Should be a simple PR to get approved.

**Comment by ahopkins** [comment]
See #1443 with the new logo and some changes to the LOGO.
