### ISSUE TITLE
Enforce Integer only value for Max-Age Cookie

### ISSUE THREAD

**Issue by harshanarayana** [huge-success/sanic#1452]
# Description
As per the `HTTP` standard guidelines, `Max-Age` for a `Set-Cookie` can only be an integer. 

> Max-Age=<number> Optional
> Number of seconds until the cookie expires. A zero or negative number will expire the cookie 
> immediately. Older browsers (ie6, ie7, and ie8) do not support max-age. For other browsers, if both > (Expires and Max-Age) are set, Max-Age will have precedence.

Current `Cookie` class provided by `sanic` has a fallback catch block that uses any value that you provide to `max-age` as a valid item and sets it. 

# Reference
1. `encode` method in `Cookie` [class](https://github.com/huge-success/sanic/blob/096c44b910443e74c821dbf21adf2f86ccda8611/sanic/cookies.py#L111-L115)
2. Community Discussion [Thread](https://community.sanicframework.org/t/housekeeping-items/91)

# Expected Behavior
If you pass a valid `interger` value to the `max-age` parameter, it needs to be set. Otherwise, it needs to be defaulted to `-1` or `0` causing it to auto expire.

**Comment by chenjr0719** [comment]
Related test:
https://github.com/huge-success/sanic/blob/cea1547e08230b6ad49eb7777fd8db5335382b7a/tests/test_cookies.py#L141-L156
