### ISSUE TITLE
Enforce Date Type for Expires on Set-Cookie

### ISSUE THREAD

**Issue by harshanarayana** [huge-success/sanic#1453]
# Description
As per the `HTTP` standard guidelines, the `Expires` parameter of the `Set-Cookie` needs to be a date in the format specified by the [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) as shown in [Mozilla Dev Guide](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date)

Current `encode` method in `sanic`'s `Cookie` class though enforces this standard, it will also allow you to set any item as a valid value via an exception catcher block.

# Reference
1. `encode` method in `Cookie` [class](https://github.com/huge-success/sanic/blob/096c44b910443e74c821dbf21adf2f86ccda8611/sanic/cookies.py#L116-L126)
2. Community Discussion [Thread](https://community.sanicframework.org/t/housekeeping-items/91)

# Expected Behavior
Only a valid `datetime` object that can be converted into a RFC standard date needs to be taken as a valid item

**Comment by chenjr0719** [comment]
@harshanarayana What about a string with valid format?

Related test:
https://github.com/huge-success/sanic/blob/cea1547e08230b6ad49eb7777fd8db5335382b7a/tests/test_cookies.py#L159-L181

**Comment by ahopkins** [comment]
Seems like an extra check for a relatively unimportant edge case.

**Comment by LTMenezes** [comment]
Is anybody currently working on this? I would like to work on this issue.
