### ISSUE TITLE
Request stream not working when using Blueprints

### ISSUE THREAD

**Issue by quasarj** [huge-success/sanic#1454]
**Describe the bug**
When trying to use Request Streaming in a route that is part of a blueprint, the request.stream object is never set (it is None), _unless_ `stream=True` has been set on some global route.

**Code snippet**
```
from sanic import Sanic
from sanic.response import text
from sanic.views import HTTPMethodView, stream
from sanic import Blueprint

app = Sanic()

# Not sure if using the decorator here is actually
# allowed or useful
@stream
def test(request):
    return text(type(request.stream))


class TestView(HTTPMethodView):
    @stream
    async def get(self, request):
        return text(type(request.stream))


bp = Blueprint("test")
bp.add_route(test, '/')
bp.add_route(TestView.as_view(), '/class')

app.blueprint(bp, url_prefix='/test')

# Adding this line makes request.stream work FOR ALL ROUTES,
# even those from the blueprint!
# app.add_route(test, '/', stream=True)

app.run(host='0.0.0.0', port=8000)
```

**Expected behavior**
Expect request.stream to be set.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04, RHEL7
 - Version 18.12.0 and master (cea1547e08230b6ad49eb7777fd8db5335382b7a)

**Additional context**
I am trying to sort this out myself, but the interaction between routes appears very complex. I will submit a pull request if I can get it working.

**Comment by chenjr0719** [comment]
@quasarj Are you still there?

According to the document, use request stream with `Blueprint` will look like this:
```python
from sanic import Sanic, Blueprint

bp = Blueprint("test")

@bp.get('/', stream=True)
def test(request):
    return text(type(request.stream))

app.blueprint(bp, url_prefix='/test')
app.run(host='0.0.0.0', port=8000)

```

If you want to use `bp.add_route()` with request stream, it seems not working currently because `bp.add_route()` does not support `stream` argument. Maybe I can send a PR to make it work.
