### ISSUE TITLE
Useful details about some HTTP errors discarded in InvalidUsage

### ISSUE THREAD

**Issue by rbw** [huge-success/sanic#1455]
**Describe the bug**
The `httptools.parser.errors.HttpParserError` exception gets useful details discarded when wrapped in `sanic.exceptions.InvalidUsage`.

For instance; if an invalid method is used, the "Invalid HTTP method" message gets replaced by just "Bad Request".

**Code snippet**

https://github.com/huge-success/sanic/blob/cea1547e08230b6ad49eb7777fd8db5335382b7a/sanic/server.py#L271-L275

**Expected behavior**
wouldn't it be better to just keep the original error message?

**Comment by rbw** [comment]
If someone wants the more generic "Bad Request" variant, it can be easily obtained from `sanic.helpers.STATUS_CODES` - right?

**Comment by ahopkins** [comment]
The details are passed when debug mode is on. I think this is right. And, the details are passed when debug mode is on. What do you think is missing? Closing for now, but feel free to repoen.

**Comment by rbw** [comment]
> For instance; if an invalid method is used, the "Invalid HTTP method" message gets replaced by just "Bad Request".
