### ISSUE TITLE
within Flask-PyMongo context: AttributeError: 'Sanic' object has no attribute 'url_map

### ISSUE THREAD

**Issue by scheung38** [huge-success/sanic#1458]
**Describe the bug**
    app.url_map.converters["ObjectId"] = BSONObjectIdConverter
AttributeError: 'Sanic' object has no attribute 'url_map' 

when changing from:

app = Flask(__name__) 

to 

app = Sanic(__name__) 

within Flask-PyMongo context:

 
```
from sanic import Sanic
from sanic.response import json

# app = Flask(__name__)
app = Sanic(__name__)
app.config["MONGO_URI"] = "mongodb://localhost:27017/cran_repo"
mongo = PyMongo(app)

@app.route('/', methods=['POST', 'GET'])
async def hello_world(request):
     
    if request.method == 'GET':
        return json({'Hello': 'world'})
```

**Expected behavior**
As normal Flask app to be running

**Environment (please complete the following information):**
 - OS: Mac OSX
 - Version Mojave

**Additional context**

**Comment by Fretice** [comment]
perhaps flask-pymongo use some flask api .if you want to use mongodb , you can use sanic-mongo

**Comment by chenjr0719** [comment]
Here is an example: https://github.com/huge-success/sanic/wiki/Examples#motor

**Comment by scheung38** [comment]
Thank you but there is no json.dumps in

from sanic.response import json

as in the normal:

import json

as I have yaml files that need to be converted into JSON before storing into MongodB, but if not, can I also store yaml directly into MongodB?

**Comment by ahopkins** [comment]
The json method in sanic is for creating a json response object and not for serialization. If you did a regular install of sanic, you probably have ujson available, which is an extremely fast alternative to the standard library json module.

As for the flask and sanic api differences, Sanic does not try to carry forward the Flask API, but exists independently and will differ in its api implementation.

Use ujson.dumps or do something like

    from json import dumps as import_dumps
