### ISSUE TITLE
Allow more flexible way to run the server

### ISSUE THREAD

**Issue by Dandi91** [huge-success/sanic#1467]
I am trying to write integration tests for my sanic application and I would like to be able to send multiple consecutive requests without stopping the server.

Note: I am running multi-worker sanic app in production and I want to test it when it runs exactly the same way.

Right now the sanic `test_client` is written in a way that it starts an application, runs a single http request, and then tears application down. So, clearly I can't use it.

Is it possible to run sanic app with multiple workers and do not block the main thread? For example, split `app.run()` into `app.start()` and `app.stop()` and let users control when to stop server. This approach also allows async applications to keep the loop running in the main thread (and still use multiprocessing), if such a need will occur.

Overall, I think it would be much more flexible design that would allow for better integration with existing code (ex. when people are trying to replace aiohttp with sanic and still want to use worker processes).
Is it something that someone can write a PR for or devs are not interested in such feature? (looking at #275 it might be the case)

**Comment by yunstanford** [comment]
@Dandi91 `pytest-sanic` doesn't tear down the server after serving each single request.

https://github.com/yunstanford/pytest-sanic

**Comment by Dandi91** [comment]
@yunstanford Yes, indeed it doesn't. Unfortunately, it doesn't run with multiple workers either, only in async configuration (which is different from what I run in production and I don't want to change this).

**Comment by yunstanford** [comment]
Any reason you need multi-worker mode in UnitTests ?

**Comment by sjsadowski** [comment]
It's been 10+ days with no further response from the requester. We can re-open if necessary

**Comment by cannonba11** [comment]
Exact same use case but from the testing perspective. If the app has in-memory state that I want to test by making successive requests to different routes in a single test, the `test_client` does not work as it tears down the app between calls and all the state is lost.

**Comment by ahopkins** [comment]
I have been doing quite a bit of work on the test clients lately ahead of 19.6 release. While I don't see any change to this behavior right now (since it is primarily for testing the framework), I do think that there is a use case for this.

How and where are you storing your state? if it is on some data structures inside your single test, then pytest should keep it alive for you.

With that said, I will factor out the run() and stop() calls so that they can be overridden. But this will mean that your tests will need to call them explicitly. Or, perhaps inside a contextmanager  so it can be done something like the following:

    with app.test_client as client:
         client.get(...)

I should also mention that I am working on a second test client that uses the ASGI. Again, depending upon where you store your state, you should have access to it within the same test.

**Comment by cannonba11** [comment]
@ahopkins Thanks for taking a look.
> 
> How and where are you storing your state? if it is on some data structures inside your single test, then pytest should keep it alive for you.
> 
It's about state in the app. Example: Let's say we have an app attribute `app.count` which gets incremented every time you hit the `/counter` route and let's say you have a `/display` route that displays the current value of the counter.  A single test that makes successive requests to those routes using `app.test_client` doesn't exhibit the behavior you'd expect from a long running app. While this may not be a typical use case (as you'd store state in an external resource like a db), I still think the test client should not tear down the app in between calls.
> With that said, I will factor out the run() and stop() calls so that they can be overridden. But this will mean that your tests will need to call them explicitly. Or, perhaps inside a contextmanager so it can be done something like the following:
> 
> ```
> with app.test_client as client:
>      client.get(...)
> ```
> 
Yes, the flask test_client does have a context manager, and even without using that, it's the same app across requests while inside a single test. So coming from flask, it caught me off guard.
For now I chose to use `pytest-sanic`.
> I should also mention that I am working on a second test client that uses the ASGI. Again, depending upon where you store your state, you should have access to it within the same test.
