### ISSUE TITLE
Standardize logging to 3+, impossible to do good log config

### ISSUE THREAD

**Issue by klausmyrseth** [huge-success/sanic#1474]
**Is your feature request related to a problem? Please describe.**
I am required to use frameworks otherwise integrated with standard 3+ logging to log when I deploy my application, and its quite frustrating when I cant do this as the application will never see production readiness.

The example code supplied in aditional context for instance works for other frameworks ive been using.
I am rewriting all my rest code to Sanic and met some interesting logging challenges.

Just need the logging streamlined so I can go into production with it ;)

**Describe the solution you'd like**
When server starts check if logging already set up, if its set up use the setup, if not you setup default setup like it does today.

**Additional context**
Sample config (config -> ConfigParser instance)
```
def configure_logger(config):
    log_level = getattr(logging, config['LOGGING']['level'], "INFO")
    cloud = config['LOGGING'].getboolean('cloud')
    logging_format = config.get('LOGGING','format', raw=True)
    logging.basicConfig(level=log_level, format=logging_format)
    if cloud:
        import google.cloud.logging
        client = google.cloud.logging.Client()
        client.setup_logging()
```

**Comment by ahopkins** [comment]
👍 No stupidity. Glad you figured it out.
