### ISSUE TITLE
Consider allowing negative int and number types

### ISSUE THREAD

**Issue by endafarrell** [huge-success/sanic#1480]
**Is your feature request related to a problem? Please describe.**
I would like to be able to be able to have negative ``number`` and ``int`` in routes: specifically for latitude and longitudes.

**Describe the solution you'd like**
A change to the https://github.com/huge-success/sanic/blob/master/sanic/router.py#L18-L29 regex to allow for negative numbers. Something like:

```:python
REGEX_TYPES = {
    "string": (str, r"[^/]+"),
    "int": (int, r"-?\d+"),
    "number": (float, r"-?[0-9\\.]+"),
    "alpha": (str, r"[A-Za-z]+"),
    "path": (str, r"[^/].*?"),
    "uuid": (
        uuid.UUID,
        r"[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-"
        r"[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}",
    ),
}
```

**Comment by sjsadowski** [comment]
I'm closing as I merged your PR this morning
