### ISSUE TITLE
Websocket handshake error when use nginx as reverse proxy server

### ISSUE THREAD

**Issue by baojiweicn** [huge-success/sanic#1494]
I use sanic==18.12.0 and websockets==6.0, and create a websocket server. When I connect the it without any proxy, it plays good. But when I try to use nginx as reverse proxy server, the connect throw out an error. 

![image](https://user-images.githubusercontent.com/26058270/53077473-08443900-352d-11e9-93ae-01c5582cb591.png)

Nginx config :
![image](https://user-images.githubusercontent.com/26058270/53077525-214cea00-352d-11e9-99cb-65ab68f3085a.png)

It seems that the "upgrade" proxy header not function correct in websockets.

[It sounds like this issue](https://github.com/aaugustin/websockets/issues/331)

**Comment by baojiweicn** [comment]
Fine, finally I find it's the nginx config error：the config should like this:
proxy_set_header Upgrade "websocket";

**Comment by andreymal** [comment]
This is strange, this config works good for me

```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
include proxy_params;
```
