### ISSUE TITLE
Blueprints for Class Views

### ISSUE THREAD

**Issue by gtmanfred** [huge-success/sanic#1495]
**Is your feature request related to a problem? Please describe.**
It would be really nice to be able to define class based views as Blueprints.

**Describe the solution you'd like**
My goal would be to be able to write a class that describes my blueprint, and then just be able to register the blueprint after the fact, instead of having to use Decorators.

https://github.com/gtmanfred/spmapi/blob/61dc8720b9bd118234ded7c47135dff139d5a8d8/spmapi/handlers/v1/formulas.py

I would love to be able to redefine the above blueprint like this

    class Formulas(sanic.Blueprint):

        uri = '/formulas'
        version = 1
    
        def get(self):
            ...
    
        def post(self):
            ...

**Additional context**

This would really allow me to build a pluggable web framework around sanic, in a similar way that I am doing in flask.

https://github.com/gtmanfred/plugins/blob/master/triagesched/triagesched/app.py#L32-L41
https://github.com/gtmanfred/plugins/blob/master/triagesched/triagesched/app.py#L106

**Comment by vltr** [comment]
@gtmanfred thanks for your insights! I know `Blueprints` have the possibility to add the `version` keyword, but, despite that, the functionality you want wouldn't be the same as using a [Class-Based View](https://sanic.readthedocs.io/en/latest/sanic/class_based_views.html)?

**Comment by gtmanfred** [comment]
It might, i could build the extra version logic into the path to the file that I am reading, and use the filesystem.

I thought the view was using the app definition in it for some reason, sorry about that.

Let me see if it fits my need.

**Comment by vltr** [comment]
@gtmanfred no need to sorry :wink: if you need any help, please let us know (or you can also join our [community forums](https://community.sanicframework.org)).

**Comment by gtmanfred** [comment]
:+1:

**Comment by ashleysommer** [comment]
@gtmanfred 
If you haven't already, check out [SanicPluginsFramework](https://github.com/ashleysommer/sanicpluginsframework). _N.B. I am the project author._
It has an object class called `SanicPlugin` that is similar to a Sanic `Blueprint`, but with some extra functionality. And it can be registered on any app, like you mentioned.
It doesn't do exactly what you want it to do, but it is a start.

Fun fact, I built [SanicPluginsFramework](https://github.com/ashleysommer/sanicpluginsframework) to be the basis of building a fully pluggable web framework around Sanic, exactly as you describe.

**Comment by sjsadowski** [comment]
Looks like we've come to a decent resolution here - closing
