### ISSUE TITLE
Intermittent tox failures with TravisCI builds

### ISSUE THREAD

**Issue by sjsadowski** [huge-success/sanic#1508]
tox is inconsistently failing in our build process - need to identify why and possibly open issue with Travis if the problem is not our own.

**Comment by c-goosen** [comment]
Any more info to share?

Logs?

**Comment by sjsadowski** [comment]
Just click on the travis builds in any of the PRs and look through the logs.

**Comment by vltr** [comment]
@sjsadowski I was having this issue in my machine. I took out `pytest-sugar` (we don't need it to run the tests) and the pinned version of `pytest` out of `tox.ini` and everything went smooth in my machine, no more random `pytest` fixtures errors in `py35-no-ext` for me. I'm preparing a PR that will address this too :wink:

**Comment by sjsadowski** [comment]
Closing for now - I think this was fixed with the cleanup @harshanarayana
