### ISSUE TITLE
Would you interested on tomato-bot for free?

### ISSUE THREAD

**Issue by moshe** [huge-success/sanic#1521]
Hey,
My name is Moshe and I've built [Tomato bot](https://tomato-bot.com) - A GitHub bot that comment tests failures and lint issues directly on your pull requests.
The bot built with Sanic and I wanted to ask if you interested that I will do the integration for you? (generate xml reports and send them to the backend)
you can see examples here:
[Flake annotation](https://github.com/tomato-bot/tomato-examples/pull/3/files#diff-698d61c446f510d0f7425c2c179f1596R40):
![image](https://user-images.githubusercontent.com/7490448/54492361-8b5b7380-48ce-11e9-9589-319d45ee4d21.png)

[Pytest annotation](https://github.com/tomato-bot/tomato-examples/pull/3/files#diff-698d61c446f510d0f7425c2c179f1596R13):
![image](https://user-images.githubusercontent.com/7490448/54492371-a29a6100-48ce-11e9-8ed7-4982e427f8fb.png)

**Comment by sjsadowski** [comment]
Hi @moshe - I'm not sure this would be a good fit for our CI pipeline BUT we are always happy to see projects that use sanic! Thank you for your generous offer!
