### ISSUE TITLE
Missing function handle_exit for SIGTERM handling

### ISSUE THREAD

**Issue by benjolitz** [huge-success/sanic#1523]
**Describe the bug**
There is a handle_quit method as of latest master but there is no handle_exit defined here or elsewhere in the repository (at least to matching the string query "handle_exit"). This affects only the gunicorn served workers.

**Code snippet**

https://github.com/huge-success/sanic/blob/391fcdc83d54c590066837f36e973ba42c72724f/sanic/worker.py#L196-L198

**Expected behavior**
SIGTERM handling works for gunicorn workers instead of referencing a non-existent method

Suggest that this is a typo and the intent is to be `self.handle_quit` instead of `self.handle_exit`

**Comment by harshanarayana** [comment]
@benjolitz the `self.handle_exit` here comes from the base worker `Worker` class. Which does a much simpler operation of `handle_quit` 

```python
def handle_exit(self, sig, frame):
    self.alive = False
```

Is this causing any issues for you at the runtime?

**Comment by benjolitz** [comment]
I found a different problem in my implementation. You’re right - not a bug

Ben
