### ISSUE TITLE
Publish 19.3 release to PyPI

### ISSUE THREAD

**Issue by whyboris** [huge-success/sanic#1524]
Thank you for the release 3 days ago!

https://github.com/huge-success/sanic/releases/tag/19.3

It's missing from PyPI at the moment:

https://pypi.org/project/sanic/#history

Please publish it at your convenience 🙇 

Keep up the awesome work ❤️

**Comment by harshanarayana** [comment]
I think @sjsadowski is already looking into it.

**Comment by sjsadowski** [comment]
Yeah we have a credentialing issue which we are working to resolve. I'll leave this open until 19.3 gets pushed.

**Comment by ahopkins** [comment]
See #1529
