### ISSUE TITLE
docs: part of request_data is out of date

### ISSUE THREAD

**Issue by veelion** [huge-success/sanic#1526]
**Describe the bug**
https://sanic.readthedocs.io/en/latest/sanic/request_data.html

`query_args` does not exist in Sanic 18.12, description about it in the doc should be removed.

the same issue also occurs on "Changing the default parsing rules of the queryset" in the docs, `request` does not has `get_args()` method.

**Comment by harshanarayana** [comment]
@veelion It's added as part of Sanic 19.3 release and hence the update in the Document. The new version will be made available in PyPi soon.
