### ISSUE TITLE
abort() not working

### ISSUE THREAD

**Issue by StVl** [huge-success/sanic#1533]
Hello!

I want to handle the errors of my application using my own messages and error codes.

For this, I created a variable, for example:

`example_error = [" example msg, ", 10000]`

and wrote a function, like this:

`async def get_error (msg, code):
    return abort (code, msg) `

when I call it, I get the following as a reply:

Еrror: example msg

And where is my error `code?`

Moreover, if I want to simply return the answer in the form of json, using the method
`async def get_error (msg, code):
    return json ({code, msg}) `

Nothing happens at all
Totally.

Ok, I'm ready to handle errors using the abort method

Can you please tell me how to return my error codes?
Sewing them in the msg answer seems to me not at all sensible

Thank!

**Comment by harshanarayana** [comment]
@StVl Can you please elaborate a bit more on the format you are expecting the Output in? Are you expecting a JSON output with Status code embedded into it? Or JSON with status code in header? 

It would be useful if you can add a small snippet of your code as well so that we can get a bit more context.

**Comment by StVl** [comment]
@harshanarayana i'm so sorry. I had tried returned error codes, which is not supported by http/1.1, My local error codes. And i hoped see that in my browser, not in headers. That's my mistake, closing  issue

**Comment by harshanarayana** [comment]
@StVl  No worries 😄 Glad you got the issue sorted out
