### ISSUE TITLE
@app.exception(ServerError) not work

### ISSUE THREAD

**Issue by nemochin** [huge-success/sanic#1540]
I want use sanic api like flask,handle 500 error like this:
browser return ：
![image](https://user-images.githubusercontent.com/13851088/55080334-fa0fac80-50d8-11e9-81f1-768f6b38461f.png)
background retrun：
![image](https://user-images.githubusercontent.com/13851088/55080461-29261e00-50d9-11e9-95e7-7abbbbc5bae6.png)
 but sadly 
if I use @app.exception(ServerError)
browser return this,it seems that the decorator not work:
![image](https://user-images.githubusercontent.com/13851088/55080695-828e4d00-50d9-11e9-8079-545656dd7294.png)
if I use app.error_handler.add
background return like this，it seems that it not log any detail internal error：
![image](https://user-images.githubusercontent.com/13851088/55081083-2aa41600-50da-11e9-9bca-eb0e44dad533.png)

Please tell me why ，and how return my hopes;
codes below:

```# -*- coding: utf-8 -*-

from sanic import Sanic
from sanic.response import json
from sanic.exceptions import InvalidUsage, Unauthorized, Forbidden, NotFound, MethodNotSupported, ServerError

app = Sanic()


def _make_resp(rsdict, status_code=200):
    response = json(rsdict, status=status_code)
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'OPTIONS,HEAD,GET,POST'
    response.headers['Access-Control-Allow-Headers'] = 'x-requested-with,content-type'
    return response


def _raise_error_resp(errorcode: int, errormessage: str):
    rsdict = {}
    rsdict['Error'] = errorcode
    rsdict['Message'] = errormessage
    response = _make_resp(rsdict, errorcode)
    return response


@app.exception(ServerError)
def ignore_500s(request, exception):
    return _raise_error_resp(500, "ServerError")


"""
async def server_error_handler(request, exception):
    return _raise_error_resp(500, "ServerError")
app.error_handler.add(Exception, server_error_handler)
"""


@app.route('/')
async def i_am_ready_to_die(request):
    a = 2 // 0


if __name__ == "__main__":
    app.run(port=8000)
```

**Comment by andreymal** [comment]
This is not a `ServerError`, this is `ZeroDivisionError`. For unexpected exception types [use a custom error handler](https://sanic.readthedocs.io/en/latest/sanic/exceptions.html#handling-exceptions)

**Comment by nemochin** [comment]
> This is not a `ServerError`, this is `ZeroDivisionError`. For unexpected exception types [use a custom error handler](https://sanic.readthedocs.io/en/latest/sanic/exceptions.html#handling-exceptions)
ZeroDivisionError  occurs in Internal Server，is it a 500 error?

**Comment by sjsadowski** [comment]
No, the ServerError is triggered by the ZeroDivisionError, which you're not catching.

The following works:
```
@app.route('/')
async def i_am_ready_to_die(request):
    try:
        a = 2 // 0
    except ZeroDivisionError as zde:
        raise ServerError("Divide By Zero")
```

curl returns:
**testing]$ curl -i localhost:8000**
```HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Keep-Alive: 5
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,HEAD,GET,POST
Access-Control-Allow-Headers: x-requested-with,content-type
Content-Length: 37
Content-Type: application/json

{"Error":500,"Message":"ServerError"}
```

**Comment by nemochin** [comment]
> No, the ServerError is triggered by the ZeroDivisionError, which you're not catching.
> 
> The following works:
> 
> ```
> @app.route('/')
> async def i_am_ready_to_die(request):
>     try:
>         a = 2 // 0
>     except ZeroDivisionError as zde:
>         raise ServerError("Divide By Zero")
> ```
> curl returns:
> **testing]$ curl -i localhost:8000**
> 
> ```
> Connection: keep-alive
> Keep-Alive: 5
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: OPTIONS,HEAD,GET,POST
> Access-Control-Allow-Headers: x-requested-with,content-type
> Content-Length: 37
> Content-Type: application/json
> 
> {"Error":500,"Message":"ServerError"}
> ```

thank you very much
