### ISSUE TITLE
request.json parsing issue

### ISSUE THREAD

**Issue by cnk113** [huge-success/sanic#1552]
I'm trying to read in a JSON through curl and the request.json gives me None. I've been looking through the doc and request.json should return what I want, but it doesn't. Any ideas?

```
from sanic import Sanic, response

app = Sanic()

@app.route('/key-value-store/<key>', methods=['GET','PUT','DELETE'])
async def key_handler(request,key):
    kvs = {}
    if request.method == 'PUT':
        inp = request.json
        print(inp)

app.run(debug=True, host='0.0.0.0', port=8082)
```

Command I'm running:

`
curl --request PUT --header "Content-Type: application/json" --write-out "%{http_code}\n"--data '{"value": "Distributed Systems"}' http://127.0.0.1:8082/key-value-store/course1000`

 - OS: ubuntu 18.04
 - Version v19.03.1

**Comment by andreymal** [comment]
You forgot to add a space between `"%{http_code}\n"` and `--data`

**Comment by cnk113** [comment]
Yeah that fixes it, my bad.
