### ISSUE TITLE
2 failed tests when tox is not used (missing fixture "benchmark")

### ISSUE THREAD

**Issue by andreymal** [huge-success/sanic#1557]
`pytest-benchmark` is not present in `tests_require`, so there are 2 failed tests in `tests/benchmark/test_route_resolution_benchmark.py` when tox is not used.

This requirement is present in `tox.ini` so tox and Travis CI are working fine.

(I don't know what's a better fix — disable the benchmark tests or add `pytest-benchmark` to `tests_require`, so I didn't create a PR)

**Comment by ahopkins** [comment]
add to tests_require

**Comment by andreymal** [comment]
Ok
