### ISSUE TITLE
Documentation required: building on fedora 28+

### ISSUE THREAD

**Issue by sjsadowski** [huge-success/sanic#1582]
Documentation needs to be updated for this corner case I discovered:

On clean installs of fedora 28, 29, and 30 (verified so far, could impact earlier versions) ujson fails when 'redhat-rpm-config' package is not installed.

This will be deprecated if/when we move on from ujson, but for now is obnoxious.

**Comment by yunstanford** [comment]
@sjsadowski can you take this one ?

**Comment by harshanarayana** [comment]
@yunstanford @sjsadowski I am working on the documentation update. WIll have the PR up by tomorrow.

**Comment by sjsadowski** [comment]
I was planning on handling it this week, but I'll hold off as @harshanarayana has claimed it.
