### ISSUE TITLE
A mysterious issue with Cython, sanic 19.3.1

### ISSUE THREAD

**Issue by heshiming** [huge-success/sanic#1601]
I'm seeing a mysterious exception in `_build_endpoint_name` of `app.py`. It occurs only when the app server module is compiled using Cython. It happens to sanic 19.3.1 but not 18.12.0 (or below).

Here is a minimal example to replicate this issue in the docker environment. First, in an empty folder, create `dockerfile` with the following contents:

    FROM python:3.7-stretch
    RUN pip install sanic cython gunicorn

Then, in the same folder, create a very simple server `app.py` like this:

    from sanic import Sanic, response

    app = Sanic()

    @app.route('/')
    async def root(request):
        return response.text('Hello')

Build the docker image:

    $ docker build --rm -f dockerfile -t sanic-test ./

Launch and go inside the container:

    $ docker run --rm --name sanic-test -it -v `pwd`:/app -w="/app" -p 127.0.0.1:5000:5000/tcp sanic-test bash

Run the following command to get `app.py` compiled:

    cython app.py -3
    gcc -shared -pthread `python3-config --includes` -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -o app.cpython-37m-x86_64-linux-gnu.so app.c

Now launch the compiled module using `gunicorn`:

    $ gunicorn app:app --bind 0.0.0.0:5000 --worker-class sanic.worker.GunicornWorker
    [2019-06-05 03:32:57 +0000] [7] [INFO] Starting gunicorn 19.9.0
    [2019-06-05 03:32:57 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
    [2019-06-05 03:32:57 +0000] [7] [INFO] Using worker: sanic.worker.GunicornWorker
    [2019-06-05 03:32:57 +0000] [10] [INFO] Booting worker with pid: 10

The docker container is set up with external port mapping. So on your host machine, you can do:

    $ curl http://localhost:5000

Which generates:

    [2019-06-05 03:32:59 +0000] [10] [ERROR] Exception occurred while handling uri: 'http://localhost:5000/'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 906, in handle_request
        handler.__name__
      File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 1355, in _build_endpoint_name
        return ".".join(parts)
    TypeError: sequence item 0: expected str instance, NoneType found
    [2019-06-05 03:32:59 +0000] - (sanic.access)[INFO][172.17.0.1:55388]: GET http://localhost:5000/  500 144

Options to prevent this exception include:

1. removing `app.cpython-37m-x86_64-linux-gnu.so` and let it run in source code
2. downgrading sanic by changing the docker file line `RUN pip install sanic cython gunicorn` to `RUN pip install sanic==18.12.0 cython gunicorn`

And of course, the expected result is something like this:

    [2019-06-05 03:35:01 +0000] - (sanic.access)[INFO][172.17.0.1:55396]: GET http://localhost:5000/  200 5

A change in 19.3.1 must have triggered this issue. But due to the nature of Cython, it's probably very difficult to debug, especially considering the source code itself works without any problem. The corresponding part of sanic's `app.py` is trying to load the handlers' `__name__` attribute.

According to my previous experience, Cython has problems with `__file__`. A Cythonized module or script will not have `__file__` defined. But I have never seen a problem with `__name__`. Any idea how to debug such a problem?

**Comment by ahopkins** [comment]
Yikes, does seem like a tough one to debug. I guess the best way is to do it incrementally. Try with a very small class and mock out `_build_endpoint_name` and `handle_request` and see if Cython can build.

I am certainly no expert in Cython, but it does seem far-fetched to think that `__name__` is not implemented.

**Comment by jfyang2010** [comment]
I've just met the same problem with a simple example from the official site.

The error disappears when one provides a name parameter to the constructor as `Sanic("important_name")`. Hope it helps.

**Comment by harshanarayana** [comment]
```python
    def _build_endpoint_name(self, *parts):
        parts = [self.name, *parts]
        return ".".join(parts)
```

The default value for `name` is not provided by the constructor of `Sanic` is `None` this causes the `join` to fail. Opening a PR to address the same.
