### ISSUE TITLE
Getting url arguments from request object

### ISSUE THREAD

**Issue by Hesarn** [huge-success/sanic#1604]
I wanted to access url arguments captured in route, from `Request` object of sanic.

actually i wanted to access this captured data in request middleware and change the json body of request a little bit for all routes of my application, but as i inspected the code a little, i found out that there is no way that i can access those parsed values from request object(I know the path is present in the the request, but it's raw string and i need to parse it again, but i don't wanna do that).

Also i wanted to change the json body of request, but as  `json` attribute of `Request` object is a property, i can't do it(as i can change the `body` property manually, but it seems not good to me because `parsed_json` only loads once based on `body` attribute and its not safe to me)

Is there anyway to get something like this ?!

```python
from sanic import Sanic
from sanic.response import json


def hello(request, route_param):
    return json('hello')


def request_middleware(request):
    # I wanted something like this
    request.get_route_arg('route_param')
    request.json['key'] = 'value'

app = Sanic()
app.add_route(hello, '/hi/<route_param:int>', ['GET'])
app.middleware('request')(request_middleware)
app.run('localhost', port=8000)
```

**Comment by ahopkins** [comment]
The current router is not very flexible. :disappointed:  This is similar to #1373 

I am working on a potential alternative Router that I would like to introduce for Version 19.9 (it will not make it into the release later this month) that would allow for this. 

---

With that being said, the `request` object is just [a regular `dict`](https://github.com/huge-success/sanic/blob/master/sanic/request.py#L70), which means you can manipulate it.

```python
from sanic import Sanic
from sanic.response import json


app = Sanic()


@app.get("/<foo>")
def foobar(request, foo):
    return json({"foo": foo, "key": request["key"]})


@app.middleware("request")
def request_middleware(request):
    foo = request.match_info.get("foo")
    if foo == "foo":
        foo = "bar"
    request["key"] = foo


app.run(port=7777, debug=True)
```

And then...

```
$ curl localhost:7777/q  
{"foo":"q","key":"q"}

$ curl localhost:7777/foo
{"foo":"foo","key":"bar"}
```
