### ISSUE TITLE
Bug with parameters and type checking

### ISSUE THREAD

**Issue by Lagicrus** [huge-success/sanic#1606]
**Describe the bug**
When using the code below it results in a 404. I believe this is due to Sanic believing that the blueprint_id is a string rather than an int because when I then run the function without the route having a type specified for blueprint_id and edit_type it works fine

**Code snippet**
```python
from sanic import Blueprint
bp = Blueprint("blueprint_edit")

@bp.route("/api/edit/<blueprint_id:int>/<edit_type:str>", methods=["POST"])
async def post_api_edit_blueprint(request, blueprint_id: int, edit_type: str):
     pass
```

**Expected behaviour**
When I send a post request to that route  it is found and processed

**Environment (please complete the following information):**
 - OS: Docker Env (Windows host machine)
 - Version 19.03.1

**Comment by ahopkins** [comment]
I am not seeing the same behavior.

```python
from sanic import Blueprint, Sanic, response

app = Sanic(strict_slashes=True)

bp = Blueprint("blueprint_edit")


@bp.route("/api/edit/<blueprint_id:int>/<edit_type:string>", methods=["POST"])
async def post_api_edit_blueprint(request, blueprint_id: int, edit_type: str):
    return response.json(
        {"blueprint_id": blueprint_id, "edit_type": edit_type}
    )


app.blueprint(bp)


print(app.router.routes_all)
app.run(debug=True)
```

The printed routes are:

```python
{
    '/api/edit/<blueprint_id:int>/<edit_type:string>': Route(
        handler=<function post_api_edit_blueprint at 0x7f50aebae730>, 
        methods=frozenset({'POST'}), 
        pattern=re.compile('^/api/edit/(-?\\d+)/([^/]+)$'), 
        parameters=[
            Parameter(name='blueprint_id', cast=<class 'int'>),
            Parameter(name='edit_type', cast=<class 'str'>)
        ],
        name='blueprint_edit.post_api_edit_blueprint',
        uri='/api/edit/<blueprint_id:int>/<edit_type:string>'
    )
}
```

And, when I hit the endpoint:

```
$ curl -X POST localhost:8000/api/edit/1/foo
{"blueprint_id":1,"edit_type":"foo"}
```

The endpoint seems to be found, and the casting is done properly.

What am I missing?

**Comment by Lagicrus** [comment]
Thanks for testing it. Whilst I am not sure what is causing it I did spot a difference in the printed route when I checked that.
```py
{
    '/bacon/edit/<blueprint_id:int>/<edit_type:str>': Route(
        handler=<function,  post_api_edit_blueprint at 0x7fcaeace4d08>, 
        methods=frozenset({'POST'}), 
        pattern=re.compile('^/bacon/edit/(-?\\d+)/(str)$'), 
        parameters=[
            Parameter(name='blueprint_id', cast=<class 'int'>), 
            Parameter(name='edit_type', cast=<class 'str'>)
        ], 
        name='blueprint_edita.post_api_edit_blueprint', 
        uri='/bacon/edit/<blueprint_id:int>/<edit_type:str>'
     )
}
``` 
Where if you look at the pattern I have it as `/(str)$` whilst you have `/(^/]+)`

**Comment by Lagicrus** [comment]
Wait a second I just realised my mistake. I defined the type for `edit_type` as `str`, not `string` which you did. And after changing my test to be that it works.. 🤦‍♂️
I had assumed that it would have included Python's shorthand for string (str) to be allowed, not having to type out the long hand (string). 
Maybe that can be added or the docs for Request routing parameters can be updated to include a list of compatible types as it only shows of ints, numbers, and basic regex in the form of `[A-z]`

**Comment by ahopkins** [comment]
> I had assumed that it would have included Python's shorthand for string (str) to be allowed, not having to type out the long hand (string).

I agree with you 100%. I am working on a proposal for a replacement router (faster, more flexible, more efficient) that is also entirely backwards compatible with the current router. In that, I have addressed that "gotcha" and inconsistency between strings and integers. In the mean time... I'd be happy to review a PR to the docs if you would like to put one together.

**Comment by Lagicrus** [comment]
Added a PR to update docs over at https://github.com/huge-success/sanic/pull/1620
