### ISSUE TITLE
Custom default JSON Encoder / Decoder for request / response

### ISSUE THREAD

**Issue by likern** [huge-success/sanic#1609]
**Is your feature request related to a problem? Please describe.**
I'm working with Mongo database and returning Mongo results as HTTP response:

```
cursor = db.bots.find(filter={"user_id": user_id})
limit = 30

bots = await cursor.to_list(limit)
return response.json({"bots": bots}, status=200)
```

With default serialization of Mongo objects to JSON (internally in `response.json`) I get exception

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 36: invalid start byte

So I need **custom** JSON Encoder to be able to encode [**ObjectId** type](https://docs.mongodb.com/manual/reference/bson-types/#objectid) to string, like in [this answer](https://stackoverflow.com/a/16586277/966467).

[I've found](https://github.com/huge-success/sanic/pull/948) that it is possible to provide custom JSON encoder / decoder for `response.json() ` function:

```return sanic.response.json(response_data, dumps=pd.json.dumps)```
But with that approach I need to do that **for every request** to MongoDB. 

_I want to be able to configure custom JSON encoder / decoder **as default** so it will be automatically works internally with this standard code:_
`return response.json({"bots": bots}, status=200)` 

**Describe the solution you'd like**
Add ability to configure default JSON encoder / decoder which is used with standard `response.json({}, status=200)` function call

**Comment by ahopkins** [comment]
I don't see this as a feature we would add into the library directly, because, as you pointed out there is the dumps argument on response method. What I would suggest is creating a wrapper that calls with the argument that you want.

I'll try and provide you with a code snippet later when I'm at a computer.

**Comment by greentornado** [comment]
you can str(document['_id']) before return

**Comment by likern** [comment]
@greentornado @ahopkins Yes, this is suitable as quick solution. But the problem is in solution which is sustainable, especially for large code base.

This approach `str(document['_id'])`:
-  is working only on exact document
 - it relies on exact document structure (ObjectID type might be elsewhere) or requires to inspect document structure to find all other possible places where conversion is required
- doesn't scale with other BSON types, which also should be converted to JSON
- error-prone when multiple developers are working together - it is easy to forget to do that conversion (and get **500 Internal Error** as response)
 - and it is easy to forget to call wrapper, as @ahopkins suggested
 - it is not automatic
 - you always have to have that in mind, instead of writing one general solution and forget

I think approach similar to [axios interceptors](https://github.com/axios/axios#interceptors) or sanic middlewares is more sustainable. Hardly ever people use wrappers instead of middlewares.

**Comment by greentornado** [comment]
Yeah, `str()` is just my suggest.

in my case, I wrote a `prepare_document` func for this, called on each document when iterating over cursor

**Comment by harshanarayana** [comment]
@likern Did you try to override the default `sanic.response. json_dumps` ? If you do override this, you can change the default JSON dump behavior without having to pass is with every `json()` call.

**Comment by ahopkins** [comment]
When in doubt... mokneypatch :laughing: 

As far as using middleware, I do not see anything that would prevent you from doing so.

**Comment by ashleysommer** [comment]
@harshanarayana and @ahopkins are right. I have monkeypatched `sanic.response.json_dumps` in an application before, it works as expected.

**Comment by likern** [comment]
@ahopkins @ashleysommer @harshanarayana Could you, please, provide source code example with `JSONEncoder`?

```
class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return json.JSONEncoder.default(self, o)

json_encoder = JSONEncoder()
```

**Comment by likern** [comment]
I digged into a little bit. It looks like it's not possible to do that. Because of how default function arguments are evaluated.
Here is a screenshot where I successfully overwritten `json_dumps`, but it's not working.
Because `response.json` function already binded `dumps` parameter to built-in.

![Screenshot from 2019-06-25 19-53-24](https://user-images.githubusercontent.com/842306/60117572-f694cb80-9782-11e9-9a04-f07ac3b17f6f.png)

**Comment by ahopkins** [comment]
Something like this should work.

```python
from sanic import Sanic, response
import json

app = Sanic(__name__)


class ObjectId:
    pass


class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return json.JSONEncoder.default(self, o)


response.json_dumps = JSONEncoder()


@app.route("/")
async def foo(request):
    print(response.json_dumps)
    return response.json({"foo": "bar"})
```

**Comment by WegDamit** [comment]
Still an issue (for me) and the encoder and dumps monkeypatch  from above didn't work (for me).
And this is still a top search result, even if closed... 

I got it working with a middleware, with sends everything that is a list or dict as json encoded with the above JSONEncoder class:

Won't help much if the app has more sophicticated responses but for a plain REST API it works just fine...

```python
@app.middleware('response')
def rest_response_middleware(req, res):
    # more stuff not related to json ...
    # dump hack for dumping json with dates...
    if isinstance(res, dict) or isinstance(res, list):
        return HTTPResponse(
            plain_json.dumps(res, indent=2, cls=JSONEncoder),
            content_type='application/json', headers=headers
        )
    if isinstance(res, str):
        return HTTPResponse(
            res,
            content_type='application/text', headers=headers
        )
  # some more stuff.
```

**Comment by vgoklani** [comment]
<bump>
