### ISSUE TITLE
Adding Bandit security static analysis for CI/CD

### ISSUE THREAD

**Issue by c-goosen** [huge-success/sanic#1611]
**Is your feature request related to a problem? Please describe.**

Adding Bandit security static analysis for sanic code. Good to pick up on potential dangerous code added to project inadvertently. 

**Describe the solution you'd like**
Add bandit comparability and deal with false positives.

**Additional context**
Bandit: https://pypi.org/project/bandit/ && https://bandit.readthedocs.io/en/latest/

**Comment by c-goosen** [comment]
PR: https://github.com/huge-success/sanic/pull/1612

**Comment by yunstanford** [comment]
closed by https://github.com/huge-success/sanic/pull/1612
