### ISSUE TITLE
RFC: Enable Towncrier based change log support

### ISSUE THREAD

**Issue by harshanarayana** [huge-success/sanic#1631]
Enable usage of `towncrier` to generate and manage the release change logs automatically.

**Comment by andreymal** [comment]
Automatic changelogs are awful.

No automatics can make a good changelog, like this: https://docs.djangoproject.com/en/2.2/releases/2.0/

Or at least like this: https://websockets.readthedocs.io/en/stable/changelog.html

**Comment by harshanarayana** [comment]
@andreymal `towncrier` provides a mechanism whereby you can create a `.bugfix` `.feature` file in a specific directory with right markdown template and all it does is gather them and generate clean output with proper groupings. 

This in no way is a replacement to manual detailed change logs but this is better than having to sit and go over the commit to extract meaningful information to generate Changelogs during the release time,.
