### ISSUE TITLE
Start event loop and pass to App before App start

### ISSUE THREAD

**Issue by c-goosen** [huge-success/sanic#1639]
Hi.

Wondering if I can start a event loop and pass it to sanic.

Having issues with libraries that need an event loop and testing that library is working in a __init__.py or before server start.

Having issues with 2 event loops.

Thanks
Christo

**Comment by Tronic** [comment]
It uses asyncio get_event_loop() to get the current loop in app.run(). You can use set_event_loop() to choose your own.

**Comment by c-goosen** [comment]
Actually solved it with app.listener("before_server_start")
def before_server_start(app, loop):

**Comment by c-goosen** [comment]
Just need to pass event loop explicitly to libraries that do not handle it correctly. Some libraries are not using get_event_loop as sanic does properly.
