### ISSUE TITLE
Custom log not working in sanic

### ISSUE THREAD

**Issue by ZeeRoc** [huge-success/sanic#1644]
```
loggers={
        'sanic.root': {
            'handlers': ['sanic.root'],
            'level': logging.NOTSET,
            "encoding": "utf8"
        },
        'sanic.access': {
            'handlers': ['sanic.access'],
            'level': logging.NOTSET,
            "encoding": "utf8"
        },
        'sanic.error': {
            'handlers': ['sanic.error'],
            'level': logging.NOTSET,
            "encoding": "utf8"
        },
}
```

```
handlers={
        'sanic.root': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/root/log/server/service/root/root.log',
            'when': 'midnight',
            'interval': 1,
            'formatter': 'default',
            'level': logging.NOTSET,
        },
        'sanic.access': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/root/log/server/service/access/access.log',
            'when': 'midnight',
            'interval': 1,
            'formatter': 'default',
            'level': logging.NOTSET,
        },
        'sanic.error': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/root/log/server/service/error/error.log',
            'when': 'midnight',
            'interval': 1,
            'formatter': 'default',
            'level': logging.NOTSET,
        },
}
```
```dictConfig(logging_config)```

This is my config part , other logger is work , but 'sanic.access','sanic.error' is not work, It show on console, but not in file.

**Comment by ZeeRoc** [comment]
@yunstanford

**Comment by ZeeRoc** [comment]
@yunstanford

**Comment by yunstanford** [comment]
@ZeeRoc can you provide more details ? like how did you setup logging or a small piece of code for reproducing

**Comment by ZeeRoc** [comment]
I read documentation，It tell me logging config need set ‘sanic.access’, I was set，It show in console，but in my config，It should in file.

I need let 'sanic.access' log write in file,  How do i do?

**Comment by ZeeRoc** [comment]
I think , I use python logging , and use dictConfig config log, Then add 'sanic.access','sanic.error'.. in python logging , sanic log should write in file by logging config, but it show in console , not in file.

**Comment by ZeeRoc** [comment]
Logging config in first comment, Then i used it in code, like this `logging.info('This is my log')`, other log is work, all write in file , but 'sanic.access','sanic.error','sanic.root' still in console, not in file, I think it's not my mistake. or sanic log use python logging need special config？ @yunstanford

**Comment by skytoup** [comment]
```Python3
Sanic(log_config=your_logging_config)
```

**Comment by ZeeRoc** [comment]
> ```python
> Sanic(log_config=your_logging_config)
> ```

`app = Sanic(__name__, log_config=settings.logging_config)`

Like this ?

**Comment by skytoup** [comment]
> > ```python
> > Sanic(log_config=your_logging_config)
> > ```
> 
> `app = Sanic(__name__, log_config=settings.logging_config)`
> 
> Like this ?

yes
