### ISSUE TITLE
Allow nonstandard HTTP methods

### ISSUE THREAD

**Issue by notpushkin** [huge-success/sanic#1646]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement some WebDAV-specific methods, but I get the `sanic.exceptions.InvalidUsage: MKCOL is not a valid HTTP method.` error.

**Describe the solution you'd like**
Probably the best way would be to remove the method whitelist altogether. It can be left for the class-based views, though.

**Comment by harshanarayana** [comment]
@notpushkin  You can always override that parameter in your code before using the View. 

```python
from sanic import views

views.HTTP_METHODS = view.HTTP_METHODS + my_custom_method_array
```

**Comment by notpushkin** [comment]
@harshanarayana Nice workaround! However I still feel it could be done better. Perhaps a tiny helper function like `sanic.constants.register_http_methods(["MKCOL", "COPY", ...])`?

**Comment by ahopkins** [comment]
I am not sure that I think this is such a necessary feature that @harshanarayana workaround requires further support. Any time there is something non-standard going on, I think this is the place for either an extension, or a simple hack as presented here.
