### ISSUE TITLE
In ASGI, headers is output as body

### ISSUE THREAD

**Issue by skytoup** [huge-success/sanic#1653]
simple test code
```Python3
@app.get('')
async def test(request):
    return await file_stream(...)
```

The HTTP response will output twice headers.
One of them is in the headers (✅), the other time in the body (❎)

**Comment by ahopkins** [comment]
This is with the Gunicorn worker?

**Comment by skytoup** [comment]
I made a mistake. Is used in ASGI, not WSGI. It is use the uvicorn.

**Comment by loek17** [comment]
I got the same problem. When using ASGI and a Stream Response the headers are send twice. 

It happens because the `response.stream()` call at [L359](https://github.com/huge-success/sanic/blob/master/sanic/asgi.py#L359) will send the headers using the `protocol.push_data()` before is starts sending the body.

maybe ignoring the first call to `push_data` in the `MockProtocol` will fix this?

**Comment by dmachi** [comment]
I am also seeing this same issue.   I don't really know the ASGI protocol, but I quickly tested @loek17 's suggestion:

`    async def push_data(self, data: bytes) -> None:
        if self._first:
          self._first=False
          return

        if not self.is_complete:
            await self.transport.send(
                {"type": "http.response.body", "body": data, "more_body": True}
            )`

Skipping the first call to push_data() does seem to work, though I can't say if it causes any other issues. Would be great to get this fixed soon!  Thanks.

**Comment by ahopkins** [comment]
I am looking into this.

**Comment by Tronic** [comment]
@ahopkins Any updates on this?

**Comment by ashleysommer** [comment]
Weird, I've been using Sanic in ASGI-mode with Uvicorn for the last 3 weeks in production at work, and I never noticed this issue. I'm glad its now getting fixed, (thanks @ahopkins!) but I'm a bit confused why I never knew it was an issue and why it never adversely affected my deployments.

**Comment by ahopkins** [comment]
It was related _ONLY_ to streaming responses. So if you didn't have any streams, you would not have encountered this.

**Comment by ashleysommer** [comment]
OK.. turns out the only apps I have running that use streaming responses are still on Sanic 19.6 and use Gunicorn, so not ASGI.
