### ISSUE TITLE
requests_count may be wrong

### ISSUE THREAD

**Issue by froginwell** [huge-success/sanic#1658]
# sanic/server.py

```python
    def data_received(self, data):  # line 254
        # some code 

        # requests count line 268
        self.state["requests_count"] = self.state["requests_count"] + 1

        # some code
```

data_received may be called many times in one http request. What's the meaning of requests_count?Does it refer to the count of data_received or the http request?

**Comment by yunstanford** [comment]
If I recall correctly, it’s not real “request count”, it’s just used for hooking up with gunicorn max_requests, which will be used for recycling workers in case of memory leak.
