### ISSUE TITLE
App must be running before you can run middleware on Docker

### ISSUE THREAD

**Issue by jkjunior** [huge-success/sanic#1659]
I have a Sanic-GraphQL app and I'm trying to run it into a Docker Container.

But i'm having this issue when my app receives any request:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 885, in handle_request
    response = await self._run_request_middleware(request)
  File "/usr/local/lib/python3.7/site-packages/spf/framework.py", line 533, in _run_request_middleware
    "App must be running before you can run middleware!"
AssertionError: App must be running before you can run middleware!`

> Here is my Dockerfile:
![image](https://user-images.githubusercontent.com/13039118/63058940-71957b00-bec4-11e9-92fa-fcbd2f780db5.png)

> Here is my run.py:
![image](https://user-images.githubusercontent.com/13039118/63059065-c638f600-bec4-11e9-9131-bd7117b50ded.png)

> Here is my routes.py:
![image](https://user-images.githubusercontent.com/13039118/63059031-a86b9100-bec4-11e9-8ac1-769031088aaf.png)

I don't have this issue running outside from a Docker Container.

Thanks to advance!

**Comment by jkjunior** [comment]
Solved by installing all libs again from requirements.txt. It should warn that was a missing lib problem.

**Comment by frankhorv** [comment]
> 
> 
> Solved by installing all libs again from requirements.txt. It should warn that was a missing lib problem.

I have the same issue here.
What do you mean "installing all libs again from requirements.txt"?
Can you paste your dockerfile please?
