### ISSUE TITLE
Having trouble installing Sanic on ubuntu, it's stuck on "Running setup.py install for uvloop ... \"

### ISSUE THREAD

**Issue by ansonfoong** [huge-success/sanic#1660]
I'm on Ubuntu, just upgraded to latest version:

`Requirement already satisfied: requests==2.* in /usr/lib/python3/dist-packages (from requests-async==0.5.0->sanic)
Requirement already satisfied: httpcore==0.3.* in /usr/local/lib/python3.6/dist-packages (from requests-async==0.5.0->sanic)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: h11==0.8.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: rfc3986==1.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.6/dist-packages (from h2==3.*->httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: hpack<4,>=2.3 in /usr/local/lib/python3.6/dist-packages (from h2==3.*->httpcore==0.3.*->requests-async==0.5.0->sanic)
Building wheels for collected packages: uvloop
  Running setup.py bdist_wheel for uvloop ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8d69ppx4/uvloop/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpcj99tlkzpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6`

Above is my error output, I'm not sure why it's stuck on uvloop. I've also tried using "SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip3 install sanic" and it still won't work. I'm getting annoyed because it's stuck on uvloop

**Comment by sjsadowski** [comment]
Looks like permissions. Are you installing inside a virtualenv using virtualenv or pipenv?

If not, it's trying to build to your system python lib path, and without running as root or elevated with sudo, it will probably fail.

**Comment by ansonfoong** [comment]
> Looks like permissions. Are you installing inside a virtualenv using virtualenv or pipenv?
> 
> If not, it's trying to build to your system python lib path, and without running as root or elevated with sudo, it will probably fail.

No I'm not use a virtualenv or pipenv. I just tried "sudo pip3 install sanic" and the same thing happens again, I'm also logged in as root too:

`Collecting sanic
  Using cached https://files.pythonhosted.org/packages/13/89/351f12a0f46a68ba9507813f7373b6440e02acc5057ff93744edcf1abf3c/sanic-19.6.2-py3-none-any.whl
Requirement already satisfied: httptools>=0.0.10 in /usr/local/lib/python3.6/dist-packages (from sanic)
Collecting uvloop>=0.5.3; sys_platform != "win32" and implementation_name == "cpython" (from sanic)
  Using cached https://files.pythonhosted.org/packages/e3/15/dc3276384f4363015d7c72282f37066bae26c77f99158f66c9058ac167cf/uvloop-0.13.0.tar.gz
Requirement already satisfied: ujson>=1.35; sys_platform != "win32" and implementation_name == "cpython" in /usr/local/lib/python3.6/dist-packages (from sanic)
Requirement already satisfied: websockets<7.0,>=6.0 in /usr/local/lib/python3.6/dist-packages (from sanic)
Requirement already satisfied: aiofiles>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from sanic)
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/local/lib/python3.6/dist-packages (from sanic)
Requirement already satisfied: requests-async==0.5.0 in /usr/local/lib/python3.6/dist-packages (from sanic)
Requirement already satisfied: requests==2.* in /usr/lib/python3/dist-packages (from requests-async==0.5.0->sanic)
Requirement already satisfied: httpcore==0.3.* in /usr/local/lib/python3.6/dist-packages (from requests-async==0.5.0->sanic)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: rfc3986==1.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: h11==0.8.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.6/dist-packages (from httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: hpack<4,>=2.3 in /usr/local/lib/python3.6/dist-packages (from h2==3.*->httpcore==0.3.*->requests-async==0.5.0->sanic)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.6/dist-packages (from h2==3.*->httpcore==0.3.*->requests-async==0.5.0->sanic)
Building wheels for collected packages: uvloop
  Running setup.py bdist_wheel for uvloop ... /`

**Comment by sjsadowski** [comment]
So I went through with vagrant and stood up a clean 19.04 instance and found it does stall for sometime the first time it builds uvloop, but eventually completes. It looks like it is hanging but it is not. Took about 2 minutes to complete. I would suggest running the install like this:

```pip3 uninstall uvloop
pip3 install sanic --no-cache-dir -vv```

the --no-cache-dir will force it to ignore any cached items and the -vv will give you extra output to evaluate where it breaks. If it is still breaking in uvloop it may need to be reported upstream to the uvloop project.

**Comment by ahopkins** [comment]
Installing `uvloop` can take some time. This is one reason I like to run Sanic inside docker, and just mount my source directory as a volume during development (with either `docker-compose`, or K8S via `minikube`).

One thing that can also help is using [a base image](https://hub.docker.com/r/sanicframework/sanic) that already has `uvloop` installed..

**Comment by ahopkins** [comment]
Closing. If problem still persists please let us know.
