### ISSUE TITLE
[Documentation] Invalid Link to CHANGELOG.md in README.rst

### ISSUE THREAD

**Issue by snguyenthanh** [huge-success/sanic#1664]
The link to `CHANGELOG` in [README.rst](https://github.com/huge-success/sanic/blob/master/README.rst) refers to a non-existing `CHANGELOG.md` page.

The link should point to`CHANGELOG.rst` instead.

**Comment by harshanarayana** [comment]
@snguyenthanh You are right. Seems like I broke that link as part of #1632 

Would you be interested in opening a PR?

**Comment by snguyenthanh** [comment]
> Would you be interested in opening a PR?

Sure 👍
