### ISSUE TITLE
Expired SSL certificate for https://community.sanicframework.org/

### ISSUE THREAD

**Issue by snguyenthanh** [huge-success/sanic#1679]
Upon opening https://community.sanicframework.org, my browser shows that the SSL certificate of the website has expired, and thus accessing the website is forbidden:
```
NET::ERR_CERT_DATE_INVALID
Subject: community.sanicframework.org

Issuer: Let's Encrypt Authority X3

Expires on: Sep 15, 2019

Current date: Sep 17, 2019
```

**Comment by yunstanford** [comment]
^ @ahopkins do you mind take a look ?

**Comment by Tronic** [comment]
This can be closed (cert has been fixed).
