### ISSUE TITLE
Sanic masking ImportErrors inside the app.

### ISSUE THREAD

**Issue by wapiflapi** [huge-success/sanic#1683]
**Describe the bug**

Sanic prevents efficient debugging during development by masking some `ImportError`s occur insidei the app. 

```
$ python -m sanic my.app --debug
No module named None found.
  Example File: project/sanic_server.py -> app
  Example Module: project.sanic_server.app
```
Note: The import error itself is in no way sanic's fault: it is an error in the app. But the debugging / investigating is being hindered by Sanic masking the bug.

If this is considered a feature request and not a bug I'll be happy to update the issue accordingly.

**Code snippet**
Sanic's `__main__.py` basically:"

```python
if __name__ == "__main__":
   ...
    try:
        ...
        module = import_module(module_name)
        ...
    except ImportError as e:
        logger.error(
            "No module named {} found.\n"
            "  Example File: project/sanic_server.py -> app\n"
            "  Example Module: project.sanic_server.app".format(e.name)
        )
...
```

**Expected behavior**
I expect something like:

```diff
 if __name__ == "__main__":
    ...
     try:
         ...
         module = import_module(module_name)
         ...
     except ImportError as e:
+        # if args.debug:
+        #     logger.exception(e)
         logger.error(
             "No module named {} found.\n"
             "  Example File: project/sanic_server.py -> app\n"
             "  Example Module: project.sanic_server.app".format(e.name)
         )
 ...
```

**Environment (please complete the following information):**
 - This behavior is present on master

**Additional context**
I'm not sure if always displaying the traceback in debug is the right solution, maybe there is a simple way to detect the problem lies with the app (and not mask the exception in that case) or if it is expected (and have the custom, friendlier, message in that case).

**Comment by abuckenheimer** [comment]
TBH I didn't even know sanic had a `__main__.py` file, this looks a bit old and I wouldn't suggest using it, I'd expect you get better results by writing your own main as described in the (docs)[https://sanic.readthedocs.io/en/latest/sanic/getting_started.html#create-a-file-called-main-py]. How did you stumble upon the `__main__.py` functionality?

**Comment by wapiflapi** [comment]
That's an excellent question. I feel like I've always used it like this. :thinking: 

So i went back and checked the README's history in git and it does not look like this was ever present. So probably I didn't pick it up from there. Maybe it used to be the way flask was used and I picked it up there. Honestly I don't know.

I guess my fault for using undocumented features :-) I'll roll my own main as you suggest. (Though I do like the idea of having a consistent entry point and cli interface across multiple apps.)

Feel free to close this if it's not considered a bug. (But maybe consider adding a message somewhere that sanic is not supposed to be used like this?)  I would also be fine with offering a PR to fix this specific issue in the existing main if you would like that.

**Comment by abuckenheimer** [comment]
not exactly sure what I'd expect to see out of the `__main__.py` but would be open to review any PRs in that area. My guess is it be something in these three options
1. delete `__main__.py`
2. `print("go to docs...")` and exit
3. trivial example server (`examples/simple_server.py` esq)

**Comment by Tronic** [comment]
I find `python -m sanic my.app` a much cleaner approach, as it keeps the app definition separate of how the server is run. Using `if __name__ == "__main__": app.run(some args)` is tediuous clutter in single-file minimal apps, and usually not appropriate for larger applications either, as it will not be used by ASGI mode anyway. Sanic's `__main__` probably should be updated (with more command line args etc) rather than obsoleted.

**Comment by wapiflapi** [comment]
I finally found where I read about this way of starting sanic @abuckenheimer 

In https://sanic.readthedocs.io/en/latest/sanic/deploying.html it is suggested under "Running via command": 
> `python -m sanic server.app --host=0.0.0.0 --port=1337 --workers=4`

So it looks like this **is** in fact a documented feature.

**Comment by ahopkins** [comment]
Leaving this one open for potential thought and discussion on @Tronic suggestion.
