### ISSUE TITLE
Improve documentation in *Accessing values using `get` and `getlist`*

### ISSUE THREAD

**Issue by nitipit** [huge-success/sanic#1704]
**Is your feature request related to a problem? Please describe.**
Documentation here should be improved:
https://sanic.readthedocs.io/en/latest/sanic/request_data.html#accessing-values-using-get-and-getlist
It isn't clear how to use `get` and `getlist`

**Describe the solution you'd like**
Change
> The request properties which return a dictionary actually return a subclass of dict called RequestParameters.

To
> `request.args` which return a dictionary actually return a subclass of dict called RequestParameters.

**Comment by harshanarayana** [comment]
@nitipit Would it be possible for you to open PR for the suggested change? If you are pre-occupied with something, I will merge this with one of my other PRs.

**Comment by nitipit** [comment]
:+1:
