### ISSUE TITLE
Start Initial Support for Python3.8

### ISSUE THREAD

**Issue by harshanarayana** [huge-success/sanic#1709]
# Description 
Considering [Python 3.8.0](https://www.python.org/downloads/release/python-380/) has been out for a while we can start adding initial support for the Python 3.8 dependencies in the CI/CD pipelines so that we can get a picture of what might break and if there are any early changes we can do to start supporting newer python versions. 

@huge-success/sanic-core-devs  I Will open a PR to include the dependencies in travis and tox setup so that we can run the tests across those versions to start with

**Comment by seemethere** [comment]
SGTM, I'm wondering if there's a way that we can add a `python-nightly` to the matrix that doesn't actually block PR merges

**Comment by harshanarayana** [comment]
@seemethere I like the idea. But we should probably restrict the nightly builds to the `travis` part and not for the `tox` env so that we don't break your test mechanisms. 

Btw, `uvloop` is flaky with python 3.8. Doesn't seem to get installed. There is an open issue that I fond. I think we can alter the `uvloop` requirements to include python version check and add it only for version < 3.8?

**Comment by seemethere** [comment]
Related issue for `uvloop` installation failure: https://github.com/MagicStack/uvloop/issues/277

**Comment by bphillips-exos** [comment]
FYI. When I upgraded to Python 3.8, I started getting this error while running Python SocketIO + Sanic in a `multiprocessing.Process`. Just going to stick with 3.7 for now

> AttributeError: Can't pickle local object 'Sanic.enable_websocket.\<locals\>.cancel_websocket_tasks'

**Comment by Tronic** [comment]
So, depend on `uvloop>=0.14` now that it is out and working on 3.8?

**Comment by harshanarayana** [comment]
@Tronic I saw the `uvloop` notification earlier today about 3.8 support. I guess time to see if we can bump to the latest version and see if we crash the universe or save it.

**Comment by AndrewBurdyug** [comment]
Hi, guys! 

Will be really appreciated if you releasing a new version with supporting python 3.8, 
archlinux already has python 3.8. in latest upgrades, I think other distributives will be has python 3.8. in their updates soon, so the people start you bothering about new release soon too, I'm the first =)

**Comment by ahopkins** [comment]
Closing in favor of #1752
