### ISSUE TITLE
Use httpx instead of requests-async

### ISSUE THREAD

**Issue by honzajavorek** [huge-success/sanic#1713]
**Is your feature request related to a problem? Please describe.**
I just noticed requests-async is [mentioned multiple times throughout the project](https://github.com/huge-success/sanic/search?q=requests-async&unscoped_q=requests-async), but the https://github.com/encode/requests-async is archived and https://github.com/encode/httpx is mentioned as a replacement. Perhaps Sanic should recommend httpx instead then?

**Describe the solution you'd like**
Sanic should mention and work with httpx instead of requests-async.

**Comment by harshanarayana** [comment]
@honzajavorek Valid point. Let me get this one sorted out later in the day. Thanks for pointing this one out. 

When we started using `requests-async` it was still under development. Looks like we missed the fact that it got archived.

**Comment by honzajavorek** [comment]
Let me know if I can help.

**Comment by yunstanford** [comment]
@honzajavorek PRs are welcome

**Comment by harshanarayana** [comment]
@honzajavorek  @yunstanford 
I did a quick scan on the changes done by the `httpx` to the `requests-async` API and there seem to be a considerable difference. Especially on the ASGI side of the things. 

Seems like it needs a bit more work than I initially expected. @honzajavorek Please feel free to open a PR. I am more than happy to help you on anything you need.

**Comment by ahopkins** [comment]
Sorry guys... that was partially my lapse since I had stepped away for a little bit die to personal reasons. I'm back on this now.

As mentioned, the requests-async package had been under active development. I'll take a look at the changes required because it is a significant requirement for testing. In particular being able to directly reach into the ASGI module without spinning up a server.

**Comment by jaylucas** [comment]
Any word on this?

**Comment by honzajavorek** [comment]
I’m still learning my ways around Sanic. When I’m done with my hobby
project using Sanic I want to take a look at this.

**Comment by ahopkins** [comment]
WIP: See #1728

**Comment by ahopkins** [comment]
@tomchristie made some **greatly** appreciated improvements to `httpx`. Much easier to make it extendable than the previous. I took a first pass to clean up and simplify some of the logic, but there are still some tests that need to be cleaned up.
