### ISSUE TITLE
What is the correct way to close a stream?

### ISSUE THREAD

**Issue by bootrino** [huge-success/sanic#1720]
I can't see anything in the documentation telling the right way to close a stream.

My streaming function sends some data, and for some reason I am sending await response.write(None) and then doing a return to finish the stream but I think this is not right.

```
            await response.write('event: message\n')
            await response.write(f'data: {message}\n')
            await response.write('\n\n')
            # abort stream
            **await response.write(None)
            return**

```

Can anyone suggest the correct way to finish a stream?

thanks!

**Comment by chenjr0719** [comment]
Hi @bootrino 

Actually, you don't have to do anything to finish the stream. It will close stream once you don't write any response. Here is an example:

```python
from sanic import Sanic
from sanic.response import stream

app = Sanic()


@app.get('/')
async def test(request):
    async def sample_streaming_fn(response):
        for n in range(0, 1024 * 40):
            await response.write(b'a')

    return stream(sample_streaming_fn)


app.run(debug=True)

```

After the for loop is finished, the connection will also close automatically. Using `return` and `return None` I think is equivalent in this example.
