### ISSUE TITLE
AttributeError: 'Queue' object has no attribute 'read'

### ISSUE THREAD

**Issue by medcelerate** [huge-success/sanic#1721]
**Describe the bug**
When using the stream api on` body = await request.stream.read() `
AttributeError: 'Queue' object has no attribute 'read'

**Code snippet**
```
@app.post('/data/<idx>/<hashx>', stream=True)
async def upload(request, idx, hashx):
  x = tempfile.NamedTemporaryFile(mode='a')
  while True:
      print(request.body)
      body = await request.stream.read()
      if body is None:
          break
      x.write(body)
      x.seek(0)
  print("appending")
  f_arr.append((idx, hashx, x))
  return text('ok')
  
```
**Expected behavior**
Should take stream and write it to a file

**Environment (please complete the following information):**
 - OS: macos
- Python 3.6

**Comment by ahopkins** [comment]
What version of Sanic are you using?

**Comment by vltr** [comment]
@medcelerate AFAIK `asyncio.Queue`s does not have a `read` method. Being a `Queue`, you should try to use `get`. Documentation [here](https://docs.python.org/3.6/library/asyncio-queue.html).

Let us know if you have any other questions :wink:
