### ISSUE TITLE
Error: Payload Too Large

### ISSUE THREAD

**Issue by shree-sopt** [huge-success/sanic#1725]
I am facing the following error: `Error: Payload Too Large` while uploading 1.26 GB file using sanic web server.

Here is the code:

```
async def upload(self ,request):
        try:
            test_file = request.files.get('file')
            file_parameters = {
            'body': test_file.body,
            'name': test_file.name,
            'type': test_file.type,
            }
            file_path = './'
            with open(file_path, 'wb') as f:
                f.write(file_parameters['body'])
            f.close()
            return json({ "received": True, "file_names": request.files.keys(), "success": True })
        except Exception as e:
            print(e)
            return response.text(format(e))
```

We are building a big data solution and are expecting files ranging from 200 GB to 1 TB. This operation has to be asynchronous.

For testing I'm deploying it on my Mac. RAM is 16GB

**Comment by Tronic** [comment]
See #1722

**Comment by shree-sopt** [comment]
Will try the solution. How should I set the max request size? `app.config.request_max_size`?

**Comment by yunstanford** [comment]
It'd be better to do streaming instead of loading all data into ram.

**Comment by sjsadowski** [comment]
No further update from reporter, closing
