### ISSUE TITLE
Interface differences between Blueprint and Sanic

### ISSUE THREAD

**Issue by eirikrye** [huge-success/sanic#1732]
The `Sanic` class exposes methods to add listeners and middleware through `register_listener`, `register_middleware` in addition to the decorator variants (`listener`, `middleware`). However, the Blueprint class only implements the decorators and instead opts to define `register_listener` and `register_middleware` in a closure under the corresponding decorator function.

Is this a deliberate design decision, or would it be possible for the Blueprint API to more closely emulate the Sanic class?

**Comment by vltr** [comment]
That's an interesting question. I personally don't see why we could not have a `register_listener` or `register_middleware` in a `Blueprint`. This could even be implemented as an `ABC` ...
