### ISSUE TITLE
Empty responses and Content-Type

### ISSUE THREAD

**Issue by LiraNuna** [huge-success/sanic#1735]
**Is your feature request related to a problem? Please describe.**
I would love to be able to send out lean responses. Sometimes a 204 response is just enough to signal the client what the backend wants to do. Currently, this is possible but has some awkwardness. 
First, an empty response has no `Content-Type`, however all responses require `Content-Type` header because of this chunk of code: https://github.com/huge-success/sanic/blob/master/sanic/response.py#L128-L130

As [RFC 2616](https://tools.ietf.org/search/rfc2616#section-7.2.1) says:

> Any HTTP/1.1 message containing an entity-body SHOULD include a
> Content-Type header field defining the media type of that body

Since we have an empty body, we should be able to discard the content type.

**Describe the solution you'd like**
At the core, I would love `content_type` to be able to be optional on `HTTPResponse`. As a synthetic sugar, a `response.empty()` would be a very nice addition (sending an empty body, 204 response)

**Additional context**
I am willing to contribute a PR if this idea sounds good to the project maintainers.

**Comment by ahopkins** [comment]
I would be happy to see a PR from you on this. Swing away.

**Comment by LiraNuna** [comment]
@ahopkins PR created.

**Comment by ahopkins** [comment]
Closing in favor of PR.
