### ISSUE TITLE
Incorrect documentation for AsyncioServer or missing __getattr__ on AsyncioServer

### ISSUE THREAD

**Issue by autumnjolitz** [huge-success/sanic#1754]
**Describe the bug**
The described sample code for the AsyncIO server is out of date (https://sanic.readthedocs.io/en/latest/sanic/asyncio_python37.html) or a resultant merge stripped a `__getattr__` handler from the AsyncIOServer class. 

I discovered this while bootstrapping a mock Azure API inside pytest for my API server (all Sanic because, why not?)

**Code snippet**
```
#!/usr/bin/env python3
import socket
import asyncio

from sanic import Sanic
from sanic.response import text

async def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
    sock.bind(("", 0))
    print(sock.getsockname())

    app = Sanic("azure_test_api")

    @app.get("/")
    async def test_index(request):
        return text('test')

    server = await app.create_server(
        sock=sock,
        return_asyncio_server=True,
        asyncio_server_kwargs=dict(start_serving=False),
    )
    # The docs say this
    await server.start_serving()
    await server.serve_forever()
    # but only this works ;)
    # await server.server.start_serving()
    # await server.server.serve_forever()

if __name__ == "__main__":
    asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())
    asyncio.run(main())
```

**Expected behavior**
I expect the docs to be updated or the following added to the AsyncIOServer class in server.py (https://github.com/huge-success/sanic/blob/2f776eba85b80ed5ee7e75badb92028ee1df0f4f/sanic/server.py#L671) -

```
    def __getattr__(self, prop_name):
         if not self.server:
            raise AttributeError('{} not found on {}'.format(prop_name, self)
         return getattr(self.server, prop_name)

```

**Environment (please complete the following information):**
 - OS: osx
 - Version 10.14.6 (18G95)

**Additional context**
N/A

**Comment by ashleysommer** [comment]
Hi @autumnjolitz 
This might be a problem introduced by my changes in this PR: https://github.com/huge-success/sanic/pull/1676
I didn't test those changes on python3.7, nor with the "server.start_serving()" or "server.serve_forever()" methods.
We can change the documentation to reflect the code changes you mentioned, or we can add those properties to the AsyncioServer proxy object in a future Sanic version.

**Comment by ahopkins** [comment]
I think the better change is the second described by @ashleysommer: changing the code to reflect the existing documentation to undo the regression. 👍

PRS welcome.
