### ISSUE TITLE
Testing with request,

### ISSUE THREAD

**Issue by johndiego** [huge-success/sanic#1756]
*How make  testing with requests LIB*

I'm Using pytest 
My fixture
```
@pytest.fixture
async def server_cli(loop, app, sanic_client):
    app = create_app('test')
    server = await app.create_server(
        return_asyncio_server=True,
        asyncio_server_kwargs=dict(start_serving=True),
    )

```

i 'm testing
How get url by  name ?
```
def test_index(server_cli):
    print(server_cli)

    r = requests.get('MY URL name here')
    print(r.json())
    assert 2 ==1

```

**Comment by ashleysommer** [comment]
Hi @johndiego 
While it _is_ possible to use the `requests` library like you have attempted here, it is a lot of work to set up boilerplate code to get it working.

Instead, it is recommended you use the `pytest-sanic` library, like is shown in the documentation here: https://github.com/huge-success/sanic/blob/master/docs/sanic/testing.rst#pytest-sanic

**Comment by ahopkins** [comment]
You also have the option of using the built in testing client as used by the Sanic internal unit tests:

```python
request, response = app.test_client.get('/')
```

Or...

```python
request, response = await app.asgi_client.get('/')
```
