### ISSUE TITLE
Websocket doesn't work when using version parameter

### ISSUE THREAD

**Issue by danieldaeschle** [huge-success/sanic#1757]
**Describe the bug**
When defining a websocket handler using `version=1` a exceptions will be thrown.

**Code snippet**
Relevant source code, make sure to remove what is not necessary.
```
@app.websocket("/changes", version=1)
```

**Expected behavior**
It should work like without `version=1`

**Environment (please complete the following information):**
 - OS: Fedora 31
 - Sanic: 19.12.2

**Comment by danieldaeschle** [comment]
I found out, that the websocket path is still `/changes` without `/v1` as prefix.
It's a routing issue.

**Comment by danieldaeschle** [comment]
`version` is missing here: https://github.com/huge-success/sanic/blob/master/sanic/app.py#L519

**Comment by ahopkins** [comment]
@danieldaeschle  Would you be able to submit a PR and perhaps a unit test?

**Comment by danieldaeschle** [comment]
I didn't found the root case yet. I'm not familiar with the sanic code. Do
you have a hint for me?
Otherwise i have to dig deeper an try to submit one.

Adam Hopkins <notifications@github.com> schrieb am Mo., 6. Jan. 2020, 21:12:

**Comment by ahopkins** [comment]
I did a quick look at the code you linked to on my phone. I'm fairly certain that you pinpointed the right place. All you should need to do is add the version kwarg to the method and then to the call that you linked. If you want to just do that much I can then take a look and give you some more direction on where and how to add the test.

**Comment by danieldaeschle** [comment]
I already tried adding that kwarg. But that wasn't enough to work.

Adam Hopkins <notifications@github.com> schrieb am Di., 7. Jan. 2020, 07:14:

**Comment by ahopkins** [comment]
OK. Thanks for taking a shot. I can take this one in conjunction with upgrading websockets dependency.

**Comment by danieldaeschle** [comment]
Thanks!
Is it possible to get this fix soon?

Am Di., 7. Jan. 2020 um 18:04 Uhr schrieb Adam Hopkins <
notifications@github.com>:
