### ISSUE TITLE
In Travis some Python3.7+ tests are not running

### ISSUE THREAD

**Issue by ashleysommer** [huge-success/sanic#1763]
**Describe the bug**
In `tests/test_app.py` there are several tests which are supposed to only run when python `version >= (3,7)` (actually it's "skip if less-than (3,7)", but same logic)
But if you look at the test logs in Travis, specifically when looking at the Python 3.7 run, those tests are _not_ run.

**Code snippet**
This is an example of what one of the tests in `test_app.py` uses:
```
@pytest.mark.skipif(
    sys.version_info < (3, 7), reason="requires python3.7 or higher"
)
``` 

**Expected behavior**
Its expected that when python version >= 3.7.0 those tests will be run by Travis

**Comment by yunstanford** [comment]
@ashleysommer looks like those tests have been run, unless i was looking at wrong place.

**Comment by ashleysommer** [comment]
Here's how I'm checking:
1) Find any PR which is currently running pre-review tests, and click through to the respective Travis Build
2) Find the "Python 3.7 with Extensions" or "Python 3.7 without Extensions" job, and expand the job-log.
3) Look at the list of tests that job is running, it will be in the format `filename.py:test_name`
4) Look for a python3.7-only test, like `test_app.py:test_create_asyncio_server`, it is not there.

See this screenshot, this is a snippet of the tests I see run in "Python 3.7 with Extensions" and in "Python 3.7 without Extensions" jobs.
![Screenshot_2020-01-11 Job #3030 3 - huge-success sanic - Travis CI](https://user-images.githubusercontent.com/402468/72199328-4e2c2780-3486-11ea-8c35-8c367d223fa8.png)

**Comment by yunstanford** [comment]
I was looking the same page, but different place.

Py3.6:
<img width="620" alt="Screen Shot 2020-01-10 at 9 46 35 PM" src="https://user-images.githubusercontent.com/13110231/72199580-ce08b200-33f2-11ea-940e-cc4983227f79.png">

Py3.7:
<img width="625" alt="Screen Shot 2020-01-10 at 9 46 52 PM" src="https://user-images.githubusercontent.com/13110231/72199585-d4972980-33f2-11ea-998a-62d7751de27d.png">

can verify locally tho.

**Comment by ashleysommer** [comment]
Ok thanks for looking into it, looks like it probably _is_ running those tests then, but without the test name printed in the detailed tests list.

I can't test it locally because I don't have a PC handy with Python 3.7 installed.
