### ISSUE TITLE
How can sanic keep handle request even if connection is closed ?

### ISSUE THREAD

**Issue by Elune0syh** [huge-success/sanic#1765]
**Is your feature request related to a problem? Please describe.**

I have some post request handler, sometimes i saw the request handler is cancelled even if the handler fucntion was executed on half way.
for example: save some data to dbs, but the rest of code is not executed because of cancellation, this is undesirable because it causes data unconsistency in db

**Describe the solution you'd like**

What can i do to prevent request handler function be cancelled ? i have read the related [issue](https://github.com/huge-success/sanic/pull/1361), but i didn`t find any solutions

sanic version: 18.12.0
python: 3.7

**Comment by vltr** [comment]
Hello, @Elune0syh !

Just for clarification, you have some workflow inside a handler and would like to have everything ran, even though the connection could be closed at any time and no response generated whatsoever?

**Comment by sjsadowski** [comment]
I was thinking that there might be something inside the call that is causing the async call to timeout, personally.

**Comment by Elune0syh** [comment]
@vltr Thanks for your reply. That`s exactly what i want to do

i have a post request workflow to create some records in db, i want these records to be all created or not be created at all. maybe something like [atomic](https://aiojobs.readthedocs.io/en/latest/api.html#aiojobs.aiohttp.atomic) ?

**Comment by Elune0syh** [comment]
@sjsadowski 
I don`t know, it`s suspectable, i did`t see any timeout error on traceback, maybe who swallows the timeout error ? but i did see the CancelledError propagated to db / kafka / etcd function call

**Comment by sjsadowski** [comment]
@Elune0syh I think asyncio is supposed to raise TimeoutError so you *should* see it in the traceback, but if you have robust error handling in there that eats the raised error in a try block, it could be problematic.

**Comment by Elune0syh** [comment]
@sjsadowski 
Now i can sure in my situation the CancelledError was caused because of client disconnect (but we did do some try block in error handling, thanks anyway) .

The client disconnect was caused because we did something wrong in a front proxy service

**Comment by Elune0syh** [comment]
Mybay i can use `asyncio.shield` to prevent cancellation to request handler.
It`s a solution ?

```
    def dispatch_request(self, request, *args, **kwargs):
        handler = super().dispatch_request(request, *args, **kwargs)
        #return handler
        return asyncio.shield(handler)
```

**Comment by vltr** [comment]
@Elune0syh perhaps `asyncio.shield` _could_ help, but I think that, if your problem is only at the database level, you should either:

- create a task for them to be executed independently; or
- wrap them into a transaction (I don't know which database you're using, but most of them supports this).

Now, if your problem is actually *catching* when a request is cancelled, then we might need to take a further look but, in my experience, you should avoid having long, consuming processing times while the request is being performed (or left open, so to speak) - either make it simpler or delegate the load somewhere else.

**Comment by Elune0syh** [comment]
@vltr Thanks for your advice

We use Cassandra for database things, so there is no way to do transactions. Your advice is really help, i will take these into consideration to refactor my code, thanks again

**Comment by vltr** [comment]
@Elune0syh I'm glad I could help! Let us know if you need something else :+1:
