### ISSUE TITLE
sanic.exceptions.NotFound: Requested URL /favicon.ico not found

### ISSUE THREAD

**Issue by mystic-cg** [huge-success/sanic#1766]
**Describe the bug**
like as
https://github.com/RasaHQ/rasa/issues/4129

**Code snippet**
```python
from sanic import Sanic
from sanic.response import json

app = Sanic("blog")


@app.route("/")
async def test(request):
    return json({"hello": "world"})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

**Expected behavior**
Without any exception

**Environment (please complete the following information):**
 - OS: `win10.1709`
 - Python: `3.8.1`
 - Sanic: `19.12.2`

**Additional context**
> [2020-01-19 12:00:10 +0800] [31552] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2020-01-19 12:00:10 +0800] [31552] [WARNING] Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
[2020-01-19 12:00:10 +0800] [31552] [WARNING] Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
[2020-01-19 12:00:10 +0800] [31552] [INFO] Starting worker [31552]
[2020-01-19 12:00:26 +0800] - (sanic.access)[INFO][127.0.0.1:51041]: GET http://127.0.0.1:8000/  200 17
[2020-01-19 12:00:26 +0800] [31552] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/favicon.ico'
Traceback (most recent call last):
  File "C:\Users\someone\.virtualenvs\LearningSanic-Q13QjVkW\lib\site-packages\sanic\app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "C:\Users\someone\.virtualenvs\LearningSanic-Q13QjVkW\lib\site-packages\sanic\router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "C:\Users\someone\.virtualenvs\LearningSanic-Q13QjVkW\lib\site-packages\sanic\router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
[2020-01-19 12:00:26 +0800] - (sanic.access)[INFO][127.0.0.1:51041]: GET http://127.0.0.1:8000/favicon.ico  404 43

**Comment by mystic-cg** [comment]
If you run with "0.0.0.0"
When you first use a certain address to access(e.g. http://127.0.0.12:8000), it will throw the above exception; if you visit again using this address, it will all work fine

**Comment by Tronic** [comment]
Browsers try to fetch favicon.ico for that small image shown on browser title bar. This can be avoided by adding `<link rel=icon href="url to your logo.png">` to HTML header, but for the most part you can safely ignore the favicon requests and related 404 errors, especially if your document is JSON and not HTML.

**Comment by andreymal** [comment]
@Tronic anyway, the log is too verbose. This is obviously not an [ERROR]; traceback is not necessary here.

**Comment by sjsadowski** [comment]
I agree with @andreymal - @huge-success/sanic-core-devs care to weigh in on this?

**Comment by ashleysommer** [comment]
@sjsadowski 
So options are:
* Reduce verbosity of error reporting for all thrown 404 exceptions, or
* Create a special case for detecting 404 exceptions thrown when browsers trying to access `/favicon.ico` so to suppress the error message
* Add default route for `/favicon.ico` in the built-in router with a response function which returns `Response(status=404)` (or maybe with smarts to automatically find and serve a favicon.ico from project root dir if it exists).

**Comment by sjsadowski** [comment]
Do we think it's that important to have a traceback with every NotFound exception? I ask because anecdotally I can't recall ever having found them useful for 404s. 

I don't think we want to dynamically detect the /favicon.ico request as it's bloat and largely irrelevant anyway.

The last item might be my preference, however I've never written anything with Sanic that directly serves to browsers, I've only written REST APIs with it and generally proxy the path through something else (nginx, traefik, etc) so I don't ever deal with favicon requests.

Honestly I'd normally just tell people to add a route for the favicon and  handle it themselves, but I don't know if that's reasonable.

**Comment by ashleysommer** [comment]
>Do we think it's that important to have a traceback with every NotFound exception? I ask because anecdotally I can't recall ever having found them useful for 404s.

No. NotFound exceptions should not produce a traceback, except for maybe if Sanic is running with `debug=True`.

>Honestly I'd normally just tell people to add a route for the favicon and handle it themselves, but I don't know if that's reasonable.

I was actually going to list that as an option in my comment above, but didn't know if it was too unreasonable. Perhaps the fix for this is to simply include something in the documentation about how to write an `@app.static` file route for `/favicon.ico`.

**Comment by mystic-cg** [comment]
At least, I think a demo in docs should work well without any error, even warnings.

**Comment by ashleysommer** [comment]
>At least, I think a demo in docs should work well without any error, even warnings.

I'm not sure if it _should_ or not.

But if I'm running a simple example, and the browser asks for something on endpoint "/favicon.ico" and the server is not configured to accept requests to that route, then I _do_ expect it to output at least something in the console, like "Error: No route for request "/favicon.ico".

**Comment by Tronic** [comment]
I think it is reasonable to *only* output a 404 on access log, not as an error of any sort.

**Comment by Tronic** [comment]
@mystic-cg This is now fixed in Sanic master and you may close the issue.

**Comment by virajlimbasiya** [comment]
hello every i am facing same issue does anyone have solution?

**Comment by ahopkins** [comment]
@virajlimbasiya What version are you using? Did you read through the whole thread? What exactly is the problem?
