### ISSUE TITLE
Using list with host parameter in blueprint.route() does not work.

### ISSUE THREAD

**Issue by damianj** [huge-success/sanic#1772]
**Describe the bug**
As the title implies, when I try to set the host parameter to a list on a blueprint route, the app does not start and instead gives an error like:

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    parent_app.blueprint(child_bp)
  File "/usr/lib/python3.8/site-packages/sanic/app.py", line 757, in blueprint
    blueprint.register(self, options)
  File "/usr/lib/python3.8/site-packages/sanic/blueprints.py", line 146, in register
    route_names = [route.name for route in routes]
  File "/usr/lib/python3.8/site-packages/sanic/blueprints.py", line 146, in <listcomp>
    route_names = [route.name for route in routes]
AttributeError: 'NoneType' object has no attribute 'name'
```

**Code snippet**
To reproduce that error:
```
from sanic import Sanic, Blueprint
from sanic.response import text

child_bp = Blueprint(name='child_blueprint', url_prefix='/')
parent_app = Sanic(__name__)


@child_bp.route('/', host=["localhost:8000", "127.0.0.1:8000"])
async def hello_world(request):
    return text("Hello world!")

parent_app.blueprint(child_bp)
parent_app.run()
```
Note that if host is set to a string (i.e., `@child_bp.route('/', host="127.0.0.1:8000")`) or it's not even specified in the route (i.e., `@child_bp.route('/')`) then the app runs just fine.

**Expected behavior**
I would expect that the host parameter would function similar to that described in [https://sanic.readthedocs.io/en/latest/sanic/routing.html#http-request-types](https://sanic.readthedocs.io/en/latest/sanic/routing.html#http-request-types)

> There is also an optional host argument (which can be a list or a string). This restricts a route to the host or hosts provided. If there is a also a route with no host, it will be the default.

**Environment (please complete the following information):**
 - OS: Arch Linux (Kernel 5.4.13)
 - Version: 19.12.2

**Additional context**
This was working previously so I don't know if it's a bug or some intentional change in functionality.

**Comment by damianj** [comment]
I've opened #1776 to address this issue.

**Comment by ahopkins** [comment]
Closing in favor of PR. Let's continue the conversation there if needed.

**Comment by ahopkins** [comment]
Thanks for bringing this up.

**Comment by myusko** [comment]
@ahopkins @ashleysommer probably we should close the issue since we already merged PR with a fix.
