### ISSUE TITLE
Add tests for route decorators

### ISSUE THREAD

**Issue by sjsadowski** [huge-success/sanic#1775]
Add tests to prevent reversions on route decorators.

**Comment by ashleysommer** [comment]
@sjsadowski 
I added some basic tests for the multiple-@route decorators, when I submitted my fix:
https://github.com/huge-success/sanic/commit/b565072ed9792debb017ba3dc2b3de67f8f03514#diff-4591e684af0cbdb11ee7409ef6f9aa4aR554

Do you know which other decorators don't have proper tests?

**Comment by sjsadowski** [comment]
@ashleysommer not yet - that's why I assigned it to myself. I may close it, but my biggest concern was not running into another reversion with decorators.
