### ISSUE TITLE
Sanic and Flask have similar performance when reading DataBase such as POSTGRESQL. 

### ISSUE THREAD

**Issue by sunshineinwater** [huge-success/sanic#1780]
### Description

**use WRK test three types of web frame to read one recorder in postgresql database
: 1、Sanic+gino, 2、flask+sqlalchemy+gevent+gunicorn,  3、Golang gin+gorm.**

test machine: MacBook Pro 8GB

- concurrence result :
1.  sanic+gino: 1700 requests/seconds
2. flask+sqlalchemy:1100 requests/seconds
3.  Golang : 5000+ requests/seconds 

**flask + SQLAlchemy :** 

<img width="405" alt="image" src="https://user-images.githubusercontent.com/15187861/73996433-83993780-4996-11ea-8af4-2d22da136dec.png">

**Sanic + gino:** 

<img width="417" alt="image" src="https://user-images.githubusercontent.com/15187861/73996565-df63c080-4996-11ea-9cd0-d92ff82b47e9.png">

**use Same Configration test purl web performance:**

- concurrence result :
1.  Sanic : 20000 requests/seconds
2.  flask:   3300 requests/seconds
3.  Golang : 80000 requests/seconds 

**Why it has nearly performance between sanic+gino and flask+sqlalchemy  ?**

### What I Did

**Sanic + gino :** 

```
@app.route('/testdb', methods=['GET'])
async def test_db(request):
    data = await UserModel.query.where(UserModel.accountID == "test").gino.first()
    return response.text(data.openID)

if __name__ == '__main__':
    app.run(debug=False, port=7005, host='0.0.0.0', workers=5, access_log=False)
```

**Flask + SQLalchemy:**  

```
@app.route("/testdb", methods=["GET"])
def test_db():
    data = UserModel.query.filter(UserModel.accountID == "test").first()
    if data is not None:
        return data.accountID
    return "None"

run:
gunicorn main:app --bind 0.0.0.0:7005 --worker-class gevent --workers 9 --threads 8
```

**Comment by sjsadowski** [comment]
So... is this informational? An issue? Nothing really explains what's going on here, other than you did some tests. Can you expand upon your concern?

**Comment by Garito** [comment]
You have 5 workers on sanic versus 9 with flask
Would be interesting if you try same number

**Comment by sunshineinwater** [comment]
under 5 workers have the best performance, add the number of workers have not any improvement .

> You have 5 workers on sanic versus 9 (and 8 threads) with flask
> Would be interesting if you try an equivalent number

**Comment by sunshineinwater** [comment]
> So... is this informational? An issue? Nothing really explains what's going on here, other than you did some tests. Can you expand upon your concern?

want to know what factor limit the performance ?

**Comment by Tronic** [comment]
Looks like gino is the bottle neck here. Try directly with asyncpg perhaps? I never use SQL anymore. Redis at least can keep up with Saniculous speed.

**Comment by sunshineinwater** [comment]
> Looks like gino is the bottle neck here. Try directly with asyncpg perhaps? I never use SQL anymore. Redis at least can keep up with Saniculous speed.

THX for advicing.  
**The newest test of Sanic+asyncpg achieve the same performance with Golang !**

<img width="388" alt="image" src="https://user-images.githubusercontent.com/15187861/74010011-6e84ce80-49bf-11ea-8dc7-4e4f8abc1a44.png">

**Comment by sunshineinwater** [comment]
> Looks like gino is the bottle neck here. Try directly with asyncpg perhaps? I never use SQL anymore. Redis at least can keep up with Saniculous speed.

By the way.  How to deal with mass data in Redis ?

**Comment by Tronic** [comment]
You might consider CouchDB, RethinkDB or Mongo if your needs are beyond small scale key-value store. I cannot comment on their performance in relation to SQL databases though, especially since they sport vastly different feature sets.

**Comment by sjsadowski** [comment]
I'm going to close for now; please consider moving discussions to the [community forum](https://community.sanicframework.org/)
