### ISSUE TITLE
ujson can not be used with python 3.8.1

### ISSUE THREAD

**Issue by rhdxmr** [huge-success/sanic#1781]
ujson is imported by request.py and response.py

But under python 3.8.1 ujson can not be imported and ImportError is raised.

> ujson.cpython-38-x86_64-linux-gnu.so: undefined symbol: Buffer_AppendShortHexUnchecked

sanic works ok because exception handler exists.
```
try:
    from ujson import loads as json_loads  # type: ignore
except ImportError as e:
    from json import loads as json_loads  # type: ignore
```

It seems that ujson is not maintained anymore.

**Comment by ahopkins** [comment]
The idea to replace ujson [has been brought up before](https://github.com/huge-success/sanic/issues/1479). It is definitely something in need of discussion because it will be a backwards incompatible change. ujson works a little differently than other libraries so just changing the dependency to something else is likely to cause some headaches. Nevertheless, it should be discussed. Thanks for bringing it up.

Any thoughts about alternatives, now is a good time to start bringing them up.

**Comment by vltr** [comment]
I did not see any problems so far with `ujson` and Python 3.8.1. @rhdxmr can you provide more information about your environment?

@ahopkins I agree that `ujson` is somewhat old and not maintained (by the original author), but I also found a lot of forks over the internet that corrects some problems here and there, updating the code and bringing it to a more interesting state. I just don't know if this a path the community wants to take, even though it's not a complicated codebase to maintain (even though it's written in C).

**Comment by Tronic** [comment]
https://github.com/lemire/simdjson is the fastest JSON decoder. Unfortunately, much of the performance is lost if the entire document needs to be converted into Python objects (instead of lookups to specific JSON paths). Further, this is only a decoder.

https://rapidjson.org/ is pretty much on par with ujson on performance, has 100 % spec conformance, and there are actively maintained Python bindings https://pypi.org/project/python-rapidjson/

If not for the standard library, RapidJSON looks like a very promising choice, although its Python performance would need to be evaluated, as well as possible compatibility issues against stdlib and ujson.

**Comment by sjsadowski** [comment]
Keep in mind too, we don't limit json decoding to what's built in. In general sanic is still failing tests under 3.8 so probably some work needs to be done there as well.

**Comment by vltr** [comment]
@Tronic `simdjson` is indeed faster for special lookups in the document (I used it in a project recently). But, it can encode to JSON (AFAIK), so I think it's a very good JSON library for some edge cases (not to mention the Python bindings are not all that reliable if you start do dig inside other methods, but that's not the case).

RapidJSON, OTOH, is fast and reliable, might be a good choice for us.

@sjsadowski I'll take a look on those tests ... From master?

**Comment by ahopkins** [comment]
@Tronic I did play around with rapidjson and Sanic about 6+ months ago. I honestly don't remember the issues I found. I will go back and try to find my notes on it.

**Comment by rhdxmr** [comment]
@vltr I figured out why ujson raised ImportError in my environment.
I built python 3.8.1 with CFLAGS=-O0 to turn off optimization because of debugging issue.

When I execute this command using my python-3.8.1 at ujson-1.35, -O0 is set also.

> $ python setup.py build
> ... truncated ...
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O0 -O0 -fPIC -I./python -I./lib -I/home/esrse/.pyenv/versions/3.8.1/include/python3.8 -c ./python/ujson.c -o build/temp.linux-x86_64-3.8/./python/ujson.o -D_GNU_SOURCE
> ... truncated ...

This command builds ujson.cpython-38-x86_64-linux-gnu.so which has undefined

**Comment by rhdxmr** [comment]
@vltr I figured out why ujson raised ImportError in my environment.
I built python 3.8.1 with CFLAGS=-O0 to turn off optimization for debugging using gdb.
> $ CFLAGS=-O0 pyenv install 3.8.1

And I installed ujson using this command
> $ pip install ujson

Without CFLAGS=-O0, ujson can be imported successfully using python 3.8.1
>>> import sysconfig
>>> sysconfig.get_config_var('CFLAGS')
'-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall'
>>> import ujson
>>>

But if python 3.8.1 is built with CFLAGS=-O0, ujson raises ImportError.
>>> import sysconfig
>>> sysconfig.get_config_var('CFLAGS')
'-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O0 -O0'
>>> import ujson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/esrse/.pyenv/versions/3.8.1/lib/python3.8/site-packages/ujson.cpython-38-x86_64-linux-gnu.so: undefined symbol: Buffer_AppendShortHexUnchecked
>>>


I had turned off optimization before python 3.8. But there were no problems occurred with python 3.7.
Test with python 3.7.6  seems OK.
>>> import sysconfig
>>> sysconfig.get_config_var('CFLAGS')
'-Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O0 -O0'
>>> import ujson
>>>

**Comment by rhdxmr** [comment]
There are people having similar problem with ujson.
https://www.google.com/search?q=ujson+undefined

**Comment by vltr** [comment]
Thanks, @rhdxmr ! I saw in the links from Google that this is actually a quick fix to `ujson`, but I don't see any further developments within `ujson` - **it can be saved**, though. I think this would be a nice topic in the community forums (again).

**Comment by andreymal** [comment]
ultrajson 2.0.0 is released, supports Python 3.8 https://github.com/ultrajson/ultrajson/releases/tag/2.0.0

**Comment by autumnjolitz** [comment]
We switched over to `orjson`. We handled the lack of support for alpine by using nightly rust and RUSTC flags that specified static only linking. `orjson` is faster and actively maintained.

**Comment by stalkerg** [comment]
I also using orjson main issue for comparing with rapidjson - you can't automatically deserialize DateTime.

**Comment by ahopkins** [comment]
See also #1479  and https://community.sanicframework.org/t/sanic-testing-and-dependency-on-httpx/556
