### ISSUE TITLE
Examples Update - How to process a basic POST request?

### ISSUE THREAD

**Issue by vgoklani** [huge-success/sanic#1787]
Looking through the examples, I noticed that a lot of basic things were just missing. For example, how do you use Sanic to process a basic POST request? One very important use case is building APIs, and it's really time-consuming to have to dig through this framework (which is a "huge-success) and not see basic things explained.

**Comment by Tronic** [comment]
Do you mean HTML form submission (no Javascript), or POST from Javascript? Try with something like:

```python
@app.post("/path")
async def do_something(request):
    print("Got form: ", request.form)
    print("Got JSON: ", request.json)
```

This is documented at https://sanic.readthedocs.io/en/latest/sanic/request_data.html

**Comment by ahopkins** [comment]
We'd be happy to entertain any documentation PRs that you may have.
