### ISSUE TITLE
Why doesn't Protocol use app.config to get its settings

### ISSUE THREAD

**Issue by Tronic** [huge-success/sanic#1796]
Sanic passes all settings such as `REQUEST_MAX_SIZE` as arguments via a chain of functions from `run_server` to `Protocol` constructor, rather than accessing them via `app.config` where needed. Is there a purpose to this?

**Comment by Tronic** [comment]
I suppose this could be removed in a future PR if anyone doesn't have objections to that. The APIs affected by this seem to be internal, as app methods such as `create_server` do not take these arguments.

**Comment by ashleysommer** [comment]
@Tronic the reason Protocol doesn't use app.config is simple, the `app.config` feature didn't exist when the `run_server` and Protocol constructor code was written in May 2016.

**Comment by Tronic** [comment]
That should now be sorted out. It's a large and quickly done patch, though, so I would suggest careful review. I did not remove the loop arguments because that would require more work and has potential to break apps that do weird things with multiple loops.
