### ISSUE TITLE
Shutdown Sanic server on KeepAlive Timeout (Saving Cloud Run minutes)

### ISSUE THREAD

**Issue by NumesSanguis** [huge-success/sanic#1799]
I want to deploy a Docker container to Google Cloud Run and use Sanic for accepting GET and POST requests. Since active containers cost money, I want them to shutdown whenever a request has finished processing.

The full question has been posted here: https://community.sanicframework.org/t/shutdown-sanic-server-on-keepalive-timeout-saving-cloud-run-minutes/512

Sorry for turning it into an issue here as well. It seems the visibility of my question is very low on the Sanic community board and therefore I would like to draw some extra eyes from here. I posted it 5 days ago, but since I only see 1 click on a link I posted in my question, I feel like it has been viewed by <5 people. Thank you in advance.

**Comment by ashleysommer** [comment]
Hi @NumesSanguis 
Thanks for posting your question on the Community forum first. I see now there are community members helping with your question, so when your problem is resolved, please feel free to close this github issue.

**Comment by NumesSanguis** [comment]
The community members' help has been great and it the problem is now resolved.
