### ISSUE TITLE
Http signature failed to parse with HttpRequestParser

### ISSUE THREAD

**Issue by autogestion** [huge-success/sanic#1811]
Getting error
```Traceback (most recent call last):
  File "/.../envs/pub1/lib/python3.7/site-packages/sanic/server.py", line 272, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserError: invalid character in header
```
Parsed data is

> b'POST /@test/inbox HTTP/1.1\r\nhost: example.com:8000\r\ncontent-type: application/activity+json\r\nuser-agent: PubGate v:0.2.21\r\n(request-target): post /@test/inbox\r\ndate: Wed, 18 Mar 2020 22:22:33 GMT\r\ndigest: SHA-256=i73n6+Pje6kxzyuGB8f88EuB+FEH+pyDECVQ58r3UCU=\r\nsignature: keyId="http://example.com:8000/@test2#main-key",algorithm="rsa-sha256",headers="content-type user-agent (request-target) date host digest",signature="gWwwnL/I/rl0eE7o7A1D4SOGK0N46APqrIAZhnZN1/SjBVYHDbcTN2H50w4K0hozis9erO5ztqHC8MQDLxJeRwu4KNbFtYn/xcYI9Ide3yoQ9UbN5tYCIQYyWOyDLVGkCOBb50DqscJsvCdRF3M58hfxEfZYyXH5UrxQYtyhXFWT8J6566n4ZcLwZvOTuTe8pHFHLiStdOjLZ1pnDtUoCLNaLwSzpfpKE2P8PuIBgCSmi3e0v+OAPsD9NKFNcBDFA1GNOCRgVX9XHmMlR3MNDqPKokUqOK5rbJ8LX0Gfbulu4yobvIOw9yU04H1cWSZz9fZ3WL8yGYJVH8wthRouSQ=="\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nContent-Length: 223\r\n\r\n'

sent by aiohttp https://github.com/autogestion/pubgate/blob/master/pubgate/utils/networking.py#L53

Worked in older version of Sanic, started to fail after update to last version

**Comment by Tronic** [comment]
```
POST /@test/inbox HTTP/1.1
host: example.com:8000
content-type: application/activity+json
user-agent: PubGate v:0.2.21
(request-target): post /@test/inbox
date: Wed, 18 Mar 2020 22:22:33 GMT
digest: SHA-256=i73n6+Pje6kxzyuGB8f88EuB+FEH+pyDECVQ58r3UCU=
signature: keyId="http://example.com:8000/@test2#main-key",algorithm="rsa-sha256",headers="content-type user-agent (request-target) date host digest",signature="gWwwnL/I/rl0eE7o7A1D4SOGK0N46APqrIAZhnZN1/SjBVYHDbcTN2H50w4K0hozis9erO5ztqHC8MQDLxJeRwu4KNbFtYn/xcYI9Ide3yoQ9UbN5tYCIQYyWOyDLVGkCOBb50DqscJsvCdRF3M58hfxEfZYyXH5UrxQYtyhXFWT8J6566n4ZcLwZvOTuTe8pHFHLiStdOjLZ1pnDtUoCLNaLwSzpfpKE2P8PuIBgCSmi3e0v+OAPsD9NKFNcBDFA1GNOCRgVX9XHmMlR3MNDqPKokUqOK5rbJ8LX0Gfbulu4yobvIOw9yU04H1cWSZz9fZ3WL8yGYJVH8wthRouSQ=="
Accept: /
Accept-Encoding: gzip, deflate
Content-Length: 223
```

The header name `(request-target)` is invalid, you cannot use parentheses in header names as per RFC 2616 (HTTP/1.1). The request works once you remove that header. Older Sanic probably used an httptools version that was less strict about this.

**Comment by autogestion** [comment]
@Tronic Thank you!
closing issue
