### ISSUE TITLE
Help with custom error handling

### ISSUE THREAD

**Issue by StVl** [huge-success/sanic#1817]
Hello

I try to make custom exception and catching them accroding to my logic
At the documentation, i found only that page:

https://sanic.readthedocs.io/en/latest/sanic/exceptions.html 

but this is not convenient for me: i don't have e request, for example, and i don't want to send "Internal server error" any time, when i overriding default() method. 

Maybe I make some mistakes
So, if you can, could you explain me, please, how to create custom exceptions without default() method overriding .

for example

I want to make something like that:

` 
class ProcessorException(ErrorHandler):
    def default(self, request, exception):
        return text(PROCESSOR_ERROR_HTML, status=303)

class UnsupportedParamError(ProcessorException, Exception):
    def default(self, request, exception):
        return super().default(request, exception) `

but this not working, because any controller is child from sanic, that's why any time i get "Internal Server Error" without my custom html and status

**Comment by willywongi** [comment]
Ciao! If I got this right, you want to raise custom exceptions (like `UnsupportedParamError`) and handle those exceptions returning useful error messages to the client.

If you just need to pass along a message you can just use `ServerError`.
```python
from sanic import Sanic
from sanic.response import html
from sanic.exceptions import SanicException

app = Sanic("my_app")

@app.exception(SanicException)
async def manage_exception(request, exception):
    # exception.args = ("There is something wrong",)
    message, = exception.args
    status_code = exception.status_code
    return text(`Ops! There was an error. {message}`, status=status_code)

@app.route("/")
async def index(request):
    # your code...
    # when you need to return an error
    if something_wrong:
        raise SanicException("There is something wrong")
    return html("Everything's alright")
```

If you want to raise different exceptions and react accordingly you can manage them.

```python
from sanic.exceptions import SanicException, ServerError, NotFound

class MyApplicationError(SanicException):
    pass

@app.exception(ServerError)
async def manage_server_error(request, exception):
    pass

@app.exception(NotFound)
async def manage_not_found(request, exception):
    pass

@app.exception(MyApplicationError)
async def manage_my_application_error(request, exception):
    pass
```

I was confused about where my "There is something wrong" message would be stored in the exception. I hope this helps you!

**Comment by StVl** [comment]
hi! Thak you, it will really help, right!

Большое спасибо, я думаю, это мне поможет. Сходу не смог сам сообразить,
как это правильно сделать
Потапов.

чт, 21 мая 2020 г. в 18:33, Francesco Pongiluppi <notifications@github.com>:
