### ISSUE TITLE
Preparing 20.3 release

### ISSUE THREAD

**Issue by Tronic** [huge-success/sanic#1825]
Assuming that the new release goes out tomorrow, I've compiled a list of PRs that should be included in the release. Only fixes that are approved at least in principle are included. I've omitted new features and PRs with pending requests for changes.

Code PRs:
- #1555 bugfixes on autoreloader
- #1696 fix blueprint names on websocket routes (needs review)
- #1760 version parameter on websocket routes: (approved, merge commit needs review)
- #1776 bugfix `None` access on routes (needs review)

Due to recent problems with CI pipelines, many of the above display various failures although I believe that if the tests were ran again, merged with current master, they'd pass just fine (if not for coverage changes). Quite possibly there will be more conflicts once some of these are merged, so it would be good for developers to stay alert, and perhaps release managers could also help sorting those out?

EDIT: Removing ones that have been merged.

**Comment by Tronic** [comment]
@sjsadowski Any timeline on release? It looks like other release managers are busy and there is no discussion on when 20.3 is coming out.

**Comment by damianj** [comment]
So are there any updates on when this will get merged, or what's going on with the project?

**Comment by ahopkins** [comment]
Corona. Kind of kicked a lot of us a bit for a loop. Sorry for the delay.

**Comment by yunstanford** [comment]
will release soon and also draft a change log afterwards.

**Comment by ashleysommer** [comment]
I'm back on board again after having a rough few months (along with everyone else).
Perhaps we should skip the 20.03 release and aim for a good 20.06 release in early June?

**Comment by Tronic** [comment]
Good to hear that the team is getting back on board.

I still see 20.03 (20.05?) as a useful testing stage before 20.06. There are already a lot of changes that have hardly been tested on git master because we only get proper field testing and feedback from actual releases. A month or two worth of feedback with this would be a good aid in 20.06 development. Also, there are quite many problems with 19.12 that should be fixed ASAP (yes, also back-ported for LTS but most users probably use the latest release rather than LTS).

**Comment by Tronic** [comment]
Closing as 20.03 has been released. The PRs still listed did not make it.
