### ISSUE TITLE
how  to deal with  stream file 

### ISSUE THREAD

**Issue by Erbeter** [huge-success/sanic#1831]
I uploaded a large file through the stream, but I found it particularly difficult to handle, I want to keep the file in my local, do you have any good way

**Comment by Tronic** [comment]
Are you uploading by HTML multipart/form-data, or by `fetch` from Javascript? These are completely different. If possible, I would suggest using `fetch` to send the bare file, so that the only thing you receive on Sanic streaming request is the file contents, no multipart headers.

**Comment by Erbeter** [comment]
> 您是通过HTML multipart / form-data还是`fetch`从Javascript 上传？这些是完全不同的。如果可能的话，我建议使用`fetch`来发送裸文件，以便您在Sanic流请求中收到的唯一内容是文件内容，没有多部分标题。

uploading by HTML multipart/form-data

**Comment by Tronic** [comment]
Sanic cannot decode multipart/form-data in streaming (without buffering the entire upload), so you'll have to decode it yourself. Perhaps in a future version this will be supported, but not any time soon.

**Comment by Erbeter** [comment]
OK, I see, thank you for your help
