### ISSUE TITLE
Document build failed

### ISSUE THREAD

**Issue by chenjr0719** [huge-success/sanic#1832]
Hey guys, I just noticed the document build on readthedocs has failed since 1 month ago. It caused by the `conda` again. I would like to fix this issue but I have one question, do we still need to use `conda` for creating the environment when building the document? Or, we can just use `pip install .[docs]`? Here is the [doc](https://docs.readthedocs.io/en/stable/config-file/v2.html#python) explain how to build the document on readthedocs with extra requirements. Let me know your idea. 😃

**Comment by ahopkins** [comment]
I say go ahead with `pip` and skip `conda`. :+1:
