### ISSUE TITLE
app.add_route() causes crash

### ISSUE THREAD

**Issue by Bevan0** [huge-success/sanic#1841]
**Describe the bug**
Program crashes when I try to add a route using the **app.add_route** function. Using @app.route still works however.
> File "C:/Users/bevan/PycharmProjects/beeprivate/beeprivate/src/main.py", line 24, in <module>
>   app.add_route("/", test_page)
> File "C:\Users\bevan\AppData\Local\Programs\Python\Python37\lib\site-packages\sanic\app.py", line 448, in add_route
>   name=name,
> File "C:\Users\bevan\AppData\Local\Programs\Python\Python37\lib\site-packages\sanic\app.py", line 187, in route
>   if not uri.startswith("/"):
> AttributeError: 'function' object has no attribute 'startswith'

**Code snippet**
if __name__ == "__main__":
    app.add_route("/", test_page)

**Expected behavior**
The route should be created and the program continues running.

**Environment (please complete the following information):**
 - OS: Windows 10, up to date
 - Version [e.g. 0.8.3] Python 3.7 + 3.8, Sanic Version: 19.12.2

**Additional context**
For my usecase I can't use the decorator and so I tried using app.add_route and the error occurs.

**Comment by Tronic** [comment]
You should use `app.add_route(test_page, "/")` (parameter order mixed up). Also, consider using `@app.get("/")` decorator in front of your handler function, unless you have a good reason to use `add_route` instead.

**Comment by Bevan0** [comment]
Yep, I had the order mixed up. Thanks for the help!
