### ISSUE TITLE
No longer works in newer version

### ISSUE THREAD

**Issue by zzxjl1** [huge-success/sanic#1855]
```
@app.route('/live2d/<file>')
@app.route('/live2d/model')
@app.route('/live2d/motions/<file2>')               
async def live2d(request,file=None,file2=None):
```

**Comment by ashleysommer** [comment]
Duplicate of https://github.com/huge-success/sanic/issues/1742

This is broken in v19.12.0, and v19.12.2. Is fixed (should be) in v20.03, and fix will also be in an upcoming release v19.12.3

**Comment by ashleysommer** [comment]
Try this workaround until you get the bugfix: https://github.com/huge-success/sanic/issues/1742#issuecomment-572050336

**Comment by zzxjl1** [comment]
🆗,thanks!
