### ISSUE TITLE
sanic How to do data validation

### ISSUE THREAD

**Issue by mochounan** [huge-success/sanic#1859]
as an asynchronous framework, does sanic have a rest framework data serialization tool similar to Django

**Comment by ahopkins** [comment]
Sanic follows more in the model of Flask where it is a mire barebones structure and the developer adds the tools they want; less opinionated.

There are [some tools on awesome-sanic](https://github.com/mekicha/awesome-sanic#api), and you can easily integrate something like [marshmallow](https://marshmallow.readthedocs.io/en/stable/), [pydantic](https://pydantic-docs.helpmanual.io/), or [middle](https://github.com/vltr/middle).

Personally, I have had good luck with marshmallow. But, here is [another project](https://github.com/kodemore/gata) I found that leverages dataclasses that looks promising.

**Comment by ahopkins** [comment]
Closing, but feel free to continue the conversation or ask questions. If you would like some more specific help on how you might use a tool like this to roll your own solution, post a message on the [community forums](https://community.sanicframework.org/).
