### ISSUE TITLE
sanic Response Streaming 'write socket.send() raised exception' warning when client close

### ISSUE THREAD

**Issue by beruhan** [huge-success/sanic#1870]
**Describe the bug**
I used sanic Streaming function to  provide mjpg service ,It seems `response.write` logging warning 'write socket.send() raised exception' instead of raise execption .does has any way to check the client is closed?

**Generate mjpg handler**
async def snapshot_stream_handler(request):
    """generate mjpeg stream from jpeg"""

    async def stream_camera_fn(response):
        while True:
            jpeg_bytes = b"xxxxxx"
            data = b"".join([b'--frame\r\nContent-Type: image/jpeg\r\n\r\n', jpeg_bytes, b'\r\n'])
            await response.write(data)
            # I want to break when client closed
    return response.stream(stream_camera_fn, content_type='multipart/x-mixed-replace; boundary=frame')

**Expected behavior**
when client closed server should raise exception,.

**Environment (please complete the following information):**
 - OS: ubuntu16.04
 - python3.6.8
- sanic 20.3.0

**Comment by Tronic** [comment]
Thanks for reporting!

I believe that this is one of the bugs fixed in the huge-success/sanic:streaming branch. I can help triaging if someone wants to try fixing this in the master branch (it's been a few months since I looked into that code so I don't remember the specifics anymore).
