### ISSUE TITLE
[Feature Request] Access the ID of the Worker the Request is being served from.

### ISSUE THREAD

**Issue by Lagicrus** [huge-success/sanic#1872]
**Describe the solution you'd like**
When a request comes in, being able to access the ID of the worker via something similar to `request.app.worker.id` or `request.worker.id`. With each spun up worker being a unique ID.

**Additional context**
The main idea behind this is the Snowflake ID system, where one of the "helpers" to prevent a duplicated ID, is the ID of the worker it is running on. 
[Twitter has a small doc on it](https://developer.twitter.com/en/docs/basics/twitter-ids)
[Same for discord](https://discord.com/developers/docs/reference#snowflakes)

**Comment by Tronic** [comment]
Sanic does not number the workers in any way. They are all forks or subprocesses of the main process, only with an open server socket handed over along with the information that they are workers. Thus each worker is identical in all respects except for the PID and any per-worker tasks currently being performed.

**Comment by ahopkins** [comment]
Agreed. If anything I would say we could grab the pid, and insert it, but I'm not sure this adds much that couldn't easily  be done at server startup, for example. Closing for now, feel free to continue the conversation.

**Comment by Lagicrus** [comment]
Makes sense @Tronic 👌 Thanks
