### ISSUE TITLE
Open Tracing is not working for multiple workers

### ISSUE THREAD

**Issue by WoodyFleurant** [huge-success/sanic#1877]
**Describe the bug**
Whenever configuring more than 1 worker, traces are not properly handled, and cannot be visualized into jaeger ui

**Code snippet**
hello.py
```
from sanic import Sanic
from sanic import response
from sanic_opentracing import SanicTracing
from jaeger_tracer import jaeger_tracer

app = Sanic(__name__)
_tracing = SanicTracing(tracer=jaeger_tracer, trace_all_requests=True, app=app)


@app.route("/example1")
async def example1(request):
    return response.json("example1")


@app.route("/example2")
async def example2(request):
    return response.json("example2")

if __name__ == "__main__":
    app.run(port=8000, host="0.0.0.0", workers=2, debug=True)
```
jaeger_tracer.py
```
import os
from jaeger_client import Config

JAEGER_HOST = os.environ.get("JAEGER_HOST ", "localhost")

config = Config(
    config={
        "sampler": {"type": "const", "param": 1},
        "logging": True,
        "local_agent": {"reporting_host": JAEGER_HOST},
    },
    service_name="Sanic-Double-Worker",
)
jaeger_tracer = config.initialize_tracer()
```

**Expected behavior**
Traces should be saved even if there is more than 1 worker

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Sanic Version 19.3.1 and 20.3.0

**Steps to reproduce**
Launch jaeger
`docker run -d -p6831:6831/udp -p16686:16686 jaegertracing/all-in-one:latest`
Install dependencies
`pip install -r requirements.txt`
requirements.txt
```
sanic==20.3.0
sanic_opentracing==0.8
jaeger-client==4.3.0
```
Start server
`python3 hello.py`

Reach endpoint http://localhost:8000/example1
Check if service is available in jaeger-ui : http://127.0.0.1:16686/
You should not see the service "Sanic-Double-Worker"

Now kill the server and put 1 worker, follow the same steps and you will be able to see traces for that service

**Comment by Tronic** [comment]
I am not familiar with Jaeger but as I understand this is some sort of tracing debugger. I've noticed that even Python's coverage module cannot track multiple processes under MacOS due to some yet unresolved bugs (according to docs it should work). Does this work if you run Sanic under Linux (e.g. in Docker VM running on MacOS)?

**Comment by ahopkins** [comment]
I am closing for now. For any further question or discussion, please move it to the plugin responsible for this: https://github.com/itechub/sanic-opentracing
