### ISSUE TITLE
Lazy loading in Sanic

### ISSUE THREAD

**Issue by nikhilpatil02** [huge-success/sanic#1879]
Hi Guys,

I have a requirement for lazy loading using sanic. There are thousands of records in database and we want to fetch batch by batch. Can anyone suggest how it can be done in sanic.

We tried using stream however stream data is loaded when all the data is fetched.

please suggest

**Comment by Tronic** [comment]
Which database are you using? In general you'll want an async database library like https://github.com/MagicStack/asyncpg and then use a *scrollable cursor* for reading data from database, possibly combined with `StreamingHTTPResponse` of Sanic.

**Comment by nikhilpatil02** [comment]
We are using postgres for same

**Comment by Tronic** [comment]
Not sure how you'd fetch data with Gino. You'll need to check the docs or ask their forums.

**Comment by ahopkins** [comment]
I usually accomplish this client side and with my API definition. 

The endpoint knows to accept `count` and  `offset` query parms, which are then passed to the data fetching layer. (I've also never used GINO). Determining which items to fetch would be handled by the client side library.

What does the frontend look like?

**Comment by nikhilpatil02** [comment]
We are using react native. Will stream in Sanic and Gino work together to solve this ?

**Comment by ahopkins** [comment]
It should. Please feel free to post back with any implementation you came up with for the benefit of anyone else in the future. Let us know if you have any other questions.
