### ISSUE TITLE
Spawn mode is incompatible with route decorators

### ISSUE THREAD

**Issue by Tronic** [huge-success/sanic#1883]
This sets "spawn" mode, earlier "fork" was used on Linux and MacOS (Windows only supports "spawn"):
https://github.com/huge-success/sanic/blob/master/sanic/server.py#L930

As a result, with current master, this doesn't work:
```python
from sanic import Sanic

app = Sanic(__name__)

@app.get("/")
def hello(req):
    pass

app.run(workers=2)
```

```
_pickle.PicklingError: Can't pickle <function hello at 0x10ff18160>: it's not the same object as __main__.hello
```

_Originally posted by @Tronic in https://github.com/huge-success/sanic/pull/1641#issuecomment-650778254_

**Comment by Tronic** [comment]
Possible fix: make decorators return the same function object?

Workaround: call the decorator so that "hello" remains the original bare function
```python
app.get("/")(hello)
```

Workaround 2: Revert #1853's default mode change, and keep using `fork` on Linux and MacOS. Problems: fork is not recommended on MacOS and is not supported at all on Windows.

**Comment by ashleysommer** [comment]
@Tronic 
The mode change in #1853 was not meant to be included, it was there from testing and was accidentally bundled with the PR.
I'm making a PR to revert it back to "fork" now.

**Comment by ashleysommer** [comment]
PR Here: https://github.com/huge-success/sanic/pull/1884
Its unfortunate looks like 20.6 release was pushed with this bug still in the code

**Comment by ahopkins** [comment]
[See v20.6.3](https://github.com/huge-success/sanic/blob/master/CHANGELOG.rst#version-2063)

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/multiprocessing-is-currently-not-supported-on-nt/827/2
