### ISSUE TITLE
Breaking request by user in the middle of the work

### ISSUE THREAD

**Issue by tomaszdrozdz** [huge-success/sanic#1898]
I have a handler like:  

    @app.route("/test")
    def handler(request):  
        request.app.config["XXX"] = True  
        await asyncio.sleep(30)  
        del request.app.config["XXX"]  
        return sanic.response.text("Done")  

If I open "/test" in my web browser and wait for 30 seconds,  
then firts "XXX" is added to app.config and then deleted from it.  

But if I open "/test" in my web browser and stop the request (e.g. close web browser) before 30 seconds,  
then firts "XXX" is added to app.config,  
but then never deleted from it  
and this is not what I want.  
I want in such case "XXX" was also deleted from app.config.  

How to aproach this ?

**Comment by Tronic** [comment]
Perhaps you should be using `request.ctx`, if you only wish to store some custom data for that one request, and not actually change Sanic config while processing requests. Changing `request.app.config` will affect all other requests being served at the same time, and probably doesn't do what you want.

**Comment by tomaszdrozdz** [comment]
Actually I want it to be in app.config so all "code" other request can check if this variable is set or not.

**Comment by tomaszdrozdz** [comment]
Or Maybe I should ask the question in other words:

How to "clean up" when Yuser interupt request ?

**Comment by ashleysommer** [comment]
Hi @tomaszdrozdz 
This is how to do what you're asking:
```
@app.route("/test")
async def handler(request):
    request.app.config["XXX"] = True
    try:
        await asyncio.sleep(30)
    except asyncio.CancelledError as c:
        print("was cancelled")
    finally:
        del request.app.config["XXX"]
    return text("Done")
```

**Comment by ashleysommer** [comment]
BTW, my project [SanicPluginsFramework](https://github.com/ashleysommer/sanicpluginsframework) has a feature similar to this built in, called "Cleanup" middleware.

Its used like this:
```python3
#Add attach_to='cleanup' to make this run even when the Response is None.
#This queue is fired _after_ response is already sent to the client.
@my_plugin.middleware(attach_to='cleanup')
def my_middleware(request):
    # Do per-request cleanup here.
    return None
```
The cleanup middleware runs after every request, whether it completed normally, encountered an exception, or was cancelled (broken connection).

If you don't want to write your application as a plugin to take advantage of this feature, you can use the handy micro-plugin that SPF comes shipped with, called `contextualize`:

```python3
from sanic import Sanic
from sanic.response import text
from spf import SanicPluginsFramework
from spf.plugins.contextualize import instance as ctx

app = Sanic(__name__)
spf = SanicPluginsFramework(app)

@ctx.route("/test")
async def handler(request, context):
    request.app.config["XXX"] = True
    await asyncio.sleep(30)
    return text("Done")

@ctx.middleware(attach_to="cleanup")
def cleanup_middleware(request, context):
    del request.app.config["XXX"]

ctx = spf.register_plugin(ctx)
if __name__ == "__main__":
    app.run(debug=True, auto_reload=False)
```

You can even use the shared context feature of Contextualize, to avoid using app.config.
```python3
from sanic import Sanic
from sanic.response import text
from spf import SanicPluginsFramework
from spf.plugins.contextualize import instance as ctx

app = Sanic(__name__)
spf = SanicPluginsFramework(app)

@ctx.route("/test")
async def handler(request, context):
    shared_context = context.shared
    shared_context["XXX"] = True
    await asyncio.sleep(30)
    return text("Done")

@ctx.middleware(attach_to="cleanup")
def cleanup_middleware(request, context):
    shared_context = context.shared
    del shared_context["XXX"]

ctx = spf.register_plugin(ctx)
if __name__ == "__main__":
    app.run(debug=True, auto_reload=False)
```

See SPF [Examples](https://github.com/ashleysommer/sanicpluginsframework/tree/master/examples) for more info, specifically the [Contextualize Example](https://github.com/ashleysommer/sanicpluginsframework/blob/master/examples/contextualize_example.py).

**Comment by tomaszdrozdz** [comment]
Thank You :-)
