### ISSUE TITLE
Access logs showing twice

### ISSUE THREAD

**Issue by LM1LC3N7** [huge-success/sanic#1910]
Hello,

I have the exact same problem that #1095: access logs are duplicated in the console. 
One line starts with `sanic.access` and the other one with a date, then `sanic.access`. Both have the exact same content. 

* sanic version: 20.6.3
* OS version: CentOS 7
* Python version: 3.7.8

app.py:

```python
#!/usr/bin/env python3.7

# Import dependencies
from sanic import Sanic, response
from sanic.log import logger, logging
from sanic.response import text, json
import sanic # for sanic.log.LOGGING_CONFIG_DEFAULTS
import ssl
# For documentation
from sanic_openapi import swagger_blueprint

# Import routes modules
from routes.threats.threats import api_threats
from routes.users.users import api_users
from routes.summary import api_summary
from routes.consoles import api_consoles

## Create Sanic app
app = Sanic("Monitoring Server", log_config=sanic.log.LOGGING_CONFIG_DEFAULTS)
app.config.from_pyfile('config/config.ini')
appconfig = app.config

# Change logging level
loglevel = app.config.DEBUG_LEVEL
logger.setLevel(loglevel)
# Remove dual messages for sanic.root
logging.getLogger("sanic.root").handlers.clear()

# Apply same logging level for imported modules
logging.getLogger("filelock").setLevel("WARNING")
logging.getLogger("urllib3").setLevel(loglevel)
logging.getLogger("requests").setLevel(loglevel)

ssl = {'cert': app.config.CERT, 'key': app.config.KEY}

## Import API routes
app.blueprint(api_threats)
app.blueprint(api_users)
app.blueprint(api_summary)
app.blueprint(api_consoles)
if (loglevel == "DEBUG"):
   app.blueprint(swagger_blueprint)

## Routes - Static files
app.static('/static/css/', 'static/css/')
app.static('/static/js/', 'static/js/')
@app.route('/')
async def index(request):
   logger.info('Serving web app index page.')
   return await response.file('static/html/index.html')


## Main to start the server
if __name__ == '__main__':
   app.run(host='0.0.0.0',
           port=app.config.PORT,
           ssl=ssl,
           workers=app.config.WORKERS,
           auto_reload=app.config.AUTO_RELOAD,
           access_log=app.config.ACCESS_LOGS,
           debug=False)
```

config/config.ini:

```python
VERSION = "0.1"
PORT = 8080
COMMENT_____DEBUG_LEVEL = "DEBUG / INFO / WARNING / ERROR"
DEBUG_LEVEL = "INFO"
ACCESS_LOGS = True
CERT = "certs/server.crt"
KEY = "certs/server.key"
GRACEFUL_SHUTDOWN_TIMEOUT = 1
WORKERS = 1
AUTO_RELOAD = False
```

Am I missing something?

**Comment by LM1LC3N7** [comment]
Here a log example I get:

```bash
[2020-08-18 10:45:27 +0200] - (sanic.access)[INFO][1.2.3.4:14458]: GET https://1.2.3.4:8080/  200 553
[sanic.access][2020-08-18 10:45:27,775] [INFO] [server.py:494]
[2020-08-18 10:45:31 +0200] - (sanic.access)[INFO][1.2.3.4:14458]: GET https://1.2.3.4:8080/test  500 41
[sanic.access][2020-08-18 10:45:31,982] [INFO] [server.py:494]
```

**Comment by ZinkLu** [comment]
The second log record looks like use a totally customized formatter. I did'nt find any format in sanic source code.
Did you:
1. start the sanic app with a server software such as uvicorn?
2. modify the logger's handler by mistake ?
3. config root logger like [https://github.com/huge-success/sanic/pull/1095](url) did? In this case, The logger logged twice because root logger has been config, and "sanic.root" logger doesn't set `propagate = False`, so the message will be passed to the parent logger.

**Comment by LM1LC3N7** [comment]
I have past my entire main python script.
Every sanic configuration is done through this file (`app.py`).
<br>

> 1. start the sanic app with a server software such as uvicorn?

No, just `./app.py`.

> 2. modify the logger's handler by mistake ?

I don't think so, or this was not intentional.

> 3. config root logger like https://github.com/huge-success/sanic/pull/1095 did? In this case, The logger logged twice because root logger has been config, and "sanic.*" logger doesn't set propagate = False, so the message will be passed to the parent logger

My file content is past in my first post. It does not seems that I have configured root logger, that is why I am asking for help 😄 


I tried to add this, but it does not change anything:

```python
logger.root.propagate = False
```

**Comment by ZinkLu** [comment]
you sholud set the sanic's logger rather than the root logger:

```python
import logging

logging.getLogger("sanic.access").propagate = False
logging.getLogger("sanic.root").propagate = False
```

Have you checked all the loggers and their handlers ?

**Comment by LM1LC3N7** [comment]
I tried adding this code, without more success.

Also adding this make all logs disappear except for the lines I want to remove, starting with `[sanic.access]`.

```python
logging.root.level = logging.NOTSET
logging.getLogger("sanic.root").handlers.clear()
logging.getLogger("sanic.access").handlers.clear()
```

Logs:

```python
[sanic.root][2020-08-18 16:18:08,920] [INFO] [app.py:1386] Goin' Fast @ https://0.0.0.0:8080
[sanic.root][2020-08-18 16:18:08,924] [INFO] [server.py:906] Starting worker [3462]
[sanic.access][2020-08-18 16:18:10,731] [INFO] [server.py:494]
[sanic.access][2020-08-18 16:18:10,882] [INFO] [server.py:494]
[sanic.access][2020-08-18 16:18:10,941] [INFO] [server.py:494]
[sanic.access][2020-08-18 16:18:10,992] [INFO] [server.py:494]
[sanic.access][2020-08-18 16:18:11,939] [INFO] [server.py:494]
[sanic.access][2020-08-18 16:18:11,940] [INFO] [server.py:494]
[sanic.root][2020-08-18 16:18:15,886] [DEBUG] [server.py:284] KeepAlive Timeout. Closing connection.
[sanic.root][2020-08-18 16:18:17,131] [DEBUG] [server.py:284] KeepAlive Timeout. Closing connection.
[sanic.root][2020-08-18 16:18:17,131] [DEBUG] [server.py:284] KeepAlive Timeout. Closing connection.
```

With this code, everthing is fine but there is not more debug logs `[sanic.root]` that shows from which file the call is made.

```python
## Create Sanic app
app = Sanic("Monitoring Server", log_config=sanic.log.LOGGING_CONFIG_DEFAULTS)
app.config.from_pyfile('config/config.ini')
appconfig = app.config

# Change logging level
loglevel = app.config.DEBUG_LEVEL
logger.setLevel(loglevel)
# # Remove dual messages
logging.getLogger("sanic.access").propagate = False
logging.getLogger("sanic.root").propagate = False

# Apply same logging level for imported modules
logging.getLogger("filelock").setLevel("WARNING")
logging.getLogger("urllib3").setLevel(loglevel)
logging.getLogger("requests").setLevel(loglevel)
```

**Comment by LM1LC3N7** [comment]
Logs **without** `logging.getLogger("sanic.root").propagate = False`

```python
[2020-08-18 16:54:18 +0200] [4330] [DEBUG]

                 Sanic
         Build Fast. Run Fast.


[sanic.root][2020-08-18 16:54:18,743] [DEBUG] [app.py:1372]

                 Sanic
         Build Fast. Run Fast.


[2020-08-18 16:54:18 +0200] [4330] [INFO] Goin' Fast @ https://0.0.0.0:8080
[sanic.root][2020-08-18 16:54:18,743] [INFO] [app.py:1386] Goin' Fast @ https://0.0.0.0:8080
[2020-08-18 16:54:18 +0200] [4330] [INFO] Starting worker [4330]
[sanic.root][2020-08-18 16:54:18,747] [INFO] [server.py:906] Starting worker [4330]
```

Logs with `logging.getLogger("sanic.root").propagate = False`

```python
                 Sanic
         Build Fast. Run Fast.


[2020-08-18 16:53:31 +0200] [3511] [INFO] Goin' Fast @ https://0.0.0.0:8080
[2020-08-18 16:53:31 +0200] [3511] [INFO] Starting worker [3511]
```

**Comment by ZinkLu** [comment]
Sanic's parent logger denfintely been modified there. The log record has been passed to the parent logger without `logging.getLogger("sanic.root").propagate = False`, check if there was a modification on root logger in other palce(may be other packages).

**Comment by LM1LC3N7** [comment]
Ok, indeed if I remove my custom module from the main sanic file, there is no more duplicated lines with `[sanic.root]`.

```python
# this cause duplicated logs
# import workers.workers as workers
```

But in that file I import other custom modules, where I start new processes and threats.
For debugging purpose I need to use `logger.debug()` and `logger.info()`.

For now, in all of my modules I import `logger`:

```python
from sanic.log import logger

deg my_function():
    logger.debug("debug message: {}".format(my_var))
```

Is this the correct way to use sanic logger?

**Comment by LM1LC3N7** [comment]
For now I do not understand when this kind of logs is activated or not, I never modify `logger` in my modules, I only use `logger.debug()` or `logger.info()` or `logger.err()`.


The ideal solution would be to activate `[sanic.root]` logs only when log level is set to `DEBUG`, for example:

`loglevel=DEBUG`

```python
[sanic.root][2020-08-18 16:54:18,747] [INFO] [server.py:906] Starting worker [4330]
```

`loglevel=INFO`

```python
[2020-08-18 16:54:18 +0200] [4330] [INFO] Starting worker [4330]
```

**Comment by ZinkLu** [comment]
You definitily can use sanic logger in you code, either you can create you own logger.

Did you mean you want to set `sanic.root` log only under `DEBUG` level? perhaps you should try `Filter` in `Handler`?

Here is a quick example:

```python
from sanic import Sanic
from sanic.log import logger
import logging


class MyFilter(logging.Filter):
    def __init__(
            self,
            level,
            name='',
    ):
        super(MyFilter, self).__init__(name)
        self.level = level

    def filter(self, record):
        if self.level != logging.DEBUG:
            return False
        return True


app = Sanic("YOU APP", )
for handler in logger.handlers:
    handler.addFilter(MyFilter(level=logging.INFO))  # set you level here

app.run()
```

Or maybe try to read the official document to do your logging setup.
