### ISSUE TITLE
Trying to run a Discord bot with Sanic at the same time

### ISSUE THREAD

**Issue by Vincysuper07** [huge-success/sanic#1911]
I got this code:
```python
bota = my_bot_class().run(token)
botb = asyncio.ensure_future(bota)

sanica = app.create_server(host="0.0.0.0", port=8765)
sanicb = asyncio.ensure_future(sanica)

loop.run_forever()
```
But when I run it, it runs the Discord bot first, and Sanic doesn't start. Is there a way to run Sanic and a bot at the same time?

**Comment by ahopkins** [comment]
It is hard to know without seeing your bit code.

Just curious, why are you trying to run them on the same loop? Generally this is not advisable to have two services in the same process using the same loop.

**Comment by Vincysuper07** [comment]
> It is hard to know without seeing your bot code.
Here it is:
```
import discord, os, asyncio
from sanic import Sanic
from discord.ext import commands
from sanic.response import json
from dotenv import load_dotenv
load_dotenv()
token = os.getenv("TOKEN")
loop = asyncio.get_event_loop()
app = Sanic(__name__)


@app.route("/bot/get_data")
async def get_tdb_data(request):
    return json({
        "online": True
    })

class my_bot_class(commands.Bot):
    def __init__(self):
        super().__init__(command_prefix=".")

    async def on_ready(self):
        print("Logged in.")

# the code i mentioned before is here...
```
> Just curious, why are you trying to run them on the same loop?
Because I want to make something for the bot status, online or offline

**Comment by ahopkins** [comment]
Can you start your bot in a listener?

https://sanic.readthedocs.io/en/latest/sanic/middleware.html#listeners

**Comment by Vincysuper07** [comment]
Okay, I tried with listeners, but, when I run the code, it starts up Sanic, but it, instead of "Starting worker" that starts server, it shows the "Logged in" thing that says the bot is logged in. CTRL+C just exits without starting server.
This is the code I used:
```python
@app.listener('before_server_start')
async def bot_startup(app, loop):
    print("Starting up bot...")
    await my_bot_class().start(token)

@app.listener('after_server_start')
async def notify_server_started(app, loop):
    print('Bot successfully started!')

@app.listener('before_server_stop')
async def notify_server_stopping(app, loop):
    print('Shutting down!')

@app.listener('after_server_stop')
async def bot_logout(app, loop):
    await my_bot_class().logout()
```

**Comment by ahopkins** [comment]
Your bot doesn't look like it needs access to the loop. In that case, I'd suggest running it from a listener and using `app.add_task`.

**Comment by sjsadowski** [comment]
@Vincysuper07 you'd likely be better off completely decoupling these two functions and using a k/v store that is read by Sanic and written by the bot in its own loop. The way you have it now, they're tightly coupled - which means that if the bot is offline, the Sanic server probably is too; though not necessarily guaranteed. It's going to add lots of complexity to manage the state of both your web service and your bot service in the same loop.

**Comment by ahopkins** [comment]
I agree with @sjsadowski. If your plan is to put this anywhere near pofuctonw, they should be on separate processes.

**Comment by Vincysuper07** [comment]
I managed to fix with this:
```python
@app.listener('before_server_start')
async def bot_startup(app, loop):
    loop.create_task(my_bot_class().start(token))

@app.listener('before_server_stop')
async def notify_server_stopping(app, loop):
    await my_bot_class().logout()
```
This is perfectly working as I wanted. Thanks everyone for help!

**Comment by Tronic** [comment]
Just be sure not to run Sanic with multiple workers or you'll get multiple bots too. Autoreloader should work but you might not want your bot restarting and losing connection every time the code is changed, so you probably don't want to use that either.

**Comment by ahopkins** [comment]
Also, there is a convenience wrapper `app.add_task` for where the loop is not available.
