### ISSUE TITLE
Exception occured while handling uri: unknown

### ISSUE THREAD

**Issue by xMistt** [huge-success/sanic#1915]
**Describe the bug**
Randomly I get the exception:
```py
[2020-08-24 04:50:26 +0100] [2348] [ERROR] Exception occurred while handling uri: unknown
NoneType: None
```

**Code snippet**
No code as I don't know causes this error.

**Expected behavior**
No exception.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version: 19.12.2

**Additional context**
I've got a websocket server running in the same script but when receiving/connecting/sending messages, the exception isnt raised then, it's raised randomly.

**Comment by ahopkins** [comment]
What kind of exception handlers do you have? Is this a full blown app or an MVP? Possibly something in your Middleware is messing up the request object. Have you tried to narrow it down at all?

**Comment by xMistt** [comment]
I've got no middleware.

**Comment by xMistt** [comment]
And exception handler? Is this some sort of event?

**Comment by ahopkins** [comment]
can you provide any kind of code snippet?

**Comment by xMistt** [comment]
No code in particular causes this so I'm not sure what snippet of code to send, want the full code?

**Comment by ahopkins** [comment]
If you don't mind. It is near impossible to figure it out without knowing what you are running. 😬

**Comment by xMistt** [comment]
Here is my source code from the script that I get the error from: https://hastebin.com/nuhuwobugu.py

**Comment by sjsadowski** [comment]
I stripped out everything unrelated to sanic, and it works fine: https://gist.github.com/sjsadowski/a2c5dc52967d3a68c0083370c1477334

I think your problem is with something not-sanic.

**Comment by xMistt** [comment]
Is there any way to just ignore these exceptions?

**Comment by ahopkins** [comment]
You are running two servers from the same loop? This is definitely a less than ideal setup. Two things:

1. Sanic [has websocket handlers](https://sanic.readthedocs.io/en/latest/sanic/websocket.html). There is no need to run a seperate service.
1. If you _need_ to keep it seperate (different domain/port/etc), then it should be done in a separate process.

I have not run the code to look at it, but I suspect this is a problem.

---

Last thing, running Sanic this way is less than ideal. I would not suggest using `run_until_complete` and `run_forever` unless you absolutely have to. For _most_ situations where you need to run something along side Sanic (and need access to the loop), it should be done in [a listener](https://sanic.readthedocs.io/en/latest/sanic/middleware.html#listeners).

> Application developers should typically use the high-level asyncio functions, such as asyncio.run(), and should rarely need to reference the loop object or call its methods. This section is intended mostly for authors of lower-level code, libraries, and frameworks, who need finer control over the event loop behavior

[Source](https://docs.python.org/3/library/asyncio-eventloop.html#event-loop)

**Comment by sjsadowski** [comment]
@ahopkins I will try and add a best practices document for communication between two servers using a queue. It seems like we're answering this question/pattern of thinking very often because of the assumption that in order to communicate, these things need to be running in the same loop in the same application.

**Comment by ahopkins** [comment]
> I will try and add a best practices document for communication between two servers using a queue

I can do you one better. I am working on a user guide (will send you the repo) to hold lots of examples and a more tutorial style walk through of Sanic.

**Comment by sjsadowski** [comment]
I'll put it there, seems like a great place for it.

**Comment by rgmuslin** [comment]
I'm having the same issue, and I've figured out that _some_ of its appearences are due to large incoming POST requests. Testing it with curl I got

> \> User-Agent: curl/7.58.0
> \> Accept: */*
> \> Content-Type: application/x-tar
> \> Content-Length: 593496727
> \> Expect: 100-continue
> \>
> \< HTTP/1.1 413 Request Entity Too Large
> \< Connection: close
> \< Content-Length: 24
> \< Content-Type: text/plain; charset=utf-8
> \<
> \* Excess found in a non pipelined read: excess = 25, size = 24, maxdownload = 24, bytecount = 0
> \* Closing connection 0
> Error: Payload Too Large

and the message from Sanic is exactly as given by @xMistt :

> 2022-02-15 08:59:10,874 [2149]  sanic.root      Exception occurred while handling uri: unknown
> NoneType: None
> 2022-02-15 08:59:10,875 [2149]  sanic.access

Hence the question: is this kind of exception an expected behavior in such (and other?) cases, or it can be be avoided/handled somehow? Sorry, if I missed something from the documentation and thanks in advance for any advice.

**Comment by ahopkins** [comment]
If it is responding as expected with a 413, then yes. The uri is unknown because it has not parsed yet when that has run.

**Comment by Tronic** [comment]
Shouldn't the URI be available even with 413? The request line and header have been read and parsed (for content-length which causes the exception), and Sanic showing the affected URL and a proper diagnostic would be expected.

**Comment by rgmuslin** [comment]
In my case the proper diagnostic is actual _indeed_, as the actual (not a debugging-with-curl one) request to Sanic is made by a third party service, to which I do not have access (I'm only specifying Sanic server's URL as a callback parameter).

**Comment by ahopkins** [comment]
The URI has been parsed out into the `request.head` but routing does not happen until it hits the handler lifecycle.
