### ISSUE TITLE
Pull route templater out to a utility function

### ISSUE THREAD

**Issue by vishalkuo** [huge-success/sanic#1918]
**Is your feature request related to a problem? Please describe.**
Currently, the route template logic is built into the `router` [code](https://github.com/huge-success/sanic/blob/master/sanic/router.py#L222-L245). In order to utilize this parser for a string, you need to instantiate a router and do some hacky iterating:
```python
r = Router()
r.add(uri="/hello/<name>/<age>", method=["GET"], handler="empty")
for k, v in list(r.routes_all.items())[:-1]:
    print(k ,v)
```

**Describe the solution you'd like**
It'd be nice if we had a utility function that had the following behavior:
```
from sanic.utilities import parse_route_uri

parse_route_uri("/hello/<name>/<age>")
RouteInfo(pattern=re.compile('^/hello/([^/]+)/([^/]+)$'), parameters=[Parameter(name='name', cast=<class 'str'>), Parameter(name='age', cast=<class 'str'>)], name=None, uri='/hello/<name>/<age>'))
``` 

I'd be happy to take a stab at a PR if this would be welcome
**Additional context**

The reason we're looking for this is so that we can do some simple analysis / schema work with our routes

**Comment by ahopkins** [comment]
This is definitely an interesting idea, and while I appreciate the offer of a PR. I am afraid it is effort probably wasted. [We are likely to replace the router](https://community.sanicframework.org/t/a-fast-new-router/649) completely after the next LTS. I will, however take this into consideration when drafting the RFC (in the works now).

In the meantime, here is a snippet to do it programatically. I opt for a `DummyRequest` here because it is a far simpler object.

```python
class DummyRequest:
    def __init__(self, path, method):
        self.path = path
        self.method = method

@app.get("/")
async def root(request):
    result = request.app.router.get(DummyRequest("/bar", "GET"))
    print(f"{result=}")
    return text("Done.")

@app.get("/<foo>")
async def do_foo(request, foo):
    return text("Done.")
```

```
result=(<function do_foo at 0x7f97ca3a4ee0>, [], {'foo': 'bar'}, '/<foo>', 'do_foo')
```

**Comment by vishalkuo** [comment]
I'm not sure this completely solves my use case. What I'm looking to pull out here is the shape of `/<foo>` - i.e. if my url were more complex `/<foo:string>/<bar:int>/` i'd like `[Parameter(name='foo', cast=<class 'str'>), Parameter(name='bar', cast=<class 'int'>)]` somehow (im mostly trying to avoid duplicating the regex here). 

Let me know if I'm misunderstanding

**Comment by ahopkins** [comment]
This will allow you to do that.
