### ISSUE TITLE
Evaluate request uri template in middleware

### ISSUE THREAD

**Issue by vishalkuo** [huge-success/sanic#1919]
**Is your feature request related to a problem? Please describe.**
https://github.com/huge-success/sanic/issues/1115 explains that we don't have the request's `uri_template` available to us. Ideally that wouldn't be the case _or_ we'd have a function like `evaluate_uri` that would just return the URI from the router similar to [https://github.com/huge-success/sanic/blob/3fe31ff551c7888249f6e1d19829f5f3b8f298bf/sanic/app.py#L571](https://github.com/huge-success/sanic/blob/3fe31ff551c7888249f6e1d19829f5f3b8f298bf/sanic/app.py#L571) but more lightweight.

**Describe the solution you'd like**
Middleware either populate the request URI OR
we expose a helper to evaluate the URI

Happy to help with either if this seems reasonable

**Additional context**
Add any other context or sample code about the feature request here.

This would make certain monitoring tasks like tracing much easier to manage.

**Comment by vishalkuo** [comment]
Actually - we've figured out a workaround (our tracing system can accept the URI template after the request has been completed, as well)

**Comment by ahopkins** [comment]
As mentioned in#1918, this is taken into consideration in the router RFC I am working on.
