### ISSUE TITLE
Explicit ASGI support in homepage README

### ISSUE THREAD

**Issue by raphaelauv** [huge-success/sanic#1920]
**Is your feature request related to a problem? Please describe.**
It's absolutely not obvious that sanic is now ASGI compliant ( only a github tag with ASGI ). Since sanic was not at the begining compliant a lot of medium or web article do not talk about sanic.

**Describe the solution you'd like**
Explain the ASGI compliance of sanic in the readme homepage with a small one line example with uvicorn or hypercorn

with a link to the deployment documentation.

What do you think about it ?

**Comment by ahopkins** [comment]
Great idea. Would you like to make a PR?

There is some discussion here 
https://sanic.readthedocs.io/en/latest/sanic/deploying.html#running-via-asgi
