### ISSUE TITLE
server.HttpProtocol.write_error does not properly deal with error handlers that are coroutines

### ISSUE THREAD

**Issue by todddialpad** [huge-success/sanic#1926]
https://github.com/huge-success/sanic/blob/58e15134fdc934ff423a0c710dad76d45368d493/sanic/server.py#L601

write_error is called with an exception argument. It then looks up a handler for the exception type and calls the handler. But if the handler is a coroutine, the handler functionality is never scheduled or awaited.

This results in the interpreter emitting a RuntimeWarning because the coroutine is created but never awaited.

**Comment by Tronic** [comment]
I believe this is duplicate #1785.

**Comment by todddialpad** [comment]
Yes @tronic you are right. I see that now. Thanks.
