### ISSUE TITLE
Allow option at runtime to disable uvloop

### ISSUE THREAD

**Issue by BobCashStory** [huge-success/sanic#1930]
**Is your feature request related to a problem? Please describe.**
I'm using sanic with papermill, papermill is not compatible for now with uvloop...
since i distribute my package in pip i don't want to ask my user to do 
```
export SANIC_NO_UVLOOP=true
export SANIC_NO_UJSON=true
pip3 install --no-binary :all: MYMODULE
```
It should be only simple install since for now only one way exist to install otherwise the module is broken .

**Describe the solution you'd like**
allow us to disable uvloop usage at runtime like `Sanic(no_uvloop=True)`
then it will let my users install my module like other one !
`pip3 install MYMODULE`

**Additional context**
Add any other context or sample code about the feature request here.

**Comment by BobCashStory** [comment]
For now my poor solutions is to import this before sanic
```
import os

class FixUvloop():
    
    def __init__(self):
        try :
            import uvloop
            with open(uvloop.__file__, 'w') as fp:
                fp.write("raise ImportError\n")
                pass
        except ImportError:
            pass

```

**Comment by ahopkins** [comment]
A+ for creative hacks!

Have you tried?

```python
asyncio.set_event_loop_policy(None)
```

**Comment by BobCashStory** [comment]
@ahopkins ahah your solution is way more reliable and works thanks <3

**Comment by ashleysommer** [comment]
I agree we do need a better mechanism to not install uvloop at all if your project doesn't need/want it. But that is not easy to do. The python _extras_ mechanism doesn't allow for _negative_ dependencies, so the environment variables are for now the only way to do it.
We can probably close this thread now.

**Comment by BobCashStory** [comment]
@ashleysommer Thanks for the answer, for now Sanic is a part of our module : https://github.com/jupyter-naas/naas
So i cannot force all my users to use env vars before install .

I was asking to allow us to disable it at runtime, since install it with is "okay".

I'm okay to install an "useless" dependency if users don't have to do custom install for one of my dependency.
I'm already doing it with `asyncio.set_event_loop_policy(None)`.
But it's a Hack solution, who create edge case since that not done inside Sanic.

Can you allow us to disable it at runtime in Sanic, like i suggest `Sanic(no_uvloop=True)` ?

**Comment by ahopkins** [comment]
> Can you allow us to disable it at runtime in Sanic, like i suggest `Sanic(no_uvloop=True)` ?
> 
> 

That is probably reasonable.  I would suggest that it belongs inside the `Sanic.run()` method since it applies to the server. And, I think that it would probably do the same thing: reset the policy.

As @ashleysommer mentioned, it is still not ideal because it leaves a fairly weighty dependency hanging around.

Perhaps another solution is to build out the docker images more, and provide some builds with and without uvloop.

**Comment by BobCashStory** [comment]
@ahopkins yes in `Sanic.run` it can be good too :)

**Comment by Tronic** [comment]
Minor note, please avoid negated flag names like `no_something=True` and use descriptive default values instead, could be `async_backend="auto"` (uvloop, asyncio, trio)

**Comment by sjsadowski** [comment]
@Tronic the no_ options predate the handoff of sanic to the current crew of maintainers, but generally I agree.
