### ISSUE TITLE
what is this error? how can i fix it?

### ISSUE THREAD

**Issue by sogand145** [huge-success/sanic#1934]
```python
File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/telebot-server/api.py", line 208, in get_post
    post_info = await connection.fetch(q)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 780, in __aexit__
    await self.pool.release(con)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 654, in release
    return await asyncio.shield(ch.release(timeout))
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 216, in release
    raise ex
  File "/usr/local/lib/python3.6/site-packages/asyncpg/pool.py", line 206, in release
    await self._con.reset(timeout=budget)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 1137, in reset
    await self.execute(reset_query, timeout=timeout)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/asyncpg/connection.py", line 295, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 316, in query
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "DO"
```

this is my code:
```python
async with request.app.config['pool'].acquire() as connection:
            q = f"""
            select
                 messages.message_id,
                 message_data.data as body,
                 groups.group_id,
                 files.file_path
            from messages left join message_data
                 on messages.data_ref = message_data.id
                 left join files
                     on messages.file_id = files.signature
                     left join groups
                         on messages.group_id = groups.group_id
            where
                messages.message_id = {int(data["message_id"][0])}
                and
                messages.group_id = {int(data["group_id"][0])};
            """
            post_info = await connection.fetch(q)
```

I'm using sanic and asyncpg

**Comment by sjsadowski** [comment]
There is an error in your SQL query, but without knowing both your database schema and your fully rendered query, it's nearly impossible to tell why.

**Comment by sogand145** [comment]
> There is an error in your SQL query, but without knowing both your database schema and your fully rendered query, it's nearly impossible to tell why.

I checked my queries
the result of queries is returned but when the pool connection should be released this error is occured

for example:
when i decided to run this query:
```sql
select count(*) from pg_stat_activity;
```
result of the query:
result +++++++++ [<Record count=7>] type :  <class 'list'>

I defined pool connection in main.py:
```python
@app.listener('before_server_start')
async def setup_server(app, loop):
    await define_global_variables()
    # Create a database connection pool
    conn = f"postgres://{config['DB']['USER']}:{config['DB']['PASSWORD']}@{config['DB']['HOST']}:{config['DB']['PORT']}/{config['DB']['DBNAME']}"
    app.config['pool'] = await asyncpg.create_pool(
                                            dsn=conn,
                                            min_size=10, #in bytes,
                                            max_size=10, #in bytes,
                                            max_queries=50000,
                                            max_inactive_connection_lifetime=300,
                                            loop=loop
                                           )
```

and have written a function for running queries, after running every query I release connection to pool
```python
await db_pool.release(pg_connection)
```

I checked postgres log of queries:
ERROR:  syntax error at or near "DO" at character 62
STATEMENT:  SELECT pg_advisory_unlock_all();
	CLOSE ALL;

	                DO $$
	                BEGIN
	                    PERFORM * FROM pg_listening_channels() LIMIT 1;
	                    IF FOUND THEN
	                        UNLISTEN *;
	                    END IF;
	                END;
	                $$;

	RESET ALL;

**Comment by sogand145** [comment]
I found it, vesion of postgres was :
postgres (PostgreSQL) 8.4.20 

asyncpg supports postgres 9.2 to up

**Comment by ashleysommer** [comment]
I'm glad you found what the problem is.
I had some postgres incompatibility issues the first time I used asyncpg too.
Just curious though, why did you open this issue on the Sanic project, instead of the asyncpg project issue tracker?

**Comment by sjsadowski** [comment]
@ashleysommer  I thought about asking too, but I  just kind of shrugged it off.

**Comment by sogand145** [comment]
> I'm glad you found what the problem is.
> I had some postgres incompatibility issues the first time I used asyncpg too.
> Just curious though, why did you open this issue on the Sanic project, instead of the asyncpg project issue tracker?

you're right, I made a mistake. sorry for that, in fact, this issue is not considered a bug of sanic, I only wanted to know the main reason :)

**Comment by sogand145** [comment]
> @ashleysommer I thought about asking too, but I just kind of shrugged it off.

you're right, I'm so sorry, I made a mistake

**Comment by ahopkins** [comment]
No worries @sogand145. The people here are generally happy to be helpful when possible. We do, however, encourage usage of [the community forums](https://community.sanicframework.org) when seeking help rather than the issues on GH.

**Comment by sogand145** [comment]
> the community forums

sure, right,  thank you so much @ahopkins  :)
