### ISSUE TITLE
Methods of classes cannot be used as blueprint routes

### ISSUE THREAD

**Issue by penn5** [huge-success/sanic#1943]
**Describe the bug**
Unable to define routes in classes

**Code snippet**
```python
class MyApp:
    def __init__(self):
        self.bp = Blueprint("app")
        self.bp.add_route(self.route, "/route")

    def route(self, request):
        return text("hi")
```

**Expected behavior**
Accessing /route says hi

**Actual behavior**
Including the blueprint fails with because trying to assign `__blueprintname__` on a method, but methods cannot have arbitrary attributes assigned.

**Environment (please complete the following information):**
19.12.2, and master

**Additional context**
Introduced in #1445

**Comment by ahopkins** [comment]
What is the motivation for this style api? Blueprints work really well in modules.

**Comment by penn5** [comment]
> What is the motivation for this style api? Blueprints work really well in modules.

I want to pass in some objects, and as we are in the middle of a refactor, I don't want it to be tied to any specific import - I want the database to be injected through the class constructor, rather than an import.

**Comment by ashleysommer** [comment]
Hi @penn5 
There is a workaround which doesn't involve hacking the sanic route mechanism.
You can turn the method into a function using `functools.partial` and `functools.wraps` like this:

```
from functools import partial, wraps
class MyApp:
    def __init__(self):
        self.bp = Blueprint("app")
        handler = wraps(self.route)(partial(self.route))
        self.bp.add_route(handler, "/route")

    def route(self, request):
        return text("hi")
```

I've tested this, and it works exactly as expected. (And actually I will keep this in mind to implement in one of my applications in the future.)
