### ISSUE TITLE
aiofiles shows py3.8 deprecation warning on >=5.0.0 and shows during install of latest sanic

### ISSUE THREAD

**Issue by sloev** [huge-success/sanic#1952]
**Describe the bug**
in python3.8
pip install --upgrade sanic
installs aiofiles>=0.3.0 (according to https://github.com/huge-success/sanic/blob/master/setup.py#L81)
which installs aiofiles==5.0.0 
which is incompatible with python3.8 according to https://github.com/Tinche/aiofiles/issues/84

**Code snippet**
no solution really except getting aiofiles to release version 6.0.0 which will fix this:
https://github.com/Tinche/aiofiles/issues/84#issuecomment-700544607

**Expected behavior**
install without "@coroutine decorator deprecated" warnings 

**Environment (please complete the following information):**
 - OS: osx/linux debian
 - Version ...?

**Additional context**

**Comment by sjsadowski** [comment]
Thanks for letting us know; we may need to update the pin once 0.6.0 is released
