### ISSUE TITLE
multidict 5.1.0 conflicts with sanic==19.12.4

### ISSUE THREAD

**Issue by autumnjolitz** [huge-success/sanic#1977]
**Describe the bug**
multidict is locked to 5.0.0 on Sanic==19.12.x. Various packages like `aiohttp` use `multidict>=5.0.0,<6.0.0a0` as a minor release (or even bugfix) should not break the effective API.

Commit (https://github.com/huge-success/sanic/commit/d0f0e73e96fc7bd22e49c90cff75e33cf8befbd9#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) for the 20.x series uses this version specifier as well.

**Code snippet**

```
Fateweaver:~$ python -m venv test_env
Fateweaver:~$ cd test_env/
Fateweaver:~/test_env$ PIP_EXTRA_INDEX_URL='' ./bin/python -m pip install -U pip
Requirement already satisfied: pip in /Users/autumn/.virtualenvs/cpython36/lib/python3.7/site-packages (20.3.1)
Fateweaver:~/test_env$ PIP_EXTRA_INDEX_URL='' ./bin/python -m pip install multidict==5.1.0 sanic==19.12.4
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install multidict==5.1.0 and sanic==19.12.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested multidict==5.1.0
    sanic 19.12.4 depends on multidict==5.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Fateweaver:~/test_env$ PIP_EXTRA_INDEX_URL='' ./bin/python -m pip install multidict==5.1.0 sanic==20.9.1
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install multidict==5.1.0 and sanic==20.9.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested multidict==5.1.0
    sanic 20.9.1 depends on multidict==5.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Fateweaver:~/test_env$
```

**Expected behavior**
Sanic plays well with multdict==5.1.0

**Environment (please complete the following information):**
 - OS: OSX, 18.7.0
 - Version 19.12.4, 20.9.1

**Additional context**

**Comment by ashleysommer** [comment]
Hi @autumnjolitz 
This is a known issue and is already fixed in master: https://github.com/huge-success/sanic/pull/1969
It will be released as part of the Sanic 20.12 release.

**Comment by autumnjolitz** [comment]
@ashleysommer Will this be a part of the 19.x series?

**Comment by ahopkins** [comment]
@autumnjolitz Yes. I will release this with 19.X at the same time we release 20.X. Probably next week.

**Comment by autumnjolitz** [comment]
Hey @ahopkins , @ashleysommer ,

I've been running with an `"multidict>=5.0.0,<6.0.0a0"` in my fork `https://github.com/autumnjolitz/sanic/tree/v19.12.5` for several months without issue. I've noticed that this change never made it back to the 19.12LTS branch.

Would it be possible for `https://github.com/autumnjolitz/sanic/commit/f7b46d920e31c03bd617706b97f121e8fd3fa924` to make it into 19.12 LTS?

**Comment by ahopkins** [comment]
See #2027 which I am preparing for release now.
