### ISSUE TITLE
Get into TechEmpower benchmarks

### ISSUE THREAD

**Issue by seemethere** [huge-success/sanic#53]
I think it'd be useful to have sanic in the TechEmpower benchmarks so that more users can discover it.

The instructions to get in are found here:
https://www.techempower.com/benchmarks/#section=code

And sample applications can be found here:
https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by GMLudo** [comment]
Hi,

I'm the maintainer of AsyncIO branch of TechEmpower Benchmarks (BTW, you've a typo in the title).
I'm working to integrate sanic in the test suite with multi-worker pattern to be fair with other benchmarks.

Stay tuned, I'll publish a branch when I'll be ready.

Have a nice week.

**Comment by channelcat** [comment]
@GMLudo awesome!  I hope to have multi-worker (using python multiprocessing and asyncio.create_server with reuse_port) pushed by tonight, so hopefully that saves you time :).  The syntax should just be 

```python
app.run(host='0.0.0.0.0', port=80, workers=4)
```

**Comment by channelcat** [comment]
Just an update - multiprocessing was added with pr https://github.com/channelcat/sanic/pull/57 and was pushed to pypi as well

**Comment by GMLudo** [comment]
Hi @channelcat, thanks for the multi-worker implementation.

I've made a first draft: https://github.com/Eyepea/FrameworkBenchmarks/commit/21517227fd45b79d7ca39df8534aff8389ae2e53
Interested by your feedbacks.

I need a patch in Sanic to work: https://github.com/Eyepea/sanic/commit/7dcdc6208dc8b69d2ba1ea9826f7bd7b226c690c
I'm sending a PR for that.

I've did some measures with wrk, it seems unbelievable when I compare with existing benchmark suite, at least on my hardware, congratulations ;-)
However, I don't publish numbers, I prefer to wait that TechEmpower publishes official numbers for the next round.

I hope to finish to integrate the complete test suite, with postgresql, mysql and redis support during the week-end for an official PR to TechEmpower.

Have a nice week.

**Comment by GMLudo** [comment]
Hi @channelcat,

I don't forget you, but I've several constraints right now. I hope to finish for the end of this week.

**Comment by seemethere** [comment]
@GMLudo Do we have an update on this?

**Comment by GMLudo** [comment]
@seemethere I've 500+ e-mails to read but I've made a branch for that.
It should be ok for round 14.

**Comment by feluxe** [comment]
I just saw the benchmarks from 2018 and am a little surprised to find Sanic so far down the list:

https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=plaintext

**Comment by yunstanford** [comment]
not sure how it hooks up, but sth. is wrong obviously as you can tell from the error count and the number...
https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=json shows different. 
I'm not sure how the number comes out..

**Comment by r0fls** [comment]
21 requests per second 😢 where is the file they used for testing?

**Comment by frmdstryr** [comment]
Round 16 was released:
https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=json

Sanic looks much better now on the json test but still has a very high number of errors on the plaintext benchmark.  

My guess would be because of the different concurrency levels:

- json benchmark -   "The request handler will be exercised at concurrency levels ranging from 8 to 256." 
-  plaintext benchmark -  "The request handler will be exercised at 256, 1024, 4096, and 16,384 concurrency."

**Comment by stalkerg** [comment]
it seems like broken right now, can somebody fix sanic in TechEmpower?

**Comment by stalkerg** [comment]
Did PR https://github.com/TechEmpower/FrameworkBenchmarks/pull/9304
