### ISSUE TITLE
App route delegation and composition (nesting routes)

### ISSUE THREAD

**Issue by graingert** [huge-success/sanic#554]
I'd like to split my app into multiple independent modules:

```python
# datascience/service/ham/app.py

from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

```python
# datascience/service/app.py

from sanic import Sanic

from datascience.service.spam.app import app as spam_app
from datascience.service.ham.app import app as ham_app


app = Sanic()

app.route("/", spam_app)
app.route("/test", ham_app)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

**Comment by graingert** [comment]
this way /test/ -> datascience.service.ham.app.test

**Comment by r0fls** [comment]
Why not use two blueprints in each module, then have one parent module that imports and runs them both?

**Comment by graingert** [comment]
@r0fls It's also not as elegant as app composition:

* you can't nest blueprints
* you can't boot a subset of your application with a blueprint
* It lets you use an app as a blueprint after configuration

Nestable apps exist in frameworks like Express or WSGI applications

**Comment by seemethere** [comment]
One solution could be to recursively import submodules using something similar to:

```python
def import_all_submodules(module):
    if isinstance(module, basestring):
        module = importlib.import_module(module)
    for _, modname, _ in pkgutil.walk_packages(
            path=module.__path__,
            prefix=module.__name__ + '.',
            onerror=lambda x: None):
        __import__(modname, fromlist=[])
```

**Comment by graingert** [comment]
@seemethere that looks like dark magic

**Comment by seemethere** [comment]
@graingert I mean I had to sacrifice a goat to write it so it basically is 👿

**Comment by graingert** [comment]
And it's not really what I want. I still want to import the apps I need explicitly

**Comment by seemethere** [comment]
Yeah judging from the usage example you provided I would say you are describing a Blueprint.

Maybe there needs to be an extension to the Blueprint's functionality in order to meet your needs?

**Comment by graingert** [comment]
Can you install a blueprint in a blueprint?

**Comment by seemethere** [comment]
I mean the functionality could be there if wanted

**Comment by ashleysommer** [comment]
@graingert 
I only just came across this issue. If you do not want to use Blueprints, this is the perfect use-case for the Dispatcher extension (shameless plug, I am the author).

There is even an example in the readme showing how to do what you want.

Github page is here: https://github.com/ashleysommer/sanic-dispatcher

**Comment by danpozmanter** [comment]
You could mimic a django like approach. Check out the `add_routes` method: https://github.com/danpozmanter/jawaf/blob/master/jawaf/server.py

You basically use a config file to specify which apps you explicitly want to include. (The way I've done it, it works with apps in the project directory, as well as any apps installed as python packages that have a `routes.py` and `views.py` defined). But you could roll it a few ways depending on what you want to build.

**Comment by RafRaf** [comment]
Hey @graingert 
It seems like I've implemented something you talking about.
[Sanic-router](https://github.com/RafRaf/sanic-router) - is a simple, django-like route controller.

**Comment by sjsadowski** [comment]
There are multiple solutions for this now and if blueprints are an option, nested blueprints are in the current release.
