### ISSUE TITLE
Include script to run performance tests

### ISSUE THREAD

**Issue by blakev** [huge-success/sanic#62]
Via `contributing.md`:

> One of the main goals of Sanic is speed. Code that lowers the performance of Sanic without significant gains in usability, security, or features may not be merged.

I'm afraid to make any "big" change attempts without knowing the exact way you're running the speed tests.

**Comment by eseglem** [comment]
Check https://github.com/channelcat/sanic/tree/master/tests/performance then run `wrk` on them. 

You could probably run `wrk -t50 -c100` or something similar against https://github.com/channelcat/sanic/blob/master/tests/performance/sanic/simple_server.py before and after making changes. The exact numbers may not match the main readme, but they will give you a relative change.

**Comment by hainm** [comment]
should also add `golang` to benchmark too: https://github.com/channelcat/sanic#benchmarks

**Comment by sjsadowski** [comment]
I'm going to go ahead and close this - it's been open for 2.5 years with no further discussion - although there is some discussion on the current community forums (https://community.sanicframework.org) about benchmarking and speed.
