### ISSUE TITLE
AWS Lambda Support

### ISSUE THREAD

**Issue by heri16** [huge-success/sanic#688]
Does anyone know how to make sanic run in a serverless infrastructure like AWS Lambda?

**Comment by r0fls** [comment]
Right now you would have to follow this: http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

**Comment by heri16** [comment]
Seriously? Does sanic have a handle function that accepts 2 parameters?

**Comment by r0fls** [comment]
No I was just kidding.

**Comment by heri16** [comment]
Thank goodness. I thought somebody has been able to make it work with Zappa

**Comment by r0fls** [comment]
https://github.com/Miserlou/Zappa/issues/798

**Comment by Miserlou** [comment]
I think that Sanic isn't WSGI?

You may need this: https://github.com/ashleysommer/sanic-dispatcher

**Comment by seemethere** [comment]
@Miserlou You would be correct in assuming that Sanic does not have WSGI compatibility

And `sanic-dispatcher` does look awesome!

**Comment by Miserlou** [comment]
If anybody wants to try it, 

I think 

https://github.com/fifthecho/zappa-sanic

plus

https://github.com/Miserlou/Zappa/issues/798#issuecomment-299952245

should work

**Comment by mojimi** [comment]
I would like to point out that using Sanic with lambda is kinda pointless as it will invoke a new server for each request defeating Sanic's purpose.

I've found that using Flask with Zappa's beautiful async decorator https://blog.zappa.io/posts/zappa-introduces-seamless-asynchronous-task-execution is more than enough (it will simply call a new lambda instance)

**Comment by heri16** [comment]
Just a note, that's not how AWS Lambda works. AWS Lambda uses something like docker and pauses the instance when there are no pending requests or response. So it is indeed possible to have a long-lived server in AWS Lambda.

**Comment by mojimi** [comment]
> 
> 
> Just a note, that's not how AWS Lambda works. AWS Lambda uses something like docker and pauses the instance when there are no pending requests or response. So it is indeed possible to have a long-lived server in AWS Lambda.

It pauses but effectively dies, it won't route two requests to the same instance
