### ISSUE TITLE
Deployment Styles and Detailed Projects

### ISSUE THREAD

**Issue by Sniedes722** [huge-success/sanic#699]
The issues have recently been filled with questions about deploying to different services, as well as the desire to see more detailed open-source projects using Sanic. This is great, because it shows the traction Sanic is gaining within the Python web dev community. Showcasing detailed projects and deployment styles will only increase this traction, but what's the best way to go about it?

**Comment by r0fls** [comment]
it might be a good fit for that wiki @luizberti is always suggesting :)

**Comment by Sniedes722** [comment]
so far this is what I have in terms of deployments (with help from @r0fls) :
- a docker swarm with multiple nodes example
- a single node docker example (even though i agree that one is quite trivial)
- a kubernetes example
- a heroku example

Feel free to add on.

**Comment by Sniedes722** [comment]
@r0fls does it make sense to create and reference a seperate repo, something like "Awesome Sanic", to hold this on?

**Comment by r0fls** [comment]
That would work, i'm really pretty open minded as to where we store the list so we can let others chime in on that... first we need some examples! :)

**Comment by r0fls** [comment]
i mean they could also live in our existing examples directory, within the repo

**Comment by seemethere** [comment]
I think that as the wiki would be awesome. :+1:

**Comment by Sniedes722** [comment]
That might be better as one of the things I've always hated about Flask is nothing's centralized.

**Comment by Sniedes722** [comment]
I'm definitely down to take charge on the wiki. Where do we want it hosted?

**Comment by r0fls** [comment]
Apparently it can be enabled via github itself.

**Comment by seemethere** [comment]
@r0fls I think it would just take us making a splash page for the wiki.

But instead of doing it hastily let's talk about what should be featured on the index page.

**Comment by r0fls** [comment]
I think we should link to the below two categories, as well others as we come up with them:

- deployment options
- sites or projects using sanic

**Comment by Sniedes722** [comment]
what about also linking external blog posts like http://masnun.rocks/2016/11/17/exploring-asyncio-uvloop-sanic-motor/ as well?

**Comment by sjsadowski** [comment]
The conversation around stagnated nearly 2 years ago. I still think it would be good to include deployment guides in the docs, but I'm going to close this due to aging out.
