### ISSUE TITLE
worker recycling when memory leaks

### ISSUE THREAD

**Issue by hsvlz** [huge-success/sanic#713]
Hi,

in the case of small and slow memory leaks, it is usually beneficial to be able to recycling workers. Gunicorn proposes the max_requests flag to set the maximum number of requests a worker will process before restarting. 
Is there something similar that could be put in place within the sanic server, or do you just advise to use gunicorn with the sanic worker instead?

Thank you and keep up the good work!

**Comment by antinescience** [comment]
Gunicorn does it by keeping track of the number of requests on a specific worker and then, when it exceeds that limit, basically kills the worker off and brings it back up, as seen [here](https://github.com/benoitc/gunicorn/blob/2b839ca14437c61780d6eaaa8b24ad31e021f2c6/gunicorn/workers/sync.py#L173).

At least looking at `server.py`, you'd probably have to muck around with running something in `before_stop`. I'm not 100% clear on what that'd look like; might try to take a stab at this this week, as a recycle trigger (either by time, like IIS does, or max requests like Gunicorn) could be incredibly handy here.

**Comment by yunstanford** [comment]
Yeah, i am working on that part. it's very weak if it cannot hook up correct with gunicorn recycling feature. it's very import. I will send a PR out when i am done. i am also thinking a little refactoring work needs to be done for server.py module.
