### ISSUE TITLE
guideline to build extension

### ISSUE THREAD

**Issue by jongbatax** [huge-success/sanic#718]
how to build sanic extension?

**Comment by Sniedes722** [comment]
@jongbatax an extension can be built using anything you like that incorporates Sanic in some way! It does not necessarily have to even use Sanic as a dependency, but that is usually a good place to start. Check out the extensions page and look at some of them, maybe they will give you a good idea :-)

**Comment by seemethere** [comment]
We don't really have an official guideline.

The idea behind the extensions was that if Sanic doesn't fulfill your needs for your project you would somehow build things around it that would.

Then you could release the things that you built and post them on our extensions page to show to the world.

I don't think having formalized documentation around it would be for the best but I'd be open to it.
