### ISSUE TITLE
Add log file options to command

### ISSUE THREAD

**Issue by mohd-akram** [huge-success/sanic#721]
Something like `--access-logfile FILE` and `--error-logfile FILE` from Gunicorn.

**Comment by jrocketfingers** [comment]
The log file was removed in #706.

**Comment by r0fls** [comment]
is this still an issue?

**Comment by mohd-akram** [comment]
Yeah, I think this would be a very helpful feature. Likewise, a syslog option would be useful too. It seems Sanic already has code for this so it just needs to be integrated into the CLI.
