### ISSUE TITLE
Timeout when streaming response

### ISSUE THREAD

**Issue by jvlar** [huge-success/sanic#784]
It looks like Sanic will still raise a RequestTimeout when the response is streaming.

I'm proxying a file from another server, so while the user is downloading the streamed file, if it takes more than 60 seconds using the default timeout, the request will be cancelled.

Here's a small code example of what I'm doing:

```py
@file_bp.route('/file', methods=['GET'])
async def download_file(request: Request) -> StreamingHTTPResponse:
    url = generate_url(request)
    session = aiohttp.ClientSession()

    resp = await session.get(url, timeout=0,
                             headers=filter_headers(request.headers))
    content_type = resp.headers.get('Content-Type', 'text/plain')

    async def streaming_return(sanic_response: StreamingHTTPResponse):
        async for chunk in resp.content.iter_any():
            sanic_response.write(chunk)
        session.close()

    return stream(streaming_return, content_type=content_type)
```

Right now I've had to set the global timeout to something really so huge files can be downloaded without timing out, but I'd like to still have a smaller timeout for standard requests.

I don't think a request should timeout while streaming.

**Comment by yunstanford** [comment]
Yes, a request should not timeout while streaming actively.
But we should have timeout, the timeout should be between two successive read or write operations on client or proxied server connections. If no data is transmitted within this time, the connection is closed. 

Very slow connection/dead connection should be closed. It's very expensive for server to maintain too many connections simultaneously. 

Also, if you put a reverse proxy, like nginx in front of you application, nginx also has proxy_timeout.
It's just how we define the timeout.

**Comment by alexsv** [comment]
to deal with nginx for similar problem (but with different framework) I did two things:
1. added X-Accel-Buffering: no headers to prevent buffering results by nginx 
2. send headers, and then stream the rest content. Once nginx received some data from the application, it stopped generating 60s timeouts (we had a proxy_timeout configured at 60s)

**Comment by sjsadowski** [comment]
I'm closing as this is nearly two years old. I was not able to replicate this with a current version of sanic unless I specifically caused problems with the upstream proxy. We can open a new issue if we can find a way to replicate with sanic itself using 18.12 LTS or one of the 19.x releases.
