### ISSUE TITLE
Autobahn / WAMP support for websockets

### ISSUE THREAD

**Issue by mczp** [huge-success/sanic#797]
Hello, how difficult would it be to include support for the WAMP stack included in autobahn by default in sanic?
The current implementation based on websocket is just too basic to be useful for most use cases outside of an example, as it requires to manually rewrite the logic in order to keep track of connected clients, support for broadcasts, pub-sub, aka. reinventing the wheel.
Unless I'm missing something, I'm also open for suggestions about how to fully use the default websockets without actually rewriting WAMP myself.

**Comment by go2sh** [comment]
Sanic by design is a web server with websocket support, nothing more nothing less. I think protocols like wamp are to special to be included here. But, you can build a wamp router on top of sanic to support the wamp protocol, which could be an extension to the core.
FYI: WAMP is a protocol, not an server or any app. There are serves like (crossbar.io etc.) that implement the wamp protocol and there are clients (-libraries) to connect to a server.

**Comment by mczp** [comment]
Perhaps my wording was not accurate enough, I do understand that WAMP is a protocol, I was rather mentioning the point of either porting the current implementation of it as defined in autobahn or crossbar.io (to not reinvent the wheel) or even changing the underlying websocket module used by sanic into something more complete like the full autobahn ws library, which works ok with asyncio and provides support for WS extensions like WAMP.

**Comment by go2sh** [comment]
Hm, I'am not sure what is missing for you? The autobahn WebSocket support is not that different from the current support in sanic and the features are nearly the same.

If you want to use the wamp protocol on top of sanic just hook in like in this file from the autobahn repo:
https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/websocket.py

**Comment by mczp** [comment]
I've realized that WAMP might actually be more problematic compared to the likes of socket.io, thus decided to go with that instead.
FYI python-socketio has already integrations with sanic, perhaps it might be worth mentioning it in the docs somewhere, or even supply a working example.
