### ISSUE TITLE
RuntimeError: Event loop stopped before Future completed on Ctrl-C with open websocket connections

### ISSUE THREAD

**Issue by intra-au** [huge-success/sanic#810]
What is the proper way to shutdown the server if it's running some sleeping tasks?

I'm trying to stop the server running the following code with Ctrl-C:
```
async def on_server_start():
  while 1:
    with sql_connect() as conn:
      conn.execute("DELETE from connections where disconnected > 0 and disconnected < ?",(time.time()-1800,))
    await asyncio.sleep(300)

if __name__ == '__main__':
    log.info("Server started...")

    app.add_task(on_server_start())
    try:
      app.run(host="127.0.0.1", port=8083,debug=False)
    except KeyboardInterrupt:
      app.stop()
```

However I get only:
^C2017-06-21 02:38:08 - (sanic)[INFO]: Stopping worker [14215]

and when I press Ctrl-C again I get traceback
```
Traceback (most recent call last):
  File "/home/intra/OST/ost3/lib/python3.5/site-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/home/intra/OST/ost3/lib/python3.5/site-packages/sanic/server.py", line 467, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1201, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25597)
RuntimeError: Event loop stopped before Future completed.
2017-06-21 02:26:32,205:ERROR:sanic:Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/intra/OST/ost3/lib/python3.5/site-packages/sanic/app.py", line 559, in run
    serve(**server_settings)
  File "/home/intra/OST/ost3/lib/python3.5/site-packages/sanic/server.py", line 467, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1201, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25597)
RuntimeError: Event loop stopped before Future completed.
```

**Comment by yunstanford** [comment]
app has already registered those system signals.
https://github.com/channelcat/sanic/blob/master/sanic/server.py#L476

it will catch ctrl-c, then stop the server and also close the loop for you. https://github.com/channelcat/sanic/blob/master/sanic/server.py#L507

You should not call app.stop(), which is essentially just close the loop again. That caused your problem.

**Comment by intra-au** [comment]
@yunstanford Well, if I just do app.run I still have the same issue - it hangs on ^C2017-06-21 02:38:08 - (sanic)[INFO]: Stopping worker [14215]

I believe it's something to do with open websocket connections. Server is waiting for them to close instead of forcefully closing them.

**Comment by yunstanford** [comment]
ctr-c(SIGINT) should be an graceful shutdown. Sanic will complete current connections before shutdown.

Does it hang forever/very long time ?

**Comment by intra-au** [comment]
it justs wait for websockets to be disconnected and it quits as soon as I disconnect my websocket (close browser tab)

**Comment by yunstanford** [comment]
Ok, i may know the issue now... but Can you still post a snippet of your code to reproduce ?

**Comment by intra-au** [comment]
Thanks @yunstanford 
Please use example from python-socketio, it can be used to reproduce this issue:
https://raw.githubusercontent.com/miguelgrinberg/python-socketio/master/examples/sanic/app.py
