### ISSUE TITLE
Migrating or coexisting with Django's ORM

### ISSUE THREAD

**Issue by pranaysharma** [huge-success/sanic#832]
Hi ,
We are considering to use Sanic for Async operations in our project.
As its a live project and we are resource constrained so we cant migrate on day zero our whole system to sanic. Currently we are using Django.

The biggest challenge that I feel so far in doing is accessing and managing database. Our DB is in Postgres.
In django its super easy to write queries/change the schema/make migrations etc.
So is there a way via which we can use the Django's ORM(or similar) to manage our database(and do migrations etc) while writing new code in Sanic?
And is that recommended 

Thankyou for your time

**Comment by yunstanford** [comment]
You can use an async driver for managing ur db.

For Postgres, you may wanna use https://github.com/aio-libs/aiopg.

**Comment by mikekeda** [comment]
you can try peewee http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#djpeewee
https://github.com/Sanic-Extensions/sanic-peewee

**Comment by danpozmanter** [comment]
https://github.com/MagicStack/asyncpg Is worth looking into, as is SQLAlchemy (and https://github.com/CanopyTax/asyncpgsa). It's quite fast. The thing is SQLAlchemy core is what you'll be looking at. You'll want https://pypi.python.org/pypi/alembic for migrations.

Thus far there isn't an async ORM that can function as a drop in replacement for Django ORM.

**Comment by jonahfang** [comment]
You can try: https://github.com/monobot/asyncorm, it is like Django ORM.

**Comment by jonahfang** [comment]
I have used the lastest version of https://github.com/fantix/gino, and it is very good.
