### ISSUE TITLE
Conda forge package

### ISSUE THREAD

**Issue by kszucs** [huge-success/sanic#848]
Does anyone plan to create a sanic-feedstock for conda-forge repository?

https://conda-forge.org/

**Comment by r0fls** [comment]
No plans that we're aware of. Please feel free to tackle this @kszucs if you have time.

**Comment by kszucs** [comment]
Actually I've already created the recipes for sanic and its missing (from conda-forge) dependencies.

The only problem, that conda forge feedstocks (https://github.com/conda-forge) needs maintainers to periodically update the recipes (versions, dependencies etc). I guess the maintainer should be one of sanic's core developer (e.g. You).

I've uploaded the recipes here: https://github.com/kszucs/sanic-conda

**Comment by kszucs** [comment]
@r0fls here is the ongoing PR, I've added You as a maintainer too.

**Comment by kszucs** [comment]
@channelcat/sanic someone who is willing to be a co-maintainer for the conda-forge package?

**Comment by sjsadowski** [comment]
Is this still something we want to keep pursuing? @r0fls

**Comment by ahopkins** [comment]
@kszucs I am going to reopen it because: Let's add `conda install sanic` to the docs. I didn't even realize that this option already existed.

**Comment by ahopkins** [comment]
See #1576

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/sanic-20-12-conda-package-for-python-3-9/809/2
