### ISSUE TITLE
Issue running multiple test client tests: Route already registered

### ISSUE THREAD

**Issue by keattang** [huge-success/sanic#849]
Hello, 

I have an app that looks something like this:

app.py
```
from core.routes import add_core_routes
from sanic import Sanic

app = Sanic(__name__)

@app.listener('before_server_start')
async def add_routes(app, loop):
    await add_core_routes(app, loop)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, workers=4, debug=True)
```

core/routes.py
```
def get_healthcheck(loop):
    async def healthcheck(request):
        # Some healthcheck that uses the loop
    return healthcheck

async def add_core_routes(app, loop):
    app.add_route(get_healthcheck(loop), '/healthcheck/', methods=['GET'])
```

tests/test_healthcheck.py
```
import unittest
from app import app

class HealthcheckTestCase(unittest.TestCase):

    def test_success(self):
        req, resp = app.test_client.get('/healthcheck/')
        self.assertEqual(resp.status, 200)

    def test_fail(self):
        req, resp = app.test_client.get('/healthcheck/')
        self.assertEqual(resp.status, 500)
```

Whenever I try to run the tests using `python -m unittest discover` I get the error `sanic.router.RouteExists: Route already registered: /healthcheck/ [GET]` on the second test.

Is this a bug or am I doing something wrong?

Your help is much appreciated.

**Comment by yunstanford** [comment]
1. usually, you should not use the global app for testing.
2. You may also need Setup/TearDown in your TestCase.

I'd suggest you to use pytest https://docs.pytest.org/en/latest/

**Comment by yunstanford** [comment]
BTW, it errors out because the app.test_client calls `app.run` in each single call. https://github.com/channelcat/sanic/blob/master/sanic/testing.py#L69

**Comment by keattang** [comment]
Are you suggesting that I wrap
```
app = Sanic(__name__)

@app.listener('before_server_start')
async def add_routes(app, loop):
    await add_core_routes(app, loop)
```

in a function and call it in `app.py` and also in a `setUp` method on my tests? What if I want to do multiple client calls in the same test? Do I have to create a new app for every one?

**Comment by yunstanford** [comment]
you can try initialize `app` in Setup, and clean it up in `teardown`. Also share the same app inside your TestCase.

**Comment by keattang** [comment]
That still doesn't allow me to make multiple client calls in the same test function.

**Comment by keattang** [comment]
This feels like a bug to me. I'm happy to make a PR if you can point me in the right direction? Perhaps `test_client` needs to be a function that sets up an app that runs once and is shared amongst all calls to that client?

**Comment by yunstanford** [comment]
i tried
```python
def test_sync():
    app = Sanic('test_text')

    @app.route('/')
    def handler(request):
        return text('Hello')

    request, response = app.test_client.get('/')

    assert response.text == 'Hello'

    request, response = app.test_client.get('/')

    assert response.text == 'Hello'
```
works fine for me.

**Comment by yunstanford** [comment]
But yes, i agree, just running once is good.

**Comment by sjsadowski** [comment]
This issue stagnated and I'm pretty sure current testing has only one setup/teardown.
