### ISSUE TITLE
Sanic instalation on Windows

### ISSUE THREAD

**Issue by lucasvfventura** [huge-success/sanic#855]
Hi,

In order to install Sanic on Windows I went over the instructions to install it without uvloop and ujson, commands:
set SANIC_NO_UVLOOP=true
set SANIC_NO_UJSON=true
pip install sanic

I got the follow output, with the exception of {User} was my user:
Collecting sanic
  Downloading sanic-0.5.4-py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 290kB/s
Collecting websockets>=3.2 (from sanic)
  Downloading websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting aiofiles>=0.3.0 (from sanic)
  Downloading aiofiles-0.3.1-py3-none-any.whl
Collecting ujson>=1.35 (from sanic)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 3.1MB/s
Collecting uvloop>=0.5.3 (from sanic)
  Downloading uvloop-0.8.0.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 3.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\{User}\AppData\Local\Temp\pip-build-rnj1hcy_\uvloop\setup.py", line 11, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment

Although when I clone the project and do the following commands, it is successfully installed:
set SANIC_NO_UVLOOP=true
set SANIC_NO_UJSON=true
pip install .

**Comment by jamesstidard** [comment]
It might make it a little more friendly to use sanic to tweak the `setup.py` to check the system it's installing on:

```python
# setup.py
...
is_windows = sys.platform.startswith("win")
if strtobool(os.environ.get("SANIC_NO_UJSON", "no")) or is_windows:
    print("Installing without uJSON")
    requirements.remove(ujson)

# 'nt' means windows OS
if strtobool(os.environ.get("SANIC_NO_UVLOOP", "no")) or is_windows:
    print("Installing without uvLoop")
    requirements.remove(uvloop)
...
```

Or along the lines of #916 maybe make `ujson` and `uvloop` `extras_require ` so you opt-in on pip install with `pipenv install sanic[ujson,uvloop]`.

**Comment by sjsadowski** [comment]
With the 0.8.x release, this should be resolved.
