### ISSUE TITLE
Support for APISpec

### ISSUE THREAD

**Issue by rdehouss** [huge-success/sanic#891]
Hello!

Despite the effort on sanic-openapi, it would be great to have a plugin for apispec.
One exists for Flask but I couldn't easily port the Flask extension for sanic, it's still quite different internally.

https://github.com/marshmallow-code/apispec

https://github.com/marshmallow-code/apispec/blob/dev/apispec/ext/flask.py

WDYT?

Thanks!

Cheers,

Raphaël Dehousse

**Comment by sjsadowski** [comment]
I'm actually going to close this. A plugin can be created if desired, but with the reorganization and ownership borders that were set up in 2018, I don't think this fits in the core sanic project.
