### ISSUE TITLE
"Currently you cannot build a URL for a static file using 'url_for'."

### ISSUE THREAD

**Issue by GoodiesHQ** [huge-success/sanic#906]
The quote is from the [docs for Static Files](http://sanic.readthedocs.io/en/latest/sanic/static_files.html).

I would like some discussion based on this issue. I cannot call `app.url_for('/static', 'style.css')`, for example, which is hindering my ability to properly render templates with `jinja2`. Why can the `url_for` method not be used the same way `app.route`-registered handlers can be used, considering `sanic.Sanic.static(...)` is just  a wrapper for `route(...)`.

**Comment by lixxu** [comment]
I'm thinking about adding this feature, and perfer this way: `app.url_for('static', name='static', filename='style.css')` where `name` is used for different folders, and you can use it for other static resources (`/uploads/logo.jpg`), e.g. `app.url_for('static', name='uploads', filename='logo.jpg')`
The format is: `url_for('static', name='static_name', filename='xxx')`
@r0fls if you think it's make sense, I'll make a PR for it.

**Comment by OdinTech3** [comment]
What if the file was nested like logo.jpg was in /uploads/module_one/logo.jpg?

**Comment by lixxu** [comment]
`filename='module_one/logo.jpg'`
