### ISSUE TITLE
Starting sanic in a thread? (ValueError: set_wakeup_fd only works in main thread)

### ISSUE THREAD

**Issue by olalonde** [huge-success/sanic#907]
I have a test.py file where I'm trying to start my sanic server from a separate thread:

```python
def start_server():
    create_app().run(
        port=5000,
        debug=False
    )


def main():
    # start app in background thread
    t = threading.Thread(target=start_server, name='server', daemon=True)
    t.start()
main()
```

I am however getting the following error:

```python
2017-08-21 22:14:47 - (sanic)[INFO]: Goin' Fast @ http://127.0.0.1:5000
2017-08-21 22:14:47 - (sanic)[ERROR]: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users/olalonde/.pyenv/versions/rise/lib/python3.6/site-packages/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/Users/olalonde/.pyenv/versions/rise/lib/python3.6/site-packages/sanic/server.py", line 520, in serve
    loop.add_signal_handler(_signal, loop.stop)
  File "uvloop/loop.pyx", line 2269, in uvloop.loop.Loop.add_signal_handler (uvloop/loop.c:41305)
ValueError: set_wakeup_fd only works in main thread
```

Is it not possible to start sanic outside the main thread?

**Comment by rdehouss** [comment]
Same question

**Comment by Phil192** [comment]
Same question

**Comment by yunstanford** [comment]
This looks normal, what is the point for running it in separate thread ? Any motivation?

**Comment by rdehouss** [comment]
Think of an existing application where you'd want to add a webserver using sanic to receive or return data.

**Comment by yunstanford** [comment]
A separate process might be better, as python process can't span multiple CPU cores.

**Comment by c-goosen** [comment]
Yeah async frameworks/code are great in a single threaded environment. Single threaded event loop that moves blazing fast. You could use uwsgi, which will spawn multiple workers on differen't CPUs, but your code might have to be tweaked for this.  If you are building a simple API with a logical request & response loop uwsgi will work well. See example 
[uwsgi]
socket = /tmp/%n.sock
module = werkzeug.testapp:test_app
processes = 4
master = 1

**Comment by cbess** [comment]
What if I don't want to run a separate thread? Should this still work, and if so, how?

**Comment by vltr** [comment]
@cbess take a look at the _limitations_ when [running subprocesses with asyncio](https://docs.python.org/3/library/asyncio-subprocess.html#subprocess-and-threads) :wink:

**Comment by cbess** [comment]
> @cbess take a look at the _limitations_ when [running subprocesses with asyncio](https://docs.python.org/3/library/asyncio-subprocess.html#subprocess-and-threads) 😉

Ah! Thanks for the info

**Comment by ahopkins** [comment]
Seeing no further discussion, I am closing.
