### ISSUE TITLE
add_task will launch multi times when app run with multi workers

### ISSUE THREAD

**Issue by zzeric** [huge-success/sanic#911]
[2017-08-23 22:04:09,755] 4173-INFO server::notify_server_started_after_five_seconds():l21: task started!
[2017-08-23 22:04:09,760] 4174-INFO server::notify_server_started_after_five_seconds():l21: task started!

Actually the task should be run once。
So maybe add_task must bind on one worker

**Comment by yunstanford** [comment]
No, these tasks should be run by all workers. Let's say you have,
```python3
@app.listener('before_server_start')
    async def init_db(app, loop):
        # Init Db
```
All workers should have connections to db, they are separate processes. Shutdown one worker should have no effects on other workers.

But you can talk more about your use case if you wanna.

**Comment by singleton11** [comment]
For example, I have migrations which should be executed only by one worker

**Comment by yunstanford** [comment]
Maybe, i don't understand your example, but if you just wanna execute one time, why do you put `migration` in a `listener` ? Let's say if someone redeploy your service, it will execute migration again..
