### ISSUE TITLE
memory leak.

### ISSUE THREAD

**Issue by larry-dev** [huge-success/sanic#918]
I use:
sanic 0.6
python-socket.io
aioredis
aiohttp client
sqlalchemy

As my users continue to enter, my thread memory continues to increase. Until the thread crashes.
When i use aiohttp +python-socket.io ,this problem does not appear.

@seemethere Can you help me?

**Comment by yunstanford** [comment]
yeah, memory leak is annoying, it also appears in tornado, aiohttp, or other python webframeworks. use `gunicorn` could solve your problem by recycling workers/processes.

**Comment by r0fls** [comment]
@larry-dev just to confirm you're using websockets right? I could reproduce this with websockets but not without them.

**Comment by r0fls** [comment]
@miguelgrinberg any chance you might be able to look into this? I added a line to log memory usage and number of python objects (class, dict, etc...) in the ws route to verify, but wasn't able to fix it with my attempts.

**Comment by larry-dev** [comment]
yes。
i use socket.io ,aioredis,aiomysql

**Comment by miguelgrinberg** [comment]
I'll see if I can figure it out. Couple of questions:

- What Python version has this been seen?
- How many users does it take to crash?

**Comment by miguelgrinberg** [comment]
@r0fls what did you do to see this leak? I'm using the `websocket.py` example. I added a memory report in the HTTP route and then connected to this app and hit refresh several times to generate a lot of connects and disconnects

- Memory usage started at 19.5MB
- After 10 refreshes, it was at 21.3MB
- After 20 refreshes it was at 21.7MB
- I did something like 50 more refreshes, at still got 21.7MB usage

This looks fairly normal to me and not indicative of a memory leak. Have you tested differently?

**Comment by larry-dev** [comment]
@miguelgrinberg   I run in production environment, with about more than 300 users.
my environment:

- python 3.6.1
- sanic 0.6

**Comment by miguelgrinberg** [comment]
@larry-dev how did you determine there is a memory leak? The more users concurrently join your application, it is expected that memory will increase. There would be a leak only if when those 300 users are replaced by another 300 users memory continues to increase significantly.

**Comment by larry-dev** [comment]
@miguelgrinberg My project is constantly having users joining and exiting. Memory will continue to increase at this point. About 18 hours or so, the python thread collapsed.

**Comment by r0fls** [comment]
@miguelgrinberg I did see memory seem to go up linearly, but admittedly didn't test as extensively (10 connections). What I did do that was pretty convincing was make a route something like this:

```
from sanic import Sanic
from sanic.response import file
from sanic.config import Config

app = Sanic(__name__)

@app.route('/')
async def index(request):
    return await file('websocket.html')


@app.websocket('/feed')
async def feed(request, ws):
    while True:
        objgraph.show_most_common_types()
        data = 'hello!'
        print('Sending: ' + data)
        await ws.send(data)
        data = await ws.recv()
        print('Received: ' + data)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000, debug=True)
```

As you close the browser or tab and reopen it (or however you're testing), you should see the number of some item (I think it was dict) continue to increase endlessly. I think it was going up 5, then removing one upon closed connection or something. Similar with some other object(s) ¯\\_(ツ)_/¯

**Comment by raphaelauv** [comment]
@ahopkins maybe time to close this issue ?

**Comment by Tronic** [comment]
It might be preferable to avoid cyclic references between per-request objects. While this will be collected by the GC eventually, some might disable GC, and even if enabled, it is nicer to have that memory freed instantly when the request ends.

In recent years there have been no reports of leaks, so I am closing this with a note that directionality of object ownership should be observed by core developers, in an effort to avoid reliance on GC. Shared data should go in objects that do not refer back to their owners. AFAIK this is already pretty well handled in Sanic.
