### ISSUE TITLE
Error in motor example

### ISSUE THREAD

**Issue by lvalladares** [huge-success/sanic#919]
Im deploying sanic using blueprints and gunicorn, my database is mongoDB so i use motor to make the connections i followed the example in here: https://github.com/channelcat/sanic/wiki/Examples#motor but when i try to query the database i get this error:

`RuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /usr/local/lib/python3.6/site-packages/sanic/app.py:503>> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.6/asyncio/futures.py:408]> attached to a different loop
`

I solved it passing the loop to motor, basically changing

`db = AsyncIOMotorClient(mongo_uri)['test']`

for

db = AsyncIOMotorClient(mongo_uri, io_loop=loop)['test']

 maybe the docs should be updated with this info

**Comment by aohan237** [comment]
you can use db in listeners , such as :

@app.listener('before_server_start')
async def setup_db(app, loop):
    app.db = AsyncIOMotorClient(mongo_uri)

then use app.db will solve the problem.

**Comment by tony-kerz** [comment]
@aohan237 (or others) i'm newer to python and not sure what the best way to reference `app.db` in a blueprint in another module from where the above `app.db = AsyncIOMotorClient(mongo_uri)` appears.

i get some import errors if i just try to import `app` straight up from a diff blueprint module (circular-reference issue?)...

do you happen to have any guidance around that (or maybe did you have all references to `app.db` in a single module)?

best, tony.

**Comment by aohan237** [comment]
@tony-kerz as for me .. 
 if you want to init just a bp, you can add blueprint listener.
if you want to just use this instance ,you may use request.app.db

**Comment by qwexvf** [comment]
@aohan237's solution example using just instance,
for example,
```Python
@app.listener('before_server_start')
def init(app, loop):
    app.db = AsyncIOMotorClient(mongo_uri)

@app.route('/objects', methods=['GET'])
async def get(request):
    # here
    docs = await request.app.db.test_col.find().to_list(length=100)
    for doc in docs:
        doc['id'] = str(doc['_id'])
        del doc['_id']
    return response.json(docs)
```
Give a try!

**Comment by hieu-n** [comment]
Thank you, guys. I came to this from google. I didn't know `app` is attached to `request`. `request.app` solves my issue.

**Comment by rt-garcia** [comment]
Hi. I'm trying to replicate this but it raises an exception saying that app has no db property, is this still viable or the current Sanic version doesn't support the db property anymore?

**Comment by ahopkins** [comment]
@rt-garcia  I cannot speak to this example as I am not familiar with motor. However, you are free to add properties to the app instance.

```python
from sanic import Sanic
from sanic.response import json, text

app = Sanic("__BASE__")


async def setup_db():
    return {}


@app.listener("after_server_start")
async def task_start(app, loop):
    app.db = await setup_db()


@app.post("/")
async def save(request):
    request.app.db.update(request.json)
    return text("Done")


@app.get("/")
async def retrieve(request):
    return json(request.app.db)


if __name__ == "__main__":
    app.run(access_log=False, debug=True, port=9999)
```

```bash
$ curl localhost:9999 -d '{"foo": "bar"}' -X POST
Done
$ curl localhost:9999
{"foo":"bar"}
```

For further discussion please open a new issue. or for support inquiries, please post on the [forums](https://community.sanicframework.org/c/questions-and-help/6).
