### ISSUE TITLE
Making Webhooks Easier

### ISSUE THREAD

**Issue by cshenton** [huge-success/sanic#970]
I'm working on a project that mainly does long-running tasks, so it is pretty callback heavy. Currently my plan is to use `sanic` to receive the request, then `aiohttp` to make the http POST once the result is processed.

However I was thinking it would be nice to have some simple functionality in sanic of the form:
```python
from sanic.response import json

@app.callback('/my-endpoint', 'callback_url')  # second arg denotes expected field for callback url
async def my_endpoint(request):
    data = request.json
    yield json({'message': 'Request Received'})
    result = await some_task_queue(data)
    return json(result)
```

The idea being that sanic takes the `yield`ed data to be the response, and takes the `result` to be the data payload for the callback (to the url it infers from the request). Though this wouldn't work more generally using webhooks for something like subscriptions, perhaps just a callback convenience method would work there.

Is this the kind of thing that makes sense to sit in the core of sanic?

**Comment by ashleysommer** [comment]
I like it, it is a good feature request and I can see its usefulness.

Im not sure if it would make sense to be in the sanic core, but it should be possible with a sanic plugin.

One main problem I see is in your example `my_endpoint` is an Async Generator.

Async Generators were introduced in Python 3.6, and Sanic (while being a bleeding edge python project) _does_ like to maintain compatibility with Python 3.5.

I might do some research to see if its possible to achieve the same thing without using Async Generators.
