### ISSUE TITLE
_protocol does not exist for python3.5 on some distribs 

### ISSUE THREAD

**Issue by arthurlenoir** [huge-success/sanic#973]
I try to run Sanic on Amazon Linux AMI instance with SSL and I got the two following errors:
`AttributeError: '_SSLProtocolTransport' object has no attribute 'get_protocol'
AttributeError: '_SSLProtocolTransport' object has no attribute '_protocol'`

I temporary fixed the error by replacing 
`protocol = request.transport._protocol`
by
`protocol = request.transport._app_protocol`
after inspecting the transport object. 

Does someone know why is it perfectly working with ._protocol on Ubuntu, but not on Amazon Linux? 

Thanks for your help!

https://github.com/channelcat/sanic/blob/006fb08024bab3dda56ae05fa1a52366bc162804/sanic/app.py#L255

**Comment by skewty** [comment]
Will something like this suffice?

```python
if hasattr(request.transport, '_app_protocol')  # non-standard; used by Amazon AMI
    protocol = request.transport._app_protocol
else:  # typical for most deployments
    protocol = request.transport._protocol
```

**Comment by its-a-feature** [comment]
Yes, that fix seems to work. Any time frame on when this fix will be pulled into the main pip install?

**Comment by MyNameIsCosmo** [comment]
There is [no pull request](https://github.com/channelcat/sanic/pulls?utf8=%E2%9C%93&q=is%3Apr+_protocol) available for this issue.

If you'd like to see a fix merge upstream, for the repo, add the fix in, create a test, and submit a Pull Request.
