### ISSUE TITLE
Using global read-only resource for all requests

### ISSUE THREAD

**Issue by travisbrady** [huge-success/sanic#994]
I have an endpoint that makes use of a single read-only pre-trained machine learning model that we load from disk at time of `__init__` as a single at the top of my source file as below.
For each request, we munge some data and then call `predict` on the model class and return the result.

I'm seeing an issue where my app spends about 25% of its time (~24ms per call according to cProfile) and I believe this is because each worker is locking the shared model while calling `predict`. The thing is, the model is read-only, so there is no need to lock.

Is there a way to declare a resource to be specific to a worker? Or to otherwise solve this problem?
thank you

Dumb example:
```python
MODEL = load_model('model_file.pkl')
app = Sanic()

@app.post('/predict')
async def post_predict(request):
    data = get_data_from_request(request)
    ret = MODEL.predict(data)
    return ret
```

This is similar to this problem with Flask: https://stackoverflow.com/questions/42439553/how-to-share-in-memory-resources-between-flask-methods-when-deploying-with-gunic

**Comment by luizberti** [comment]
Sounds like you may be locking the event loop with whatever you're doing with your model.
Concurrent programming doesn't favor CPU bound task scheduling...

**Comment by yunstanford** [comment]
@travisbrady workers are separate processes, they are not sharing resources between each other.

**Comment by travisbrady** [comment]
@yunstanford That was my expectation, but when I change Sanic's worker count from 4 to 1 the time spent in `posix.waitpid` goes to zero as computed by cProfile.

**Comment by yunstanford** [comment]
@travisbrady  The main calling thread'll be blocked after process.join call https://github.com/channelcat/sanic/blob/master/sanic/server.py#L687, I guess you may not do it in the right way. you may wanna profile the `worker process` instead. try https://github.com/uber/pyflame, it can profile python process by attaching the pid, pretty cool.

**Comment by travisbrady** [comment]
@yunstanford Will give that a try. Thanks.

**Comment by tocab** [comment]
Is there any effort for this use case? I have the same problem, i want to load a word vector model at server start and then use the word vectors to do calculations on a get request.

**Comment by marvinxu-free** [comment]
> Is there any progress for this use case? I have the same problem, i want to load a word vector model at server start and then use the word vectors to do calculations on a get request.

did you resolved this problem?
