### ISSUE TITLE
Right way to save connect to amqp in sanic app?

### ISSUE THREAD

**Issue by SwordFighter** [huge-success/sanic#996]
Connect example:

`  
    import asyncio
    import aioamqp
    app = Sanic(__name__)

    @app.listener('before_server_start')
    async def setup_amqp_connection(app, loop):
        transport, protocol = await aioamqp.connect(
            host=app.config.get('AMQP_HOST'),
            login=app.config.get('AMQP_USER'),
            password=app.config.get('AMQP_PASS'),
            virtualhost=app.config.get('AMQP_VHOST'),
            port=app.config.get('AMQP_PORT'),
        )
        channel = await protocol.channel()
        app.transport = transport
        app.protocol = protocol
        app.channel = channel

        async def consume(app):
            async def handle_msg(channel, body, envelope, properties):
                print(" [x] %r" % body)

            await app.channel.basic_consume(handle_msg, queue_name='queue_name')

        async def test():
            while True:
                await asyncio.sleep(5)
                print('working')

        asyncio.ensure_future(test(), loop=loop)
        asyncio.ensure_future(consume(app), loop=loop)

    @app.listener('before_server_stop')
    async def close_amqp_connection(app, loop):
        await app.protocol.close()
        app.transport.close()

.... start sanic app
app.go_fast(
        host=HOST,
        port=PORT,
        debug=DEBUG,
        workers=WORKERS_NUM,
        log_config=LOGGING
    )
`

It s correct to use asyncio.ensure_future to start consuming in sanic app?
Why "app.add_task"  (app.add_task(test)) not working?

**Comment by sjsadowski** [comment]
@SwordFighter is this still an issue or were you able to solve it?
